// DISPOSABLE research contract — D872/Wave C C5. Not a production registry or implementation authority.
import { writeFileSync } from "node:fs";

import { describe, expect, it } from "vitest";

const OUTPUT = new URL("./consumer-matrix-output.md", import.meta.url).pathname;

type Consumer = "support" | "review" | "theory" | "bot" | "inspector" | "authoring";
type Timing = "precommit_requested" | "postcommit" | "review" | "analysis" | "offline";
type Distance = "square" | "relation" | "concept" | "candidate" | "move" | "line" | "evaluation";
type Grounding = "position_rules" | "recorded_run" | "bounded_search" | "tablebase_exact" | "citable_text";

interface CandidateProjection {
  readonly id: string;
  readonly producer: string;
  readonly grounding: Grounding;
  readonly operands: readonly [string, ...string[]];
  readonly abstention: readonly string[];
  readonly consumers: readonly [Consumer, ...Consumer[]];
  readonly timing: readonly [Timing, ...Timing[]];
  readonly answerDistance: readonly [Distance, ...Distance[]];
  readonly sourceCeiling: string;
  readonly workflowCeiling: string;
  readonly fixtures: { readonly positive: string; readonly hardNegative: string; readonly abstention: string };
  readonly availability: string;
}

const p = (value: CandidateProjection): CandidateProjection => Object.freeze(value);

const ROWS: readonly CandidateProjection[] = Object.freeze([
  p({ id: "rules.tactic.reading.defender_duty_set@1", producer: "rules.tactic", grounding: "position_rules", operands: ["defender", "defenderRole", "targets", "targetRoles", "coDefenders"], abstention: [], consumers: ["support", "review", "bot", "inspector", "authoring"], timing: ["precommit_requested", "postcommit", "review", "analysis"], answerDistance: ["square", "relation"], sourceCeiling: "Exact attack/defence relations only; multiple duties are not yet exploitable overload.", workflowCeiling: "Support may identify defender/targets on request; never recommend a move from this row.", fixtures: { positive: "one defender with two named duties", hardNegative: "same geometry with second co-defender retained", abstention: "none: total rules reading" }, availability: "local synchronous" }),
  p({ id: "rules.tactic.event.defender_removed@1", producer: "rules.tactic", grounding: "recorded_run", operands: ["move", "defender", "defenderRole", "target", "targetRole", "lostDuty"], abstention: [], consumers: ["support", "review", "bot", "inspector", "authoring"], timing: ["postcommit", "review", "analysis"], answerDistance: ["square", "relation", "concept"], sourceCeiling: "Names the captured defender and lost duty; not force, intent or value.", workflowCeiling: "Post-commit/Review fact; candidate adapters may compute it before bot choice without exposing the move.", fixtures: { positive: "captured defender exposes retained target", hardNegative: "captured piece had no retained duty", abstention: "none: total transition event" }, availability: "local synchronous" }),
  p({ id: "rules.tactic.event.defender_duty_relocated@1", producer: "rules.tactic", grounding: "recorded_run", operands: ["move", "defenderBefore", "defenderAfter", "target", "lostDuty"], abstention: [], consumers: ["support", "review", "bot", "inspector", "authoring"], timing: ["postcommit", "review", "analysis"], answerDistance: ["square", "relation"], sourceCeiling: "Relocation and duty loss only; not generic deflection.", workflowCeiling: "Quiet factual nudge or inspector row; semantic deflection uses its own event.", fixtures: { positive: "same defender relocates and loses target duty", hardNegative: "relocation preserves duty", abstention: "none: total recorded edge" }, availability: "local synchronous" }),
  p({ id: "derived.tactic.deflection_observed@1", producer: "derived.tactic", grounding: "recorded_run", operands: ["baitMove", "defenderBefore", "defenderAfter", "lostDuty", "targetCapture"], abstention: ["continuation_too_short"], consumers: ["support", "review", "inspector", "authoring"], timing: ["postcommit", "review", "offline"], answerDistance: ["square", "relation", "concept"], sourceCeiling: "Observed bait/check displacement plus retained-target capture; not forced.", workflowCeiling: "May name deflection after the sequence; pre-commit Support requires a separate candidate proof.", fixtures: { positive: "external-tag agreement positive", hardNegative: "relocation without later target capture", abstention: "record ends before consequence horizon" }, availability: "local after three recorded edges" }),
  p({ id: "derived.tactic.attraction_observed@1", producer: "derived.tactic", grounding: "recorded_run", operands: ["baitMove", "heavyPiece", "arrivalSquare", "checkOrCaptureConsequence"], abstention: ["continuation_too_short"], consumers: ["support", "review", "inspector", "authoring"], timing: ["postcommit", "review", "offline"], answerDistance: ["square", "relation", "concept"], sourceCeiling: "Observed king/queen/rook attraction with exact consequence; no intent/force.", workflowCeiling: "Named only after consequence is recorded; ordinary Support gets the relation, not a line.", fixtures: { positive: "99.9%-agreement source positive", hardNegative: "any-piece attraction rule firing on 19% controls", abstention: "record ends before consequence" }, availability: "local after bounded recorded sequence" }),
  p({ id: "derived.tactic.line_blocker_clearance_observed@1", producer: "derived.tactic", grounding: "recorded_run", operands: ["blocker", "slider", "ray", "target", "targetCapture"], abstention: ["continuation_too_short"], consumers: ["support", "review", "bot", "inspector", "authoring"], timing: ["postcommit", "review", "analysis"], answerDistance: ["square", "relation", "concept"], sourceCeiling: "Named blocker/ray/target and observed capture; not generic square clearance.", workflowCeiling: "Post-commit relation; candidate bot adapter may evaluate, Support never receives its resulting line.", fixtures: { positive: "sole ray blocker vacates then slider captures target", hardNegative: "vacation opens ray with no retained target consequence", abstention: "record ends before consequence" }, availability: "local after three recorded edges" }),
  p({ id: "derived.tactic.square_clearance_observed@1", producer: "derived.tactic", grounding: "recorded_run", operands: ["vacatedSquare", "vacatingPiece", "laterSlider", "laterMove"], abstention: ["continuation_too_short"], consumers: ["support", "review", "inspector", "authoring"], timing: ["postcommit", "review", "offline"], answerDistance: ["square", "relation", "concept"], sourceCeiling: "Exact vacated square later used/crossed by same-side slider; no force or value.", workflowCeiling: "May name clearance after the sequence; no pre-commit move reveal.", fixtures: { positive: "98.3%-agreement source positive", hardNegative: "unrelated later slider move", abstention: "record ends before slider consequence" }, availability: "local after bounded recorded sequence" }),
  p({ id: "derived.tactic.interference_observed@1", producer: "derived.tactic", grounding: "recorded_run", operands: ["interposingMove", "slider", "betweenSquare", "target", "brokenDuty", "targetCapture"], abstention: ["continuation_too_short"], consumers: ["support", "review", "bot", "inspector", "authoring"], timing: ["postcommit", "review", "analysis"], answerDistance: ["square", "relation", "concept"], sourceCeiling: "Exact broken slider duty and observed target consequence; conservative subset.", workflowCeiling: "Post-commit/Review name; candidate bot adapter may use the event without exposing its move.", fixtures: { positive: "interpose on exact between-set then target capture", hardNegative: "blocker appears on unrelated ray", abstention: "record ends before consequence" }, availability: "local after three recorded edges" }),
  p({ id: "derived.tactic.check_zwischenzug_observed@1", producer: "derived.tactic", grounding: "recorded_run", operands: ["expectedRecapture", "intermediateCheck", "reply", "retainedRecapture"], abstention: ["continuation_too_short"], consumers: ["support", "review", "inspector", "authoring"], timing: ["postcommit", "review", "offline"], answerDistance: ["square", "relation", "concept"], sourceCeiling: "Exact check-intermezzo subset with retained recapture; not all zwischenzugs.", workflowCeiling: "Review/post-commit only; do not disclose the intermediate move before commitment.", fixtures: { positive: "legal recapture interrupted by check then retained", hardNegative: "quiet delayed recapture", abstention: "record ends before recapture returns" }, availability: "local after four recorded edges" }),
  p({ id: "derived.tactic.overloaded_defender_response_conflict@1", producer: "derived.tactic", grounding: "position_rules", operands: ["candidate", "soleDefender", "capturedTarget", "retainedTargets", "legalRecaptures", "positiveCaptures"], abstention: ["no_legal_recapture"], consumers: ["support", "review", "bot", "inspector", "authoring"], timing: ["precommit_requested", "postcommit", "review", "analysis"], answerDistance: ["square", "relation", "concept"], sourceCeiling: "Same sole defender cannot recapture candidate without exposing named positive capture; not whole-position value.", workflowCeiling: "Support may show defender/targets on request but not candidate/move; bots receive full candidate identity.", fixtures: { positive: "sole two-duty defender with every recapture exposing target", hardNegative: "alternate defender or recapture preserving duty", abstention: "defender has no legal recapture" }, availability: "local bounded legal-recapture enumeration" }),
  p({ id: "derived.tactic.overload_exploitation_observed@1", producer: "derived.tactic", grounding: "recorded_run", operands: ["firstCapture", "defenderRecapture", "secondTargetCapture", "dutySet"], abstention: ["continuation_too_short"], consumers: ["support", "review", "inspector", "authoring"], timing: ["postcommit", "review", "offline"], answerDistance: ["square", "relation", "concept"], sourceCeiling: "Observed three-edge exploitation; not proof the recapture was forced.", workflowCeiling: "May name overload after the line; no pre-commit disclosure.", fixtures: { positive: "five imported exact observed sequences", hardNegative: "one-duty defender", abstention: "record ends before second capture" }, availability: "local after three recorded edges" }),
  p({ id: "rules.tactic.consequence.forced_mate_after_move@1", producer: "rules.tactic", grounding: "position_rules", operands: ["candidate", "attacker", "maxAttackerMoves", "proofStatus", "proofDigest", "rootReplies", "nodes"], abstention: ["budget_exhausted", "horizon_above_four"], consumers: ["support", "review", "bot", "inspector", "authoring"], timing: ["precommit_requested", "postcommit", "review", "analysis", "offline"], answerDistance: ["square", "relation", "concept", "candidate"], sourceCeiling: "Complete legal tree through four; proved/refuted/budget-exhausted, no engine substitution.", workflowCeiling: "Support may say there is a mating net or light relevant squares on request; candidate identity obeys stage ceiling.", fixtures: { positive: "mate-in-2/3/4 proved populations", hardNegative: "adjacent deeper tags at shallow horizon", abstention: "five-plus tree reaches 250k-node cap" }, availability: "bounded local/offline search; latency grows with horizon" }),
  p({ id: "rules.pawn.reading.promotion_geometry@1", producer: "rules.pawn", grounding: "position_rules", operands: ["pawn", "distance", "path", "blockers", "controls", "sideToMove", "passAvailability", "replyPersistence"], abstention: [], consumers: ["support", "review", "bot", "inspector", "authoring"], timing: ["precommit_requested", "postcommit", "review", "analysis"], answerDistance: ["square", "relation", "concept"], sourceCeiling: "Descriptive pawn geometry only; no winner/result outside a joined authority.", workflowCeiling: "Support may reveal path/distance by stage; no automatic winner language.", fixtures: { positive: "seventh-rank and breakthrough examples", hardNegative: "promotion available but removable after reply", abstention: "none: total per-pawn reading" }, availability: "local synchronous plus bounded one-reply flag" }),
  p({ id: "derived.pawn.promotion_race_geometry@1", producer: "derived.pawn", grounding: "position_rules", operands: ["pawns", "arrivalConvention", "ordering", "sideToMove"], abstention: ["blocked_or_capturable_path_outside_convention"], consumers: ["support", "review", "bot", "inspector", "authoring"], timing: ["precommit_requested", "postcommit", "review", "analysis"], answerDistance: ["square", "relation", "concept"], sourceCeiling: "Descriptive arrival ordering; explicitly not winning/losing/drawing.", workflowCeiling: "May say both pawns are racing and expose distances; outcome words require tablebase.", fixtures: { positive: "two-sided unblocked race", hardNegative: "geometry predicts loss where Syzygy says win", abstention: "path outside declared race convention" }, availability: "local synchronous" }),
  p({ id: "derived.pawn.promotion_race_tablebase@1", producer: "derived.pawn", grounding: "tablebase_exact", operands: ["raceGeometry", "category", "dtz", "preciseDtz", "provider"], abstention: ["outside_tablebase_domain", "provider_unavailable"], consumers: ["support", "review", "bot", "inspector", "authoring"], timing: ["postcommit", "review", "analysis", "offline"], answerDistance: ["relation", "concept", "evaluation"], sourceCeiling: "Exact Syzygy outcome joined to same participants in-domain.", workflowCeiling: "Support may disclose exact outcome only under its source/workflow ceiling; geometry survives provider absence.", fixtures: { positive: "recorded <=7-piece race", hardNegative: "same geometry with different tablebase category", abstention: "eight-piece position" }, availability: "provider-bound; exact domain <=7 pieces" }),
  p({ id: "theory.opening.current_endpoint@1", producer: "theory.opening", grounding: "citable_text", operands: ["transpositionKey", "eco", "name", "sourceRow"], abstention: ["no_named_endpoint"], consumers: ["support", "review", "theory", "bot", "inspector", "authoring"], timing: ["postcommit", "review", "analysis", "offline"], answerDistance: ["concept"], sourceCeiling: "Exact named endpoint only; absence is not out-of-book.", workflowCeiling: "Theory breadcrumb may name/link endpoint; no sticky label after catalogue exit.", fixtures: { positive: "two move orders same named endpoint", hardNegative: "unnamed prefix with many descendants", abstention: "position has no named endpoint" }, availability: "immutable local catalogue" }),
  p({ id: "theory.opening.catalogue_membership@1", producer: "theory.opening", grounding: "citable_text", operands: ["transpositionKey", "candidateRows", "isNamedEndpoint"], abstention: ["outside_catalogue"], consumers: ["review", "theory", "bot", "inspector", "authoring"], timing: ["review", "analysis", "offline"], answerDistance: ["concept"], sourceCeiling: "Membership/prefix fact; descendant names are not current identity.", workflowCeiling: "Inspector/theory applicability only; never choose a descendant opening for the learner.", fixtures: { positive: "catalogue prefix", hardNegative: "prefix with 2,023 descendants", abstention: "key absent from catalogue" }, availability: "immutable local catalogue" }),
  p({ id: "derived.opening.deepest_reached@1", producer: "derived.opening", grounding: "recorded_run", operands: ["endpoint", "ply", "transpositionKey", "history"], abstention: ["no_named_endpoint_reached"], consumers: ["review", "theory", "bot", "inspector"], timing: ["review", "analysis", "offline"], answerDistance: ["concept"], sourceCeiling: "Retrospective deepest named endpoint reached; never current applicability.", workflowCeiling: "Review/repertoire context only; excluded from live Support after catalogue exit.", fixtures: { positive: "game reaches then leaves endpoint", hardNegative: "sticky endpoint used as current identity", abstention: "game reaches no named endpoint" }, availability: "local history fold" }),
  p({ id: "derived.review.eval_delta@1", producer: "derived.review", grounding: "bounded_search", operands: ["beforeCp", "afterCp", "perspective", "engine", "version", "budget"], abstention: ["missing_endpoint", "mate_operand", "provider_unavailable"], consumers: ["review", "inspector"], timing: ["review", "analysis"], answerDistance: ["evaluation"], sourceCeiling: "cp→cp recorded difference only; no grade, significance or best move.", workflowCeiling: "Review/Analyze may show the labelled measurement; never live Support.", fixtures: { positive: "two typed cp points", hardNegative: "cp-to-mate transition", abstention: "one endpoint missing" }, availability: "optional post-game engine pass" }),
  p({ id: "derived.review.mate_transition@1", producer: "derived.review", grounding: "bounded_search", operands: ["before", "after", "side", "distance", "engine", "version", "budget"], abstention: ["missing_endpoint", "no_mate_operand", "provider_unavailable"], consumers: ["review", "inspector"], timing: ["review", "analysis"], answerDistance: ["relation", "evaluation"], sourceCeiling: "Mate appearance/disappearance/distance as typed engine reading; exact proof remains separate.", workflowCeiling: "Review/Analyze only; may join exact mate proof by node/candidate identity.", fixtures: { positive: "72/72 engine/exact-mate rows", hardNegative: "mate coerced to +/-1000 cp", abstention: "engine returns cp at finite budget" }, availability: "optional post-game engine pass" }),
]);

describe("D872 Wave-C producer-to-consumer closure", () => {
  it("requires every candidate projection to retain a complete C5 contract", () => {
    expect(new Set(ROWS.map((row) => row.id)).size).toBe(ROWS.length);
    for (const row of ROWS) {
      expect(row.id).toMatch(/@1$/u);
      expect(row.operands.length).toBeGreaterThan(0);
      expect(row.consumers.length).toBeGreaterThan(0);
      expect(row.timing.length).toBeGreaterThan(0);
      expect(row.answerDistance.length).toBeGreaterThan(0);
      expect(row.sourceCeiling.length).toBeGreaterThan(20);
      expect(row.workflowCeiling.length).toBeGreaterThan(20);
      expect(Object.values(row.fixtures).every((value) => value.length > 0)).toBe(true);
      expect(row.availability.length).toBeGreaterThan(0);
    }
  });

  it("prevents source and answer-distance leaks into ordinary pre-commit Support", () => {
    const precommit = ROWS.filter((row) => row.timing.includes("precommit_requested"));
    expect(precommit.every((row) => row.consumers.includes("support"))).toBe(true);
    expect(precommit.every((row) => row.grounding === "position_rules")).toBe(true);
    expect(precommit.every((row) => !row.answerDistance.includes("move") && !row.answerDistance.includes("line") && !row.answerDistance.includes("evaluation"))).toBe(true);
    expect(ROWS.filter((row) => row.grounding === "bounded_search" || row.grounding === "tablebase_exact")
      .every((row) => !row.timing.includes("precommit_requested"))).toBe(true);
  });

  it("writes the candidate handoff and leaves habits out until opportunity denominators exist", () => {
    const counts = new Map<Consumer, number>();
    for (const row of ROWS) for (const consumer of row.consumers) counts.set(consumer, (counts.get(consumer) ?? 0) + 1);
    const lines = [
      "# D872 Wave-C producer-to-consumer candidate matrix",
      "",
      "Research handoff only: projection names and eligibility are candidates for the collector/module RFCs. Every row retains literal operands, grounding, abstention, source/workflow ceilings, positive/hard-negative/abstention fixtures and availability in the executable source file.",
      "",
      `Rows: ${ROWS.length}. Candidate consumer reach: ${[...counts].map(([key, value]) => `${key} ${value}`).join("; ")}. Habit rows: 0 (intentionally held until opportunity denominators, sample floors and the longitudinal store exist).`,
      "",
      "| projection | grounding | timing | candidate consumers | answer distance | availability |",
      "|---|---|---|---|---|---|",
      ...ROWS.map((row) => `| \`${row.id}\` | ${row.grounding} | ${row.timing.join(", ")} | ${row.consumers.join(", ")} | ${row.answerDistance.join(", ")} | ${row.availability} |`),
      "",
      "Compiler invariant: a workflow receives `preset request ∩ session ceiling ∩ role ∩ source availability`; no row raises a preset's disclosure. Raw operands remain configurable in the inspector/authoring plane without becoming learner settings.",
      "",
    ];
    writeFileSync(OUTPUT, lines.join("\n"), "utf8");
    expect(counts.get("inspector")).toBe(ROWS.length);
    expect(ROWS.some((row) => row.consumers.includes("authoring"))).toBe(true);
    expect(ROWS.some((row) => (row.consumers as readonly string[]).includes("habit"))).toBe(false);
  });
});
