// rfc/verifiable-runtime-distribution.md §1/§8 — the post-image release set: digest-pinned Compose
// profiles, the release manifest (generated once, verified read-only), SHA256SUMS and the acyclic
// artifact graph that orders them.
import { existsSync, readFileSync, statSync } from "node:fs";
import { resolve } from "node:path";

import {
  canonicalReleaseManifest,
  isPrerelease,
  parseReleaseManifest,
  validateReleaseManifest,
} from "../../../packages/schema/src/release-manifest/index.ts";
import { DIGEST, sha256Digest, sha256Hex } from "./common.mjs";

export const RELEASE_MANIFEST_NAME = "release-manifest.json";
export const CHECKSUMS_NAME = "SHA256SUMS";
export const MOUNTED_MANIFEST_PATH = "/run/chess-tabiya/release-manifest.json";
export const PROVENANCE_PREDICATE = "https://slsa.dev/provenance/v1";
export const SBOM_PREDICATE = "https://spdx.dev/Document/v2.3";
export const COMPOSE_PROFILES = Object.freeze(["appliance", "hosted", "local"]);
const SUBJECT = /^[a-z0-9.-]+(?::[0-9]+)?\/[a-z0-9._/-]+@sha256:[0-9a-f]{64}$/u;

export function releaseFile(root, path) {
  const bytes = readFileSync(resolve(root, path));
  return { path, bytes: bytes.length, sha256: sha256Digest(bytes) };
}

// ---------------------------------------------------------------------------------------------
// Compose profiles. F12-A owns the final deployment-profile semantics; these three are the release
// projections of today's server/Maia topology with the §5 cgroup limits and no swap.

const PROFILE_SETTINGS = Object.freeze({
  local: { bind: "127.0.0.1", cookieSecure: "false", description: "single-machine use on this host only" },
  appliance: { bind: "0.0.0.0", cookieSecure: "false", description: "a trusted home/club network appliance without TLS" },
  hosted: { bind: "127.0.0.1", cookieSecure: "true", description: "behind an operator-managed TLS reverse proxy" },
});

export function renderCompose({ profile, serverSubject, maiaSubject = null, version }) {
  const settings = PROFILE_SETTINGS[profile];
  if (settings === undefined) throw new TypeError(`unknown Compose profile ${profile}`);
  if (!SUBJECT.test(serverSubject)) throw new TypeError("server image must be a digest-pinned OCI subject");
  if (maiaSubject !== null && !SUBJECT.test(maiaSubject)) throw new TypeError("Maia image must be a digest-pinned OCI subject");
  const engines = maiaSubject !== null;
  const lines = [
    `# Tabiya ${version} — Compose profile "${profile}": ${settings.description}.`,
    "# Generated by tools/release/release-set.mjs from the pushed image digests; never edit by hand.",
    "# Verify the release set (SHA256SUMS, signatures, attestations) before `docker compose up`.",
    "# Download release-manifest.json next to this file: the server verifies it at startup.",
    "name: chess-tabiya",
    "",
    "services:",
    "  server:",
    `    image: ${serverSubject}`,
    "    environment:",
    "      DATABASE_PATH: /data/chess-tabiya.sqlite",
    `      ENGINE_MODE: ${engines ? "${ENGINE_MODE:-maia}" : "mock"}`,
    ...(engines ? ["      MAIA_HOST: maia", '      MAIA_PORT: "7000"'] : []),
    '      PORT: "3000"',
    "      STOCKFISH_PATH: /usr/games/stockfish",
    `      TABIYA_COOKIE_SECURE: "${settings.cookieSecure}"`,
    `      TABIYA_RELEASE_MANIFEST: ${MOUNTED_MANIFEST_PATH}`,
    `      TABIYA_SERVER_IMAGE: ${serverSubject}`,
    `      TABIYA_DEPLOYMENT_TIER: ${engines ? "cpu" : "core"}`,
    "    ports:",
    `      - "${settings.bind}:\${TABIYA_PORT:-3000}:3000"`,
    "    volumes:",
    "      - tabiya-data:/data",
    `      - ./${RELEASE_MANIFEST_NAME}:${MOUNTED_MANIFEST_PATH}:ro`,
    "    mem_limit: 512m",
    "    memswap_limit: 512m",
    ...(engines ? [
      "    networks: [default, engines]",
      "    depends_on:",
      "      maia:",
      "        condition: service_healthy",
    ] : []),
    "    restart: unless-stopped",
  ];
  if (engines) {
    lines.push(
      "",
      "  maia:",
      `    image: ${maiaSubject}`,
      '    entrypoint: ["python", "/opt/chess-tabiya/maia-sidecar.py"]',
      "    environment:",
      "      MAIA_LISTEN_HOST: 0.0.0.0",
      '      MAIA_LISTEN_PORT: "7000"',
      "      MAIA_READY_FILE: /tmp/ready",
      "    healthcheck:",
      '      test: ["CMD", "python", "-c", "import os,sys; sys.exit(0 if os.path.exists(\'/tmp/ready\') else 1)"]',
      "      interval: 5s",
      "      timeout: 2s",
      "      start_period: 120s",
      "      retries: 24",
      "    mem_limit: 1536m",
      "    memswap_limit: 1536m",
      "    networks: [engines]",
      "    restart: unless-stopped",
    );
  }
  lines.push("", "volumes:", "  tabiya-data:");
  if (engines) lines.push("", "networks:", "  engines:", "    internal: true");
  return `${lines.join("\n")}\n`;
}

/** Every `image:` reference in a Compose text; tag-only references are returned as findings. */
export function composeImages(text) {
  const images = [...text.matchAll(/^\s*image:\s*(\S+)\s*$/gmu)].map((match) => match[1]);
  return {
    subjects: [...new Set(images.filter((image) => SUBJECT.test(image)))].sort(),
    tagOnly: images.filter((image) => !SUBJECT.test(image)),
  };
}

// ---------------------------------------------------------------------------------------------
// Manifest generation (once) and read-only verification.

export function signatureIdentity(repository, version) {
  return `${repository}/.github/workflows/release.yml@refs/tags/v${version}`;
}

/**
 * Builds the post-image manifest from already-produced release files. `images` maps role →
 * { subject, platforms: { "linux/amd64": digest, ... }, fossEligible }. The release directory must
 * already hold the source archive, NOTICE.txt, LICENSE, the per-platform SBOMs and Compose files.
 */
export function generateReleaseManifest({ dir, version, sourceRevision, createdAt, repository, images, resourceReceipts = [], contentBundle, fossPolicy, sourceArchive }) {
  const artifacts = Object.entries(images).map(([role, image]) => {
    const tier = { server: "core", "maia-cpu": "cpu", "maia-accelerated": "accelerated" }[role];
    const platforms = Object.keys(image.platforms).sort();
    return {
      role,
      tier,
      subject: image.subject,
      platforms,
      platformManifests: platforms.map((platform) => ({
        platform,
        digest: image.platforms[platform],
        sbom: releaseFile(dir, `sbom/${role}-${platform.replace("/", "-")}.spdx.json`),
      })),
      signatureIdentity: signatureIdentity(repository, version),
      provenancePredicate: PROVENANCE_PREDICATE,
      sbomPredicate: SBOM_PREDICATE,
      fossEligible: image.fossEligible,
    };
  }).sort((left, right) => left.role.localeCompare(right.role));
  const compose = COMPOSE_PROFILES.filter((profile) => existsSync(resolve(dir, `compose.${profile}.yaml`))).map((profile) => {
    const path = `compose.${profile}.yaml`;
    const { subjects, tagOnly } = composeImages(readFileSync(resolve(dir, path), "utf8"));
    if (tagOnly.length > 0) throw new TypeError(`${path} contains tag-only images: ${tagOnly.join(", ")}`);
    return { ...releaseFile(dir, path), profile, imageDigests: subjects };
  });
  const sbomFiles = artifacts.flatMap((artifact) => artifact.platformManifests.map((platform) => platform.sbom));
  const files = [releaseFile(dir, "LICENSE"), releaseFile(dir, "NOTICE.txt"), ...sbomFiles].sort((left, right) => left.path.localeCompare(right.path));
  const manifest = {
    format: "tabiya-release-manifest",
    formatVersion: 1,
    release: { version, sourceRevision, createdAt, repository, sourceArchive: releaseFile(dir, sourceArchive) },
    requiredArtifacts: artifacts.filter((artifact) => artifact.role !== "maia-accelerated"),
    optionalArtifacts: artifacts.filter((artifact) => artifact.role === "maia-accelerated"),
    compose,
    files,
    resourceReceipts: [...resourceReceipts].sort((left, right) => `${left.tier}|${left.platform}`.localeCompare(`${right.tier}|${right.platform}`)),
    contentBundle,
    fossPolicy,
  };
  const errors = validateReleaseManifest(manifest);
  if (errors.length > 0) throw new TypeError(`release manifest refused:\n- ${errors.join("\n- ")}`);
  return canonicalReleaseManifest(manifest);
}

/** SHA256SUMS over every release file except itself (the manifest included), sorted by path. */
export function renderChecksums(dir, paths) {
  const unique = [...new Set(paths)].filter((path) => path !== CHECKSUMS_NAME).sort();
  return unique.map((path) => `${sha256Hex(readFileSync(resolve(dir, path)))}  ${path}`).join("\n").concat("\n");
}

export function parseChecksums(text) {
  return text.trimEnd().split("\n").map((line) => {
    const match = /^([0-9a-f]{64}) {2}(\S+)$/u.exec(line);
    if (match === null) throw new TypeError(`invalid SHA256SUMS line: ${line}`);
    return { sha256: `sha256:${match[1]}`, path: match[2] };
  });
}

/**
 * Read-only verification of a downloaded release set: checksums, manifest schema/joins, every
 * listed file, Compose digests. Returns the parsed manifest or throws with every failure.
 */
export function verifyReleaseSet(dir) {
  const failures = [];
  const checksums = parseChecksums(readFileSync(resolve(dir, CHECKSUMS_NAME), "utf8"));
  if (checksums.some((entry) => entry.path === CHECKSUMS_NAME)) failures.push("SHA256SUMS lists itself");
  for (const entry of checksums) {
    const path = resolve(dir, entry.path);
    if (!existsSync(path) || !statSync(path).isFile()) failures.push(`missing ${entry.path}`);
    else if (sha256Digest(readFileSync(path)) !== entry.sha256) failures.push(`checksum mismatch: ${entry.path}`);
  }
  let manifest;
  try {
    manifest = parseReleaseManifest(readFileSync(resolve(dir, RELEASE_MANIFEST_NAME), "utf8"));
  } catch (error) {
    failures.push(error.message);
  }
  if (manifest !== undefined) {
    if (!checksums.some((entry) => entry.path === RELEASE_MANIFEST_NAME)) failures.push("SHA256SUMS does not cover the release manifest");
    const listed = [manifest.release.sourceArchive, ...manifest.files, ...manifest.compose];
    for (const file of listed) {
      const path = resolve(dir, file.path);
      if (!existsSync(path)) {
        failures.push(`manifest file missing: ${file.path}`);
        continue;
      }
      const bytes = readFileSync(path);
      if (bytes.length !== file.bytes || sha256Digest(bytes) !== file.sha256) failures.push(`manifest file changed: ${file.path}`);
      if (!checksums.some((entry) => entry.path === file.path && entry.sha256 === file.sha256)) failures.push(`SHA256SUMS does not cover ${file.path}`);
    }
    for (const compose of manifest.compose) {
      const { subjects, tagOnly } = composeImages(readFileSync(resolve(dir, compose.path), "utf8"));
      if (tagOnly.length > 0) failures.push(`${compose.path} has tag-only images`);
      if (subjects.join(",") !== compose.imageDigests.join(",")) failures.push(`${compose.path} images differ from the manifest`);
    }
  }
  if (failures.length > 0) throw new TypeError(`release set verification failed:\n- ${failures.join("\n- ")}`);
  return manifest;
}

export { isPrerelease };

// ---------------------------------------------------------------------------------------------
// §8 artifact graph: committed/pre-image bytes → image digest → SBOM/resource receipt → Compose
// digest → release manifest → checksum file → signatures/attestations.

export const RELEASE_GRAPH = Object.freeze([
  ["committed-source", "source-archive"],
  ["committed-source", "foss-policy"],
  ["committed-source", "runtime-content"],
  ["foss-policy", "notice"],
  ["committed-source", "notice"],
  ["notice", "build-metadata"],
  ["foss-policy", "build-metadata"],
  ["runtime-content", "build-metadata"],
  ["committed-source", "platform-image"],
  ["notice", "platform-image"],
  ["build-metadata", "platform-image"],
  ["runtime-content", "platform-image"],
  ["platform-image", "image-index"],
  ["platform-image", "sbom"],
  ["platform-image", "resource-receipt"],
  ["image-index", "compose"],
  ["image-index", "release-manifest"],
  ["sbom", "release-manifest"],
  ["resource-receipt", "release-manifest"],
  ["compose", "release-manifest"],
  ["source-archive", "release-manifest"],
  ["notice", "release-manifest"],
  ["release-manifest", "checksums"],
  ["compose", "checksums"],
  ["sbom", "checksums"],
  ["source-archive", "checksums"],
  ["image-index", "image-signature"],
  ["image-index", "provenance-attestation"],
  ["sbom", "sbom-attestation"],
  ["checksums", "release-attestation"],
]);

/** Kahn topological sort; throws on any cycle (including a self-edge). */
export function topologicalOrder(edges = RELEASE_GRAPH) {
  const nodes = new Set(edges.flat());
  const incoming = new Map([...nodes].map((node) => [node, 0]));
  for (const [from, to] of edges) {
    if (from === to) throw new TypeError(`release graph cycle: ${from} depends on itself`);
    incoming.set(to, incoming.get(to) + 1);
  }
  const ready = [...nodes].filter((node) => incoming.get(node) === 0).sort();
  const order = [];
  while (ready.length > 0) {
    const node = ready.shift();
    order.push(node);
    for (const [from, to] of edges) {
      if (from !== node) continue;
      incoming.set(to, incoming.get(to) - 1);
      if (incoming.get(to) === 0) ready.push(to);
    }
    ready.sort();
  }
  if (order.length !== nodes.size) throw new TypeError(`release graph cycle among: ${[...nodes].filter((node) => !order.includes(node)).join(", ")}`);
  return order;
}

export function requireDigestString(value) {
  if (!DIGEST.test(value)) throw new TypeError(`not a digest: ${value}`);
  return value;
}
