packages:
  - apps/*
  - packages/*

storeDir: .cache/pnpm-store
cacheDir: .cache/pnpm-cache
stateDir: .cache/pnpm-state
verifyStoreIntegrity: true
strictPeerDependencies: true
autoInstallPeers: false

allowBuilds:
  esbuild: true

onlyBuiltDependencies:
  - esbuild
