// rfc/pack-capability-contract.md §2.3, §2.7, §3.1 — the capability contract's build/check surface.
//
// Deliberately imports the evidence catalogue and the lifecycle by module path rather than through
// `@chess-tabiya/runtime`'s index: the registry's module-load invariants run over the generated
// declarations, and a generator that could only start when its own output is already consistent
// could never repair it.

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import {
  canonicalJson,
  capabilityKey,
  closedSchemaInventory,
  type CapabilityApplicability,
} from "@chess-tabiya/schema";
import type { GeneratedCapabilityDeclaration } from "@chess-tabiya/runtime";

import {
  BREADTH_CONVENTION_TEXT,
  PRIMARY_EVIDENCE_MANIFEST,
  SEMANTIC_CONVENTION_TEXT,
} from "../../../../packages/runtime/src/evidence-catalog.js";
import { CAPABILITY_LIFECYCLE } from "../../../../packages/runtime/src/capability/lifecycle.js";
import { buildCapabilityRegistry } from "../../../../packages/runtime/src/capability/registry.js";
import { GENERATED_CAPABILITY_DECLARATIONS } from "../../../../packages/runtime/src/capability/declarations.generated.js";
import { CAPABILITY_APPLICABILITY } from "../../../../packages/schema/src/capability/applicability.generated.js";

import {
  buildCapabilityContract,
  loadRegistryEntries,
  type ApplicabilityAuthority,
  type BuiltCapabilityContract,
} from "./declarations.js";
import { CapabilitySourceIndex } from "./source-image.js";

export const APPLICABILITY_AUTHORITY_PATH = "rfc/contracts/pack-capability-applicability-v1.json";
export const APPLICABILITY_GENERATED_PATH = "packages/schema/src/capability/applicability.generated.ts";
export const DECLARATIONS_GENERATED_PATH = "packages/runtime/src/capability/declarations.generated.ts";

export interface ContractBuildOptions {
  readonly root: string;
  readonly overrides?: Readonly<Record<string, string>>;
  readonly lifecycle?: typeof CAPABILITY_LIFECYCLE;
  readonly previous?: readonly GeneratedCapabilityDeclaration[];
  readonly authority?: ApplicabilityAuthority;
  /** Convention tables; defaults to the compiled catalogue (mutation fixtures, criterion 14). */
  readonly conventions?: Readonly<Record<string, Readonly<Record<string, string>>>>;
  readonly schema?: unknown;
}

export function readAuthority(root: string): ApplicabilityAuthority {
  return JSON.parse(readFileSync(resolve(root, APPLICABILITY_AUTHORITY_PATH), "utf8")) as ApplicabilityAuthority;
}

export function buildContract(options: ContractBuildOptions): BuiltCapabilityContract & { readonly index: CapabilitySourceIndex } {
  const root = resolve(options.root);
  const index = new CapabilitySourceIndex({ root, ...(options.overrides === undefined ? {} : { overrides: options.overrides }) });
  const schema = options.schema ?? JSON.parse(readFileSync(resolve(root, "schemas/drill_pack.schema.json"), "utf8")) as unknown;
  const built = buildCapabilityContract({
    schema,
    authority: options.authority ?? readAuthority(root),
    lifecycle: options.lifecycle ?? CAPABILITY_LIFECYCLE,
    manifest: PRIMARY_EVIDENCE_MANIFEST,
    conventions: options.conventions ?? { BREADTH_CONVENTION_TEXT, SEMANTIC_CONVENTION_TEXT },
    shapes: loadRegistryEntries(root, "content/shapes"),
    principles: loadRegistryEntries(root, "content/principles"),
    previous: options.previous ?? GENERATED_CAPABILITY_DECLARATIONS,
  });
  buildCapabilityRegistry(built.declarations, options.lifecycle ?? CAPABILITY_LIFECYCLE);
  return Object.freeze({ ...built, index });
}

export function renderApplicability(rows: readonly CapabilityApplicability[], authority: ApplicabilityAuthority): string {
  return [
    "// GENERATED by `make capability-applicability` from rfc/contracts/pack-capability-applicability-v1.json",
    "// and packages/runtime/src/capability/lifecycle.ts; do not edit. `make capability-applicability-check`",
    "// compares without writing. The author artifact is the authority; this image must expand to its digests.",
    'import type { CapabilityApplicability } from "./requirements.js";',
    "",
    "export const CAPABILITY_APPLICABILITY_AUTHORITY = Object.freeze({",
    `  artifact: ${JSON.stringify(authority.artifact)},`,
    `  schemaSha256: ${JSON.stringify(authority.schema.sha256)},`,
    `  inventorySha256: ${JSON.stringify(authority.closedVocabulary.inventorySha256)},`,
    `  expandedMappingSha256: ${JSON.stringify(authority.closedVocabulary.expandedMappingSha256)},`,
    `  expandedAuthoritySha256: ${JSON.stringify(authority.expandedAuthoritySha256)},`,
    "} as const);",
    "",
    `export const CAPABILITY_METADATA_EXCLUSIONS: readonly string[] = Object.freeze(${JSON.stringify(authority.metadataExclusions)});`,
    `export const CAPABILITY_METADATA_INSTANCE_EXCLUSIONS: readonly string[] = Object.freeze(["/requires"]);`,
    "",
    "// One row per line inside a JSON string: parsed once at load, and cheap for the type checker.",
    "export const CAPABILITY_APPLICABILITY: readonly CapabilityApplicability[] = Object.freeze(JSON.parse(String.raw`[",
    ...rows.map((row, index) => `${JSON.stringify(row).replaceAll("`", "\\u0060").replaceAll("${", "$\\u007b")}${index === rows.length - 1 ? "" : ","}`),
    "]`) as CapabilityApplicability[]);",
    "",
  ].join("\n");
}

export function renderDeclarations(rows: readonly GeneratedCapabilityDeclaration[]): string {
  return [
    "// GENERATED by `make capability-declarations`; do not edit. Compatibility uses explicit id/version.",
    "// Released declaration records remain immutable; source-only changes do not create pack migrations.",
    'import type { GeneratedCapabilityDeclaration } from "./registry.js";',
    "",
    "// One declaration per line inside a JSON string: parsed once at load, and cheap for the type checker.",
    "export const GENERATED_CAPABILITY_DECLARATIONS: readonly GeneratedCapabilityDeclaration[] = Object.freeze(JSON.parse(String.raw`[",
    ...rows.map((row, index) => `${JSON.stringify(row).replaceAll("`", "\\u0060").replaceAll("${", "$\\u007b")}${index === rows.length - 1 ? "" : ","}`),
    "]`) as GeneratedCapabilityDeclaration[]);",
    "",
  ].join("\n");
}

export interface DigestFinding {
  readonly key: string;
  readonly kind: "digest_mismatch" | "added" | "removed" | "changed";
}

/** Compares recomputed declarations against the stored ones. */
export function compareDeclarations(stored: readonly GeneratedCapabilityDeclaration[], built: readonly GeneratedCapabilityDeclaration[]): readonly DigestFinding[] {
  const findings: DigestFinding[] = [];
  const before = new Map(stored.map((row) => [capabilityKey(row.id), row]));
  const after = new Map(built.map((row) => [capabilityKey(row.id), row]));
  for (const [key, row] of after) {
    const previous = before.get(key);
    if (previous === undefined) findings.push({ key, kind: "added" });
    else if (previous.semanticsDigest !== row.semanticsDigest) findings.push({ key, kind: "digest_mismatch" });
    else if (canonicalJson(previous) !== canonicalJson(row)) findings.push({ key, kind: "changed" });
  }
  for (const key of before.keys()) if (!after.has(key)) findings.push({ key, kind: "removed" });
  return findings.sort((left, right) => (left.key < right.key ? -1 : 1));
}

/** A generator may add explicit versions, never rewrite or remove a released declaration. */
export function assertDeclarationUpdate(stored: readonly GeneratedCapabilityDeclaration[], built: readonly GeneratedCapabilityDeclaration[]): void {
  const rewrites = compareDeclarations(stored, built).filter((finding) => finding.kind !== "added");
  if (rewrites.length > 0) throw new TypeError(`CAPABILITY_DECLARATION_REWRITTEN: ${rewrites.map((finding) => finding.key).join(", ")}; retain the declaration and add its explicit versioned successor`);
}

export type CensusCode =
  | "SCHEMA_CAPABILITY_UNANNOTATED"
  | "CAPABILITY_INTERPRETER_ORPHAN"
  | "CAPABILITY_NAMED_ROOT_MISSING"
  | "CAPABILITY_DECLARATION_EXTRA"
  | "CAPABILITY_IDENTITY_MISMATCH";

export interface CensusFinding { readonly code: CensusCode; readonly detail: string }

/**
 * §3.1 — four independent authorities; declarations must set-equal their union.
 *   1. the schema's closed members set-equal the author inventory, and the public ids are the author's;
 *   2. every exhaustive switch over a census type is a declared interpreter site of its family;
 *   3. every named evaluator/constant/interpreter site resolves exactly once;
 *   4. the declaration set has no row outside the four roots and the authored lifecycle subjects.
 */
export function runCensus(input: {
  readonly schema: unknown;
  readonly authority: ApplicabilityAuthority;
  readonly index: CapabilitySourceIndex;
  readonly declarations: readonly GeneratedCapabilityDeclaration[];
  readonly applicability: readonly CapabilityApplicability[];
  readonly expectedSubjects: ReadonlySet<string>;
}): readonly CensusFinding[] {
  const findings: CensusFinding[] = [];
  const inventory = closedSchemaInventory(input.schema, input.authority.metadataExclusions);
  const authored = new Set(input.authority.closedVocabulary.sourceInventory.map((row) => canonicalJson(row)));
  const live = new Set(inventory.rows.map((row) => canonicalJson(row)));
  for (const row of live) if (!authored.has(row)) findings.push({ code: "SCHEMA_CAPABILITY_UNANNOTATED", detail: `schema member ${row} has no author inventory row` });
  for (const row of authored) if (!live.has(row)) findings.push({ code: "SCHEMA_CAPABILITY_UNANNOTATED", detail: `author inventory row ${row} is not a live schema member` });
  const declaredSites = new Map(input.authority.meaningAuthority.interpreterRoots.map((family) => [family.subject, new Set([...family.sites, ...family.admissionSites])]));
  const interpreters = [
    ["exhaustively interprets", input.index.exhaustiveSites(input.authority.meaningAuthority.censusTypes)],
    ["branches on two or more members of", input.index.armSites(input.authority.meaningAuthority.censusTypes)],
  ] as const;
  const orphaned = new Set<string>();
  for (const [how, found] of interpreters) {
    for (const [typeName, sites] of found) {
      for (const site of sites) {
        if (declaredSites.get(typeName)?.has(site) || orphaned.has(`${typeName}|${site}`)) continue;
        orphaned.add(`${typeName}|${site}`);
        findings.push({ code: "CAPABILITY_INTERPRETER_ORPHAN", detail: `${site} ${how} ${typeName} and is not a declared interpreter site` });
      }
    }
  }
  const named = [
    ...input.authority.always.flatMap((row) => [...row.sites, ...row.dependencies]),
    ...input.authority.meaningAuthority.constantRoots.flatMap((row) => row.sites),
    ...input.authority.meaningAuthority.interpreterRoots.flatMap((row) => [...row.sites, ...row.admissionSites]),
    ...input.authority.lifecycleSubjects.flatMap((row) => row.versions.flatMap((version) => version.sites)),
  ];
  for (const site of new Set(named)) if (input.index.siteCount(site) !== 1) findings.push({ code: "CAPABILITY_NAMED_ROOT_MISSING", detail: `${site} resolves to ${input.index.siteCount(site)} declarations` });
  const bySubject = new Map(input.declarations.map((row) => [row.subjectId, row]));
  for (const subject of bySubject.keys()) if (!input.expectedSubjects.has(subject)) findings.push({ code: "CAPABILITY_DECLARATION_EXTRA", detail: `${subject} is declared outside every census root` });
  for (const subject of input.expectedSubjects) if (!bySubject.has(subject)) findings.push({ code: "CAPABILITY_NAMED_ROOT_MISSING", detail: `${subject} is a census root with no declaration` });
  for (const row of input.applicability) {
    if (row.selector.kind !== "schema_member") continue;
    const declaration = bySubject.get(row.capability!.id);
    const source = declaration?.sources.find((candidate) => candidate.kind === "schema_member");
    if (source === undefined || canonicalJson(source.kind === "schema_member" ? source.sourceIdentity : null) !== canonicalJson(row.selector.sourceIdentity)) {
      findings.push({ code: "CAPABILITY_IDENTITY_MISMATCH", detail: `${row.capability!.id} is mapped from ${canonicalJson(row.selector.sourceIdentity)} but declared from ${source === undefined ? "nothing" : canonicalJson(source)}` });
    }
  }
  return findings;
}

/** The subject ids the four census roots plus the authored lifecycle subjects require. */
export function censusSubjects(root: string, authority: ApplicabilityAuthority, applicability: readonly CapabilityApplicability[]): ReadonlySet<string> {
  const out = new Set<string>();
  for (const row of applicability) if (row.capability !== undefined) out.add(row.capability.id);
  for (const row of authority.meaningAuthority.constantRoots) out.add(row.capability);
  for (const id of Object.values(authority.meaningAuthority.conventions.ids)) out.add(id);
  for (const projection of PRIMARY_EVIDENCE_MANIFEST.projections) out.add(projection.id);
  for (const row of authority.lifecycleSubjects) out.add(row.subjectId);
  for (const entry of loadRegistryEntries(root, "content/shapes")) out.add(`shape.${entry.id}`);
  for (const entry of loadRegistryEntries(root, "content/principles")) out.add(`principle.${entry.id}`);
  return out;
}

function main(argv: readonly string[]): number {
  const [command, ...flags] = argv;
  const root = resolve(process.env.TABIYA_ROOT ?? process.cwd());
  if (!existsSync(resolve(root, APPLICABILITY_AUTHORITY_PATH))) throw new Error(`run from the repository root (${APPLICABILITY_AUTHORITY_PATH} not found)`);
  const write = flags.includes("--write");
  const authority = readAuthority(root);
  if (command === "applicability") {
    const built = buildContract({ root });
    const text = renderApplicability(built.applicability, authority);
    const path = resolve(root, APPLICABILITY_GENERATED_PATH);
    if (write) { writeFileSync(path, text); console.log(`capability-applicability: wrote ${built.applicability.length} rows`); return 0; }
    if (readFileSync(path, "utf8") !== text) { console.error("capability-applicability-check: the generated image is stale; run make capability-applicability"); return 1; }
    console.log(`capability-applicability-check: ${built.applicability.length} rows match the author authority`);
    return 0;
  }
  if (command === "declarations" || command === "check") {
    const built = buildContract({ root });
    const findings = compareDeclarations(GENERATED_CAPABILITY_DECLARATIONS, built.declarations);
    const applicabilityText = renderApplicability(built.applicability, authority);
    const applicabilityStale = readFileSync(resolve(root, APPLICABILITY_GENERATED_PATH), "utf8") !== applicabilityText;
    if (command === "declarations" && write) {
      assertDeclarationUpdate(GENERATED_CAPABILITY_DECLARATIONS, built.declarations);
      writeFileSync(resolve(root, DECLARATIONS_GENERATED_PATH), renderDeclarations(built.declarations));
      writeFileSync(resolve(root, APPLICABILITY_GENERATED_PATH), applicabilityText);
      console.log(`capability-declarations: wrote ${built.declarations.length} declarations (${findings.length} changed)`);
      return 0;
    }
    // §2.1a / criterion 5: no suffixed version literal becomes capability authority.
    const literals = built.index.capabilityLiteralViolations();
    for (const violation of literals) console.error(`CAPABILITY_VERSION_LITERAL: ${violation} — construct a structured CapabilityId; old wire bytes go through legacyCapabilityFixture/parseLegacyCapability`);
    if (literals.length > 0) return 1;
    for (const finding of findings) console.error(`${finding.kind === "digest_mismatch" ? "CAPABILITY_DIGEST_MISMATCH" : `CAPABILITY_DECLARATION_${finding.kind.toUpperCase()}`}: ${finding.key}`);
    if (applicabilityStale) console.error("capability-check: the applicability image is stale; run make capability-applicability");
    if (findings.length > 0 || applicabilityStale) {
      console.error("capability-check: released declarations cannot be rewritten. Retain the old contract and add an explicit versioned successor for a deliberate public behavior change.");
      return 1;
    }
    console.log(`capability-check: ${built.declarations.length} explicit versioned declarations match; source hashes do not determine compatibility`);
    return 0;
  }
  if (command === "census") {
    const built = buildContract({ root });
    const schema = JSON.parse(readFileSync(resolve(root, "schemas/drill_pack.schema.json"), "utf8")) as unknown;
    const findings = runCensus({ schema, authority, index: built.index, declarations: built.declarations, applicability: built.applicability, expectedSubjects: censusSubjects(root, authority, built.applicability) });
    for (const finding of findings) console.error(`${finding.code}: ${finding.detail}`);
    if (findings.length > 0) return 1;
    const counts = new Map<string, number>();
    for (const row of built.declarations) counts.set(row.subject, (counts.get(row.subject) ?? 0) + 1);
    console.log(`capability-census: ${built.declarations.length} declarations · ${[...counts].sort().map(([subject, count]) => `${subject} ${count}`).join(" · ")}`);
    return 0;
  }
  if (command === "site-check") {
    const built = buildContract({ root });
    const failures: string[] = [];
    const named = new Set([
      ...authority.always.flatMap((row) => [...row.sites, ...row.dependencies]),
      ...authority.meaningAuthority.constantRoots.flatMap((row) => row.sites),
      ...authority.meaningAuthority.interpreterRoots.flatMap((row) => [...row.sites, ...row.admissionSites]),
    ]);
    for (const site of named) {
      if (built.index.siteCount(site) !== 1) { failures.push(`${site} does not resolve exactly once`); continue; }
      if (!built.index.hasProductionReader(site)) failures.push(`${site} has no production reader`);
    }
    for (const failure of failures) console.error(`CAPABILITY_NAMED_ROOT_MISSING: ${failure}`);
    if (failures.length > 0) return 1;
    console.log(`capability-site-check: ${named.size} named sites resolve once and have a production reader`);
    return 0;
  }
  console.error("usage: contract.js applicability|declarations|check|census|site-check [--write]");
  return 2;
}

const invoked = process.argv[1] !== undefined && /capability-contract\.js$/u.test(process.argv[1]);
if (invoked) process.exitCode = main(process.argv.slice(2));
