import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

type Entry = string | { readonly id: string; readonly state: "blocking" | "resolved" | "accepted"; readonly statement: string; readonly clearedBy?: string; readonly accepted?: { readonly kind: string; readonly ruling: string; readonly rulingRef: string } };

function files(root: string): readonly string[] {
  if (root === "content/candidates") return readdirSync(root, { withFileTypes: true }).filter((entry) => entry.isDirectory()).map((entry) => resolve(root, entry.name, "pack.json")).filter((file) => { try { readFileSync(file); return true; } catch { return false; } }).sort();
  return readdirSync(root, { withFileTypes: true }).filter((entry) => entry.isFile() && entry.name.endsWith(".json") && !/\.(?:evidence|graduation|job|sources)\.json$/u.test(entry.name)).map((entry) => resolve(root, entry.name)).sort();
}

export interface GraduationReport { readonly text: string; readonly acceptedPage: string; readonly legacy: number; readonly graduable: readonly string[]; }

export function graduationReport(roots: readonly string[] = ["content/drafts", "content/candidates", "content/packs"]): GraduationReport {
  const accepted: Array<{ packId: string; entry: Exclude<Entry, string> }> = [];
  const graduable: string[] = [];
  let legacy = 0;
  const sections: string[] = [];
  for (const root of roots) {
    const documents = files(root).map((file) => ({ file, document: JSON.parse(readFileSync(file, "utf8")) as { id: string; provenance?: { graduationBlockers?: Entry[] } } }));
    const counts = { blocking: 0, resolved: 0, accepted: 0, legacy: 0 };
    const documentLines: string[] = [];
    for (const { file, document } of documents) {
      const entries = document.provenance?.graduationBlockers ?? [];
      const blocking = entries.filter((entry) => typeof entry === "string" || entry.state === "blocking");
      if (root !== "content/candidates" && !file.endsWith(".browser.json") && blocking.length === 0) graduable.push(document.id);
      for (const entry of entries) {
        if (typeof entry === "string") { counts.legacy += 1; legacy += 1; continue; }
        counts[entry.state] += 1;
        if (entry.state === "accepted") accepted.push({ packId: document.id, entry });
      }
      const stateCounts = {
        blocking: blocking.length,
        resolved: entries.filter((entry) => typeof entry !== "string" && entry.state === "resolved").length,
        accepted: entries.filter((entry) => typeof entry !== "string" && entry.state === "accepted").length,
      };
      documentLines.push(`- **${document.id}** — blocking ${stateCounts.blocking}; resolved ${stateCounts.resolved}; accepted ${stateCounts.accepted}`);
      for (const entry of blocking) {
        if (typeof entry === "string") documentLines.push(`  - **legacy** — ${entry}`);
        else documentLines.push(`  - **${entry.id}** — ${entry.statement}; clears via ${entry.clearedBy ?? "(unspecified)"}`);
      }
    }
    sections.push(`## ${root}\n\ndocuments: ${documents.length}; legacy: ${counts.legacy}; blocking: ${counts.blocking}; resolved: ${counts.resolved}; accepted: ${counts.accepted}\n\n${documentLines.join("\n") || "(none)"}`);
  }
  const acceptedLines: string[] = [];
  for (const kind of [...new Set(accepted.map(({ entry }) => entry.accepted!.kind))].sort()) {
    acceptedLines.push(`## ${kind}`, "");
    for (const { packId, entry } of accepted.filter((row) => row.entry.accepted!.kind === kind).sort((a,b) => a.packId.localeCompare(b.packId) || a.entry.id.localeCompare(b.entry.id))) {
      acceptedLines.push(`- **${packId}/${entry.id}** — ${entry.statement}\n  Ruling: ${entry.accepted!.ruling} ([source](${entry.accepted!.rulingRef}))`);
    }
    acceptedLines.push("");
  }
  const page = ["# Accepted graduation conditions", "", "Generated by `make graduation-report`; edit the pack records, not this page.", "", ...acceptedLines].join("\n");
  return Object.freeze({ text: [...sections, `## Graduable drafts and packs\n\n${graduable.sort().join("\n") || "(none)"}`, ""].join("\n\n"), acceptedPage: page, legacy, graduable: Object.freeze(graduable) });
}

export function writeAcceptedConditions(path = "content/accepted-conditions.md"): GraduationReport {
  const report = graduationReport();
  writeFileSync(path, report.acceptedPage);
  return report;
}

if (/graduation-report\.(?:js|ts)$/u.test(process.argv[1] ?? "")) {
  const report = writeAcceptedConditions();
  process.stdout.write(`${report.text}\n`);
  if (report.legacy > 0) process.exitCode = 2;
}
