// GENERATED by tools/generate-candidate-packet-projections.mjs from PRIMARY_EVIDENCE_MANIFEST.
// Do not edit by hand: `node tools/generate-candidate-packet-projections.mjs --check` fails on drift.
// rfc/shared-candidate-evidence-packet.md §3.1/§5.3: the literal collector-output vocabulary and
// the abstention reasons the packet row may carry. A closure, not a claim that all members fire.

export const CANDIDATE_COLLECTOR_PROJECTION_KEYS = Object.freeze({
  "event.structural": Object.freeze([
    "rules.structural.event.backward_pawn@1",
    "rules.structural.event.doubled_pawn@1",
    "rules.structural.event.half_open_file@1",
    "rules.structural.event.isolated_pawn@1",
    "rules.structural.event.king_opposition@1",
    "rules.structural.event.king_zone@1",
    "rules.structural.event.line_blockers@1",
    "rules.structural.event.open_file@1",
    "rules.structural.event.passed_pawn@1",
    "rules.structural.event.piece_count@1",
    "rules.structural.event.direct_attack_count@1",
  ] as const),
  "event.pawn_island": Object.freeze([
    "rules.structural.event.pawn_islands@1",
  ] as const),
  "event.transition": Object.freeze([
    "rules.transition.event.occupied_attack@1",
    "rules.transition.event.occupied_defence@1",
    "rules.transition.event.slider_ray@1",
    "rules.transition.event.piece_escape@1",
    "rules.transition.event.defended_duty@1",
    "rules.transition.event.castled@1",
    "rules.transition.event.clock_reset@1",
    "rules.transition.event.last_of_role@1",
    "rules.transition.event.pawn_contact@1",
    "rules.transition.event.checkmate@1",
    "rules.transition.event.promotion@1",
    "rules.transition.event.capture@1",
    "rules.transition.event.developed@1",
  ] as const),
  "event.tactical": Object.freeze([
    "rules.tactic.event.double_attack@1",
    "rules.tactic.consequence.reply_breadth@1",
    "rules.tactic.event.check@1",
  ] as const),
  "event.loose_piece": Object.freeze([
    "rules.tactic.event.loose_piece@1",
  ] as const),
  "event.castling": Object.freeze([
    "rules.castling.event.rights_lost@1",
  ] as const),
  "event.exchange": Object.freeze([
    "derived.exchange.capture_class@1",
    "derived.exchange.trade_completed@1",
  ] as const),
  "event.discovered": Object.freeze([
    "derived.tactic.discovered_executed@1",
  ] as const),
  "event.breadth": Object.freeze([
    "rules.square.event.control@1",
    "rules.mobility.event.piece_destinations@1",
    "rules.pawn.event.dynamics@1",
    "derived.pawn.event.transitions@1",
    "derived.tactic.defender_exposure@1",
    "derived.material.event.role_asymmetry@1",
    "rules.king.event.zone_state@1",
    "derived.king.captured_zone_defender@1",
    "derived.activity.event.open_file_occupancy@1",
  ] as const),
  "event.duty": Object.freeze([
    "rules.tactic.event.defender_removed@1",
    "rules.tactic.event.defender_duty_relocated@1",
  ] as const),
  "reading.child": Object.freeze([
    "derived.material.reading.role_signature@1",
    "derived.tactic.promotion_pressure@1",
    "rules.castling.reading.legality@1",
    "rules.castling.reading.rights@1",
    "rules.king.reading.zone_state@1",
    "rules.mobility.reading.piece_destinations@1",
    "rules.pawn.reading.candidate_majority@1",
    "rules.pawn.reading.contacts@1",
    "rules.phase.development@1",
    "rules.square.reading.control@1",
    "rules.structural.reading.pawn_connectivity@1",
    "rules.structural.reading.space@1",
    "rules.tactic.consequence.mate_in_one@1",
    "rules.tactic.consequence.threat@1",
    "rules.tactic.reading.back_rank@1",
    "rules.tactic.reading.discovered_latency@1",
    "rules.tactic.reading.loose_piece@1",
    "rules.tactic.reading.ray_classification@1",
    "rules.tactic.reading.rook_on_seventh@1",
    "rules.tactic.reading.trapped_piece@1",
  ] as const),
  "reading.legal_exchange": Object.freeze([
    "rules.exchange.predicate.legal_exchange@1",
  ] as const),
  "reading.fork_survival": Object.freeze([
    "derived.tactic.fork_survives_reply@1",
  ] as const),
} as const);

export const CANDIDATE_PACKET_ABSTENTION_REASONS = Object.freeze({
  "rules.tactic.event.loose_piece@1": Object.freeze([
    "invalid_turn_clone",
  ] as const),
} as const);
