/**
 * The compiled semantic-convention registry (rfc/semantic-convention-provenance.md §1) and its
 * shared-resource register source (rfc/semantic-convention-register.md).
 *
 * `CONVENTION_DECLARATIONS` is the one literal runtime authority for every declared convention a
 * projection may depend on. Its prefix is generated byte-for-byte from the reviewed source-recovery
 * artifact `planning/semantic-convention-provenance/initial-declarations.json` by
 * `tools/generate-initial-convention-declarations.mjs` (`make semantic-convention-source-check`);
 * later declarations are authored directly beneath it. Each landed `id@version` has exactly one
 * append-only row in `evidence-convention-history.jsonl` (`make semantic-convention-history-check`).
 *
 * `SEMANTIC_CONVENTION_MEMBERS` is the literal string tuple the shared-resource catalogue reads
 * (`rfc/shared-resource-registers.json`, `string_tuple` reader). One member per declaration, in the
 * register's member grammar: `space@1` is `space_v1`, `defence-duty@1` is `defence_duty_v1`.
 * `evidence-conventions.test.ts` proves the tuple and the declarations are one set.
 *
 * A convention is a *definition*, not grounding: it never promotes a projection's grounding,
 * exactness or confidence, and it is never a learner-facing setting.
 */
import { evidenceDigest } from "./evidence-contract.js";

export interface ConventionRef {
  readonly id: string;
  readonly version: number;
}

export type ConventionAuthority =
  | Readonly<{ kind: "position_rules"; implementation: string }>
  | Readonly<{ kind: "landed_contract"; witnesses: readonly string[]; snapshotRef: string }>
  | Readonly<{ kind: "published_source"; citation: string; licence: string }>
  | Readonly<{ kind: "product_rule"; rulingRef: string }>
  | Readonly<{ kind: "measured_record"; recordRef: string }>;

export type ConventionDisclosure =
  | Readonly<{ kind: "definition_and_limitations" }>
  | Readonly<{ kind: "reviewed_text"; summary: string; detail: string }>;

export interface ConventionDeclaration {
  readonly ref: ConventionRef;
  readonly definition: string;
  readonly limitations: readonly string[];
  readonly authority: readonly ConventionAuthority[];
  readonly disclosure: ConventionDisclosure;
}

export interface CompiledConventionRegistry {
  /** Ordered by `(id, version)`; frozen. */
  readonly declarations: readonly ConventionDeclaration[];
  /** `sha256:<hex>` over every semantic field, independent of declaration order or file path. */
  readonly digest: string;
}

/** The register's member tuple. Literal and sorted; checked set-equal to the declarations. */
export const SEMANTIC_CONVENTION_MEMBERS = [
  "back_rank_susceptible_v1",
  "backward_pawn_legacy_v1",
  "candidate_feature_vector_v1",
  "candidate_majority_v1",
  "chessops_king_takes_rook_v1",
  "defence_duty_v1",
  "development_v1",
  "discovered_latency_v1",
  "double_attack_v1",
  "endgame_material_census_v1",
  "evidence_reference_resolution_v1",
  "fork_survival_v1",
  "grade_convention_v1",
  "king_landing_square_v1",
  "king_opposition_blocker_blind_v1",
  "king_shelter_v1",
  "king_zone_v1",
  "legal_exchange_v1",
  "local_non_losing_v1",
  "loose_piece_v1",
  "lucena_bridge_method_v1",
  "lucena_setup_v1",
  "mate_proof_v1",
  "material_role_signature_v1",
  "maximal_pawn_reach_v1",
  "mover_turn_ep_cleared_v1",
  "named_structure_catalogue_v1",
  "observed_window_v1",
  "opening_deepest_reached_v1",
  "overload_conflict_v1",
  "pawn_relations_v1",
  "phase_bands_v1",
  "philidor_third_rank_method_v1",
  "philidor_third_rank_setup_v1",
  "pressure_line_v1",
  "race_arrival_v1",
  "ray_classification_v1",
  "space_v1",
  "square_control_v1",
  "standard_uci_king_destination_v1",
  "story_last_level_v1",
  "story_rank_v1",
  "story_title_v1",
  "threat_v1",
  "trade_completed_v1",
  "trapped_v1",
  "vancura_method_v1",
  "vancura_setup_v1",
] as const;

const WIKIPEDIA_LICENCE = "CC BY-SA 4.0 (short verbatim quotation with attribution)";
const QUOTATION_LICENCE = "short verbatim quotation with attribution";
const EVA_SNAPSHOT = "cd2fdfb7";

export const CONVENTION_DECLARATIONS: readonly ConventionDeclaration[] = deepFreeze<ConventionDeclaration[]>([
  // BEGIN GENERATED initial declarations: node tools/generate-initial-convention-declarations.mjs (do not edit)
  {
    ref: { id: "back_rank_susceptible", version: 1 },
    definition: "The king stands on its back rank, every non-back-rank king escape is blocked by an own piece or attacked, and an enemy rook or queen is already on that rank or has a file path to it containing no pawn of either color. Non-pawn path blockers do not suppress the state.",
    limitations: ["Susceptibility is not mate, a move grade or inferred intent. Rank or diagonal approaches and whether an entry square is defended are outside this convention; exact mate-in-one is separate."],
    authority: [{ kind: "landed_contract", witnesses: ["rules.tactic.reading.back_rank@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "backward-pawn-legacy", version: 1 },
    definition: "A pawn on the named file is backward when no same-color pawn on an adjacent file is on its rank or behind it from that color's perspective, its one-step stop square is on the board, and an enemy pawn attacks that stop square. Occupancy and move legality of the stop square are not checked.",
    limitations: ["This is the shipped blocker-blind legacy predicate. State and signed before/after relations carry no learner valence, relevance or importance."],
    authority: [{ kind: "landed_contract", witnesses: ["packages/runtime/src/structure.ts#matchesStructuralFeature", "rules.structural.predicate.backward_pawn@1", "rules.structural.reading.backward_pawn@1", "rules.structural.event.backward_pawn@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "candidate-feature-vector", version: 1 },
    definition: "A typed record of one fixed-bound engine evaluation and the literal registered tactical and breadth collector results for each legal candidate child position. It adds no detector, grade, trait or prose.",
    limitations: ["The vector re-anchors registered results to hypothetical legal moves. Presence is not importance; absence is not safety; engine score and collector payloads do not grade the learner or establish a personality trait."],
    authority: [{ kind: "landed_contract", witnesses: ["derived.opponent.candidate_feature_vector@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "candidate-majority", version: 1 },
    definition: "A pawn is not passed and has no enemy pawn strictly ahead on its file. Supporting pawns are other same-color pawns on an adjacent file whose rank is the subject pawn's rank or any rank behind it from that color's perspective; enemy blockers are opposing pawns on adjacent files strictly ahead of the subject. At least one support is required and support count must be at least blocker count.",
    limitations: ["The convention deliberately omits a backward-pawn classifier and emits no plan or conversion verdict."],
    authority: [{ kind: "landed_contract", witnesses: ["rules.pawn.reading.candidate_majority@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "chessops-king-takes-rook", version: 1 },
    definition: "The internal UCI identity is chessops' Chess960-safe castling form in which a castling king move names the rook square; common king-destination spelling is normalized before legality and identity checks.",
    limitations: ["This is move identity, not the square on which the king finishes and not a source-input dialect."],
    authority: [{ kind: "landed_contract", witnesses: ["packages/runtime/src/legal-moves.ts#MOVE_IDENTITY_CONVENTION", "packages/runtime/src/legal-moves.ts#exactMoveIdentity"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "defence-duty", version: 1 },
    definition: "A duty is a directed pseudo-defence edge under current occupancy from any defender onto a same-color non-king target. Sole defender means the named defender holds the only such edge onto that target. Duties are not legality-filtered; multiple duties alone never imply exploitable overload.",
    limitations: ["Pseudo duty may be legally unexecutable; co-defenders are retained specifically to prevent multi-duty state from being called overload."],
    authority: [{ kind: "landed_contract", witnesses: ["rules.tactic.reading.defender_duty_set@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "development", version: 1 },
    definition: "Role-matched knights on b- and g-file home squares and bishops on c- and f-file home squares are retained per color. A development event is gained when such a minor leaves its home square and lost when it returns.",
    limitations: ["Minor-piece home-square state only; it is not a complete opening-development score or move grade."],
    authority: [{ kind: "landed_contract", witnesses: ["rules.phase.development@1", "rules.transition.event.developed@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "discovered-latency", version: 1 },
    definition: "A friendly non-king screen is the sole blocker between a friendly slider and an enemy target; removing the screen exposes either exact discovered check or a positive legal-exchange@1 capture. Slider, screen, target, ray and exchange operands are retained.",
    limitations: ["Latent one-blocker geometry only; it does not claim the screen should move, that every screen move exposes the ray, or that the relation is important."],
    authority: [{ kind: "landed_contract", witnesses: ["rules.tactic.reading.discovered_latency@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "double-attack", version: 1 },
    definition: "The moved piece attacks at least two enemy targets after the move; each non-king target has a positive legal-exchange@1 capture by that piece. Geometry alone does not emit the event.",
    limitations: ["An exact double attack is not a universal positive prior or a move grade."],
    authority: [{ kind: "landed_contract", witnesses: ["rules.tactic.event.double_attack@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "evidence-reference-resolution", version: 1 },
    definition: "A recorded evidence reference resolves only through the source implementation's documented literal reference grammar and retains its reference, rendered text and source label as separate operands.",
    limitations: ["A family-only reference token does not retain predicate operands or independently establish the referenced semantic fact; attached provider bytes travel as a separate declared source item."],
    authority: [{ kind: "landed_contract", witnesses: ["run.record.evidence_ref_resolution@1", "packages/runtime/src/evidence-ref.ts"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "fork-survival", version: 1 },
    definition: "For every exact legal reply, the moved piece survives and retains a positive legal-exchange@1 capture of at least one original non-king target on its original square. False results retain refuting replies.",
    limitations: ["One-reply local survival only; no inevitability, quality or whole-position claim."],
    authority: [{ kind: "landed_contract", witnesses: ["derived.tactic.fork_survives_reply@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "grade-convention", version: 1 },
    definition: "Learner-point-of-view loss class using paired readings from one engine and search limit, the unrounded win-percentage drop, threshold, context and lane; no best move or principal variation is retained.",
    limitations: ["Single-line evaluations only.", "The grade can be right about the position and wrong about the reason; it is not a lesson."],
    authority: [{ kind: "landed_contract", witnesses: ["derived.grade.move_quality@1", "packages/runtime/src/grade.ts"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "king-landing-square", version: 1 },
    definition: "A move's semantic destination is its ordinary destination except for castling, where it is the square returned by chessops kingCastlesTo for the moving color and castling side.",
    limitations: ["This is a display and semantic destination, not the runtime's internal castling move identity."],
    authority: [{ kind: "landed_contract", witnesses: ["packages/runtime/src/legal-moves.ts#MOVE_DESTINATION_CONVENTION", "packages/runtime/src/legal-moves.ts#semanticDestination", "packages/runtime/src/legal-moves.ts#exactMoveDestination"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "king-opposition-blocker-blind", version: 1 },
    definition: "The named color has opposition when both kings exist, it is the other color's turn, the kings share a file or rank, and there is exactly one square between them for direct opposition or three or five squares for distant opposition. Occupancy of the intervening squares is not checked.",
    limitations: ["This is the shipped blocker-blind legacy predicate. State and signed before/after relations carry no learner valence, relevance or importance."],
    authority: [{ kind: "landed_contract", witnesses: ["packages/runtime/src/structure.ts#opposition", "rules.structural.predicate.king_opposition@1", "rules.structural.reading.king_opposition@1", "rules.structural.event.king_opposition@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "king-shelter", version: 1 },
    definition: "Same-color pawns one or two forward ranks from the king on its file or either adjacent file form the retained shelter set.",
    limitations: ["Shelter state emits no exposed-king, attack, safety or mating-net verdict."],
    authority: [{ kind: "landed_contract", witnesses: ["rules.king.reading.zone_state@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "king-zone", version: 1 },
    definition: "The king zone contains up to eight adjacent squares, excluding the king square. Attackers and defenders are distinct non-king pieces controlling at least one zone square.",
    limitations: ["Escape availability uses the per-color turn clone with en passant cleared; zone state emits no exposed-king, attack, safety or mating-net verdict."],
    authority: [{ kind: "landed_contract", witnesses: ["rules.king.reading.zone_state@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "legal-exchange", version: 1 },
    definition: "One specified legal capture is evaluated by legal recapture-only minimax on its landing square. Either side may stop. Material uses pawn 1, knight 3, bishop 3, rook 5 and queen 9; promotion adds promoted-piece minus pawn. Illegal off-line pinned recaptures and illegal king captures are absent; legal along-ray recaptures and X-rays remain.",
    limitations: ["Units are convention material, never centipawns. Zwischenzugs, replies elsewhere, position value and compensation are outside scope."],
    authority: [{ kind: "landed_contract", witnesses: ["rules.exchange.predicate.legal_exchange@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "local-non-losing", version: 1 },
    definition: "For a legal capture destination, legal-exchange@1 is at least zero. For a quiet destination, after the piece arrives the opponent has no legal capture of it with legal-exchange@1 greater than zero.",
    limitations: ["This is one-exchange local safety, never engine safety, recommendation or goodness. It applies to bishop, knight, rook and queen legal destinations."],
    authority: [{ kind: "landed_contract", witnesses: ["rules.mobility.reading.piece_destinations@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "loose-piece", version: 1 },
    definition: "For each non-king piece belonging to the non-moving side, retain legal capturers, geometric defenders, legal-exchange@1 results and the implementation's en-prise, loose and under-defended flags.",
    limitations: ["Local exchange only; zwischenzugs, compensation and whole-position move quality are outside scope."],
    authority: [{ kind: "landed_contract", witnesses: ["rules.tactic.reading.loose_piece@1", "packages/runtime/src/tactics.ts#loosePieceReading"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "mate-proof", version: 1 },
    definition: "The declared candidate is attacker move one; later attacker moves are existential and every defender reply is enumerated through one to four attacker moves. One node is counted per visited position before cap and terminal checks; the cap is 250000. Attacker moves sort check-first then canonical UCI, defender moves canonical UCI. Results are proved, refuted by an escaping reply or terminal non-mate, or budget_exhausted.",
    limitations: ["Five-plus attacker moves, engine mate claims, move quality and king-zone inference are outside this convention."],
    authority: [{ kind: "landed_contract", witnesses: ["rules.tactic.consequence.forced_mate_after_move@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "material-role-signature", version: 1 },
    definition: "Per-color counts of pawns, knights, bishops, rooks and queens. Asymmetry is the unordered role-count difference vector; event-comparison magnitude is the sum of the five absolute per-role count differences.",
    limitations: ["Kings are excluded. No piece-value scalar, material advantage, imbalance quality or exchange advice is emitted."],
    authority: [{ kind: "landed_contract", witnesses: ["derived.material.reading.role_signature@1", "derived.material.event.role_asymmetry@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "maximal_pawn_reach", version: 1 },
    definition: "An enemy pawn is a push attacker when it is on an adjacent file and can geometrically reach the rank from which it attacks the target; it is a capture attacker when the minimum file captures needed to reach a target-adjacent file do not exceed its forward rank advance. The square is safe only when both sets are empty.",
    limitations: ["The model admits every geometrically possible forward or capture migration while ignoring blockers, capture availability, turn order and move legality. False may be pessimistic; true establishes only absence of an opposing-pawn reach path."],
    authority: [{ kind: "landed_contract", witnesses: ["packages/runtime/src/structure.ts#pawnSafetyOnPosition", "rules.structural.predicate.pawn_safe_square@1", "rules.structural.predicate.outpost@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "mover-turn-ep-cleared", version: 1 },
    definition: "The pass clone makes the original mover the side to move in the after-position and clears en passant before legal controller and capture checks.",
    limitations: ["The clone is an authority input only. The joined edge and capture do not establish removal, deflection, overload, force, success, safety or move quality."],
    authority: [{ kind: "landed_contract", witnesses: ["derived.tactic.defender_exposure@1", "packages/runtime/src/semantic-evidence.ts#defenderExposureOperands"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "observed-window", version: 1 },
    definition: "N consecutive move anchors retain N+1 ordered nodes, byte-equal shared FEN and node boundaries, canonical UCI and exact subject identity.",
    limitations: ["Recorded order never establishes intent, force, best play or causality."],
    authority: [{ kind: "landed_contract", witnesses: ["derived.tactic.square_clearance_observed@1", "packages/runtime/src/semantic-evidence.ts#canonicalRecordedPath"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "opening-deepest-reached", version: 1 },
    definition: "The deepest opening reached is the greatest recorded matched ply, using the lowest node id as deterministic tie-break and retaining every matched visit.",
    limitations: ["Retrospective deepest match never labels the current position and never infers move order from FEN."],
    authority: [{ kind: "landed_contract", witnesses: ["derived.opening.deepest_reached@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "overload-conflict", version: 1 },
    definition: "One named defender is sole defender of the captured target and another retained target; it has a legal recapture; no legal recapture preserves every retained sole duty; and after every recapture at least one retained target has a positive legal-exchange@1 capture. No legal recapture abstains.",
    limitations: ["The broad lost-duty-edge rule is rejected. This is candidate-time arithmetic only and does not grade or recommend the candidate."],
    authority: [{ kind: "landed_contract", witnesses: ["derived.tactic.overloaded_defender_response_conflict@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "pawn-relations", version: 1 },
    definition: "An opposing-pawn contact is a directed pawn-attack edge; a direct lock is a White pawn immediately below a Black pawn on the same file; a passed pawn's blockers are opposing pawns strictly ahead on its file or either adjacent file; protection is a same-color pawn attack on the subject; and a connected passed pair is any two passed pawns of one color on adjacent files.",
    limitations: ["Connected-passer rank distance is deliberately unrestricted; all pawn and blocker identities remain literal."],
    authority: [{ kind: "landed_contract", witnesses: ["rules.pawn.reading.contacts@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "pressure-line", version: 1 },
    definition: "A bishop, rook or queen slider and an enemy rook or queen target are collinear with exactly one occupied square between them, and with that screen removed the target lies in the slider's own chessops attack set. The screen belongs to the target's color, has lower pawn-1/knight-3/bishop-3/rook-5/queen-9 role value than the target, and is not a king. Retention requires the same slider color and role plus the exact same screen and target square, color and role.",
    limitations: ["The observed harassment sequence additionally requires a pawn newly attacking the bishop and that exact bishop relocating on the consecutive reply. It establishes no force, quality or intent."],
    authority: [{ kind: "landed_contract", witnesses: ["derived.pawn.sequence.harassment_pressure@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "race-arrival", version: 1 },
    definition: "Two or more opposite-color named pawns have unblocked forward paths; side to move and the initial double push are respected; strict turn alternation models no captures, checks, king or piece activity.",
    limitations: ["Ordering and per-pawn arrival distance are descriptive and contain no outcome verdict."],
    authority: [{ kind: "landed_contract", witnesses: ["packages/runtime/src/evidence-catalog.ts#BREADTH_CONVENTION_TEXT.raceArrival", "packages/runtime/src/pawn-dynamics.ts#RACE_ARRIVAL_CONVENTION"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "ray-classification", version: 1 },
    definition: "One-blocker slider rays are classified with precedence absolute pin, skewer, relative pin, then X-ray; each item retains slider, blocker, target, ray and any declared value comparison. Absolute-pin geometry is exact.",
    limitations: ["The combined projection conservatively declares convention grounding. State geometry is not a move grade, tactical inevitability or statement that a ray is important."],
    authority: [{ kind: "landed_contract", witnesses: ["rules.tactic.reading.ray_classification@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "space", version: 1 },
    definition: "Literal pawn-attacked squares in the enemy half are counted by queenside a-c, central d-e and kingside f-h zones; differentials are White minus Black.",
    limitations: ["Pawn control only; piece control, mobility, territory quality, recommendation and move grade are outside this convention."],
    authority: [{ kind: "landed_contract", witnesses: ["rules.structural.reading.space@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "square-control", version: 1 },
    definition: "Square control uses no hypothetical occupant. A pseudo controller is a piece whose chessops attack set contains the target under current occupancy. A legal controller is that same source piece only when the target also appears in its actual allDests set after a valid clone makes the piece's color the side to move and clears en passant.",
    limitations: ["Opposing-king-square pseudo control makes the checking color's complete legal set abstain invalid_turn_clone. No individual target receives an invented occupant."],
    authority: [{ kind: "landed_contract", witnesses: ["rules.square.reading.control@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "standard-uci-king-destination", version: 1 },
    definition: "Engine bestmove and pack move UCI use common standard UCI castling spelling with the king's landing square as destination before normalization to the internal move identity.",
    limitations: ["This is an inbound source dialect, not the application's stored move identity."],
    authority: [{ kind: "landed_contract", witnesses: ["packages/runtime/src/legal-moves.ts#INBOUND_MOVE_DIALECT", "packages/runtime/src/legal-moves.ts#normalizeInboundMove"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "story-last-level", version: 1 },
    definition: "The last-level flag uses a within-one-pawn evaluation threshold and is gated by whether the imported result says the learner lost.",
    limitations: ["This is a deterministic story presentation rule, not a chess significance or move-quality claim."],
    authority: [{ kind: "landed_contract", witnesses: ["derived.story.last_level@1", "packages/runtime/src/story.ts"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "story-rank", version: 1 },
    definition: "Story prominence uses a fixed kind-priority order with absolute recorded-evaluation delta as tie-break.",
    limitations: ["The ordering is presentation prominence, not chess significance."],
    authority: [{ kind: "landed_contract", witnesses: ["derived.story.rank@1", "packages/runtime/src/story.ts"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "story-title", version: 1 },
    definition: "Story title is a fixed composition over rank, recorded outcome and result, learner side and endgame label; imported result verbs are learner-relative.",
    limitations: ["The title is deterministic presentation and does not infer intent or add a chess judgement."],
    authority: [{ kind: "landed_contract", witnesses: ["derived.story.title@1", "packages/runtime/src/story.ts"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "threat", version: 1 },
    definition: "Give the move to the opponent and clear en passant, then enumerate positive legal-exchange@1 captures and mate in one. Abstain while the side to move is in check.",
    limitations: ["Quiet promotion, deeper mating nets, trapping threats and forking threats are outside this one-ply convention. Threat presence is not a move grade, recommendation, forcing claim or statement of intent."],
    authority: [{ kind: "landed_contract", witnesses: ["rules.tactic.consequence.threat@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "trade-completed", version: 1 },
    definition: "Two immediately consecutive legal captures have a byte-identical shared position, with the second capture occurring on the first capture's landing square.",
    limitations: ["Immediate capture-recapture only; later return captures and strategic exchange judgements are outside scope."],
    authority: [{ kind: "landed_contract", witnesses: ["derived.exchange.trade_completed@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "trapped", version: 1 },
    definition: "A non-pawn, non-king piece of the side to move is locally trapped only when the opponent-turn clone has a positive legal-exchange@1 capture on its current square and every legal destination is locally losing. Capture destinations use their own exchange result; quiet destinations retain every positive opponent capture after relocation.",
    limitations: ["Local exchange and legal destinations only; defending moves, intermezzi, compensation, counterattacks and search-derived claims that the piece is lost are outside scope."],
    authority: [{ kind: "landed_contract", witnesses: ["rules.tactic.reading.trapped_piece@1"], snapshotRef: "62a5731f" }],
    disclosure: { kind: "definition_and_limitations" },
  },
  // END GENERATED initial declarations
  // Declarations authored directly after the initial population (rfc/semantic-convention-provenance.md
  // §1.2: a future declaration is authored under the normal authority union). The first three name
  // meanings already shipped by rfc/evidence-value-authority.md §3.3–§3.4; the six endgame setup and
  // method conventions move here from their interim in-code registration (endgame-setup.ts,
  // endgame-method.ts). `evidence-conventions.test.ts` binds each to the code that computes it.
  {
    ref: { id: "endgame-material-census", version: 1 },
    definition: "Applies only to a position phase-bands@1 labels endgame. With each colour's non-pawn, non-king pieces listed: neither colour has any is a pawn ending; each colour has exactly one rook and there is exactly one pawn on the board is rook and pawn versus rook; otherwise each colour has exactly one rook is a rook ending; each colour has exactly one queen is a queen ending; each colour has exactly one bishop or knight is a minor-piece ending; any other material is an endgame with no material family.",
    limitations: [
      "A material family is not a technique, outcome or recommendation.",
      "Only the five listed families are named; every other endgame material is reported as no family rather than guessed.",
    ],
    authority: [{ kind: "landed_contract", witnesses: ["rules.endgame.classification@1", "packages/runtime/src/endgame.ts#endgameClassification"], snapshotRef: EVA_SNAPSHOT }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "named-structure-catalogue", version: 1 },
    definition: "A position matches a registered structure-catalogue entry when that entry's registered expression holds under the structural-feature vocabulary: carlsbad = all(half_open_file(white, c); half_open_file(black, e); white pawn on d4; black pawn on d5; black pawn on c6); iqp-white = all(white pawn on d4; isolated_pawn(white, d); half_open_file(black, d)); iqp-black = all(black pawn on d5; isolated_pawn(black, d); half_open_file(white, d)); maroczy-bind = all(white pawn on c4; white pawn on e4; half_open_file(white, d); half_open_file(black, c)). The payload carries the entry's id, catalogue name and catalogue provenance note.",
    limitations: [
      "A catalogue detector match names a registered pawn skeleton; it is not a plan, evaluation or recommendation.",
      "Only the four registered catalogue entries exist; an unlisted skeleton is not matched.",
    ],
    authority: [{ kind: "landed_contract", witnesses: ["rules.structural.reading.named_structure@2", "packages/runtime/src/structure.ts#STRUCTURE_PREDICATES"], snapshotRef: EVA_SNAPSHOT }],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "phase-bands", version: 1 },
    definition: "Phase is computed from one FEN. Non-pawn material counts queen 9, rook 5, bishop 3, knight 3 per colour; undeveloped minors count each colour's bishops or knights standing on its own b, c, f or g back-rank square, role-agnostic. With M the larger colour's material and U the two colours' undeveloped-minor total: M <= 13 is endgame; otherwise M < 18 is unclear (material transition gap); otherwise U >= 5 is opening, U <= 2 is middlegame, and any U between them is unclear (development transition gap). The reading records exactly one of these five decision arms with its integer margin or distances.",
    limitations: [
      "Margins and distances are never a probability, accuracy estimate, number of moves to transition, opening identity or provider-availability signal.",
      "A phase band is a product convention, not a claim about the game's character.",
    ],
    authority: [
      { kind: "landed_contract", witnesses: ["rules.phase.reading@2", "packages/runtime/src/phase.ts#phaseBandReading", "packages/runtime/src/phase.ts#classifyPhase"], snapshotRef: EVA_SNAPSHOT },
      { kind: "product_rule", rulingRef: "[[D2484]]" },
    ],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "lucena-setup", version: 1 },
    definition: "Lucena position setup: a position matches only when every operand holds. material_krpkr: Exactly five pieces: one side has king, rook and one pawn; the other has king and rook only. The side with the pawn is the attacker. pawn_not_rook_pawn: The pawn is on one of the b- through g-files. pawn_on_seventh: The pawn stands on the attacker's seventh rank. attacking_king_on_queening_square: The attacking king stands on the pawn's promotion square. attacking_rook_cuts_off_defending_king: The attacking rook stands on a file strictly between the pawn's file and the defending king's file, and every square of the rook's file from the rook to the defending king's rank is empty. Ranks are relative to the named side (1 = its back rank).",
    limitations: [
      "A match is geometry under this convention only; it carries no outcome, advice, reachability or significance.",
      "attacking_rook_cuts_off_defending_king: \"Cuts off by a file\" is pinned as the rook standing between the two files with an unobstructed ray along its file to the defending king's rank; a rook whose file ray is blocked does not cut the king off (the D2495 blocked-ray falsifier).",
      "Not required in this version: defending rook on the file on the other side of the pawn. Chess.com's definition omits it; v1 requires only the conditions both sources state, and a defending rook elsewhere does not make the listed geometry less of a Lucena setup under Chess.com's reading.",
    ],
    authority: [
      { kind: "published_source", citation: "Lucena position — Wikipedia, https://en.wikipedia.org/wiki/Lucena_position (oldid=1356336262; retrieved 2026-09-24)", licence: WIKIPEDIA_LICENCE },
      { kind: "published_source", citation: "Lucena Position — Chess Terms, Chess.com, https://www.chess.com/terms/lucena-position-chess (retrieved page; retrieved 2026-09-24)", licence: QUOTATION_LICENCE },
    ],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "philidor-third-rank-setup", version: 1 },
    definition: "Philidor position (third-rank defence) setup: a position matches only when every operand holds. material_krpkr: Exactly five pieces: one side has king, rook and one pawn; the other has king and rook only. The side with the pawn is the attacker. defending_king_on_or_adjacent_to_queening_square: The defending king stands on the pawn's promotion square or on a square adjacent to it (king distance at most 1); any pawn file. pawn_short_of_defender_third_rank: The pawn stands on the attacker's fifth rank or lower. attacking_king_beyond_defender_third_rank: The attacking king stands on the defender's fourth rank or farther from the defender's back rank. defending_rook_on_defender_third_rank: The defending rook stands on the defender's third rank. Ranks are relative to the named side (1 = its back rank).",
    limitations: [
      "A match is geometry under this convention only; it carries no outcome, advice, reachability or significance.",
      "defending_rook_on_defender_third_rank: The source's purpose clause (\"keeping the opposing king off that rank\") is not an extra square-control predicate: v1 requires the rook's rank only.",
      "Not required in this version: defending king exactly on the promotion square, pawn at least four squares from promotion, rook merely with access to the third rank. Chess.com states a narrower king condition, a stricter pawn distance (\"at least four squares away from promotion\") and rook access rather than placement; v1 adopts the Wikipedia characteristic list, and the disagreement is disclosed rather than averaged.",
    ],
    authority: [
      { kind: "published_source", citation: "Philidor position — Wikipedia, https://en.wikipedia.org/wiki/Philidor_position (oldid=1356336197; retrieved 2026-09-24)", licence: WIKIPEDIA_LICENCE },
    ],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "vancura-setup", version: 1 },
    definition: "Vančura position setup: a position matches only when every operand holds. material_krpkr: Exactly five pieces: one side has king, rook and one pawn; the other has king and rook only. The side with the pawn is the attacker. rook_pawn: The pawn is on the a- or h-file. pawn_not_beyond_sixth: The pawn stands on the attacker's sixth rank or lower. attacking_rook_in_front_of_pawn: The attacking rook stands on the pawn's file on a higher attacker-relative rank than the pawn. defending_rook_attacks_pawn_from_side: The defending rook stands on the pawn's rank and every square between them is empty. defending_king_beyond_its_rook: The defending king's file is on the far side of the defending rook's file from the pawn. defending_king_in_drawing_zone: The defending king stands on the attacker's seventh rank on one of the two files farthest from the pawn (g7/h7 for a White a-pawn; mirrored by file and colour). Ranks are relative to the named side (1 = its back rank).",
    limitations: [
      "A match is geometry under this convention only; it carries no outcome, advice, reachability or significance.",
      "defending_rook_attacks_pawn_from_side: \"From some distance away\" is not pinned to a minimum distance in v1; only the lateral, unobstructed attack is required.",
      "defending_king_in_drawing_zone: The two cited squares are for a White a-pawn; the h-pawn and Black-pawn cases are the file and colour mirror images.",
    ],
    authority: [
      { kind: "published_source", citation: "Rook and pawn versus rook endgame — Wikipedia, §Vančura position, https://en.wikipedia.org/wiki/Rook_and_pawn_versus_rook_endgame (oldid=1364966292; retrieved 2026-09-24)", licence: WIKIPEDIA_LICENCE },
      { kind: "published_source", citation: "Karsten Müller: Understanding the Vancura draw — ChessBase (2014), https://en.chessbase.com/post/karsten-mueller-understanding-the-vancura-draw (retrieved page; retrieved 2026-09-24)", licence: QUOTATION_LICENCE },
    ],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "lucena-bridge-method", version: 1 },
    definition: "lucena method stages observed along one exact recorded path anchored by a positive lucena-setup@1 setup match, for the pawn side. lucena_bridge_prepared: The attacking rook moves to the attacker's fourth rank while the pawn is on its seventh rank and the attacking king stays on the promotion square. lucena_king_excursion_started (after lucena_bridge_prepared): The attacking king moves off the promotion square. lucena_bridge_interposed (after lucena_king_excursion_started): While in check, the attacker moves the rook so that it blocks the check: afterwards the side is out of check and the attacking king, the attacking rook and the defending rook share one file with the attacking rook between them.",
    limitations: [
      "A method stage is a retrospective observation over an exact recorded path; it says nothing about whether the stage was best, whether the outcome was preserved, or whether the setup could have been reached or forced.",
      "lucena_bridge_prepared: Only the fourth-rank bridge is recognized; the source's fifth-rank alternative (\"A bridge can also be built on the fifth rank\") is not a v1 stage.",
      "lucena_bridge_interposed: The bridge is pinned to a same-file interposition between the checking rook and the king.",
    ],
    authority: [
      { kind: "published_source", citation: "Lucena position — Wikipedia, https://en.wikipedia.org/wiki/Lucena_position (oldid=1356336262; retrieved 2026-09-24)", licence: WIKIPEDIA_LICENCE },
    ],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "philidor-third-rank-method", version: 1 },
    definition: "philidor method stages observed along one exact recorded path anchored by a positive philidor-third-rank-setup@1 setup match, for the defender. philidor_pawn_entered_defender_third: The attacker's pawn moves from its fifth rank or lower onto its sixth rank (the defender's third rank). philidor_rear_rank_switch (after philidor_pawn_entered_defender_third): The defending rook moves from the defender's third rank to the defender's seventh or eighth rank. philidor_rear_check_delivered (after philidor_rear_rank_switch): The defending rook moves and gives check from an attacker-relative rank lower than the attacking king's.",
    limitations: [
      "A method stage is a retrospective observation over an exact recorded path; it says nothing about whether the stage was best, whether the outcome was preserved, or whether the setup could have been reached or forced.",
      "philidor_rear_check_delivered: \"From behind\" is pinned as the checking rook standing on a lower attacker-relative rank than the attacking king.",
    ],
    authority: [
      { kind: "published_source", citation: "Philidor position — Wikipedia, https://en.wikipedia.org/wiki/Philidor_position (oldid=1356336197; retrieved 2026-09-24)", licence: WIKIPEDIA_LICENCE },
    ],
    disclosure: { kind: "definition_and_limitations" },
  },
  {
    ref: { id: "vancura-method", version: 1 },
    definition: "vancura method stages observed along one exact recorded path anchored by a positive vancura-setup@1 setup match, for the defender. vancura_pawn_entered_seventh: The attacker's rook pawn moves onto its seventh rank. vancura_rook_moved_behind (after vancura_pawn_entered_seventh): The defending rook moves onto the pawn's file on a lower attacker-relative rank than the pawn.",
    limitations: [
      "A method stage is a retrospective observation over an exact recorded path; it says nothing about whether the stage was best, whether the outcome was preserved, or whether the setup could have been reached or forced.",
    ],
    authority: [
      { kind: "published_source", citation: "Rook and pawn versus rook endgame — Wikipedia, §Vančura position, https://en.wikipedia.org/wiki/Rook_and_pawn_versus_rook_endgame (oldid=1364966292; retrieved 2026-09-24)", licence: WIKIPEDIA_LICENCE },
    ],
    disclosure: { kind: "definition_and_limitations" },
  },
]);

// ---------------------------------------------------------------------------------------------
// Identity grammar
// ---------------------------------------------------------------------------------------------

const BASE_ID = /^[a-z][a-z0-9_-]*$/u;
const REF_TEXT = /^([a-z][a-z0-9_-]*)@([1-9][0-9]*)$/u;
const SHA256 = /^sha256:[0-9a-f]{64}$/u;

export class ConventionRegistryError extends TypeError {
  constructor(readonly code: string, message: string) {
    super(`${code}: ${message}`);
    this.name = "ConventionRegistryError";
  }
}

export function conventionRefKey(ref: ConventionRef): string {
  return `${ref.id}@${ref.version}`;
}

/** Parses an exact `id@version` ref; version is a canonical positive safe integer. */
export function parseConventionRef(text: string): ConventionRef {
  const match = typeof text === "string" ? text.match(REF_TEXT) : null;
  if (match === null || !Number.isSafeInteger(Number(match[2]))) throw new ConventionRegistryError("CONVENTION_REF_INVALID", `${String(text)} is not an exact id@version ref`);
  return Object.freeze({ id: match[1]!, version: Number(match[2]) });
}

/** The register's member spelling: `defence-duty@1` is `defence_duty_v1`. */
export function conventionMember(ref: ConventionRef): string {
  return `${ref.id.replaceAll("-", "_")}_v${ref.version}`;
}

export function compareConventionRefs(left: ConventionRef, right: ConventionRef): number {
  return left.id < right.id ? -1 : left.id > right.id ? 1 : left.version - right.version;
}

const text = (value: unknown): value is string => typeof value === "string" && value.trim() !== "";
const exactKeys = (value: unknown, keys: readonly string[]): boolean =>
  typeof value === "object" && value !== null && !Array.isArray(value) && Object.keys(value).length === keys.length && keys.every((key) => Object.hasOwn(value, key));

function assertAuthority(ref: string, authority: unknown): void {
  const shape = (keys: readonly string[]): boolean => exactKeys(authority, keys);
  const item = authority as Record<string, unknown>;
  const valid = typeof authority === "object" && authority !== null && (
    (item.kind === "position_rules" && shape(["kind", "implementation"]) && text(item.implementation))
    || (item.kind === "landed_contract" && shape(["kind", "witnesses", "snapshotRef"]) && Array.isArray(item.witnesses) && item.witnesses.length > 0
      && item.witnesses.every(text) && typeof item.snapshotRef === "string" && /^[0-9a-f]{7,40}$/u.test(item.snapshotRef))
    // A citation must resolve to a retrievable URL; a ruling to a ledger id.
    || (item.kind === "published_source" && shape(["kind", "citation", "licence"]) && text(item.citation) && /https:\/\/\S+/u.test(item.citation as string) && text(item.licence))
    || (item.kind === "product_rule" && shape(["kind", "rulingRef"]) && typeof item.rulingRef === "string" && /^\[\[D\d+[a-z]?\]\]$/u.test(item.rulingRef))
    || (item.kind === "measured_record" && shape(["kind", "recordRef"]) && text(item.recordRef))
  );
  if (!valid) throw new ConventionRegistryError("CONVENTION_AUTHORITY_INVALID", `${ref} carries an unsupported or unresolvable authority ${JSON.stringify(authority)}`);
}

/** The semantic image of one declaration: every field, canonical key order, no path or position. */
function semanticImage(declaration: ConventionDeclaration): unknown {
  return {
    ref: { id: declaration.ref.id, version: declaration.ref.version },
    definition: declaration.definition,
    limitations: [...declaration.limitations],
    authority: declaration.authority.map((authority) => ({ ...authority })),
    disclosure: { ...declaration.disclosure },
  };
}

/** `sha256:<hex>` digest of one declaration's complete semantic image. */
export function conventionSemanticDigest(declaration: ConventionDeclaration): string {
  return `sha256:${evidenceDigest(semanticImage(declaration))}`;
}

/**
 * Freezes and orders declarations by `(id, version)`. Refuses duplicate refs, malformed refs, a
 * skipped or backward lineage (`id@2` needs `id@1`), blank definition/limitations/disclosure and
 * any unsupported authority shape. The digest covers every semantic field, never order or path.
 */
export function compileConventionRegistry(declarations: readonly ConventionDeclaration[]): CompiledConventionRegistry {
  if (!Array.isArray(declarations)) throw new ConventionRegistryError("CONVENTION_REGISTRY_INVALID", "declarations must be an array");
  const seen = new Set<string>();
  const members = new Set<string>();
  for (const declaration of declarations) {
    if (!exactKeys(declaration, ["ref", "definition", "limitations", "authority", "disclosure"])) throw new ConventionRegistryError("CONVENTION_DECLARATION_INVALID", "a declaration must have exactly ref, definition, limitations, authority and disclosure");
    const ref = declaration.ref;
    if (!exactKeys(ref, ["id", "version"]) || !BASE_ID.test(ref.id) || !Number.isSafeInteger(ref.version) || ref.version < 1) throw new ConventionRegistryError("CONVENTION_REF_INVALID", `malformed ref ${JSON.stringify(ref)}`);
    const key = conventionRefKey(ref);
    if (seen.has(key)) throw new ConventionRegistryError("CONVENTION_REF_DUPLICATE", `${key} is declared twice`);
    seen.add(key);
    const member = conventionMember(ref);
    if (members.has(member)) throw new ConventionRegistryError("CONVENTION_MEMBER_ALIAS", `${key} aliases register member ${member}`);
    members.add(member);
    if (!text(declaration.definition)) throw new ConventionRegistryError("CONVENTION_DECLARATION_BLANK", `${key} has a blank definition`);
    if (!Array.isArray(declaration.limitations) || declaration.limitations.length === 0 || !declaration.limitations.every(text)) throw new ConventionRegistryError("CONVENTION_DECLARATION_BLANK", `${key} needs at least one non-blank mandatory limitation`);
    if (!Array.isArray(declaration.authority) || declaration.authority.length === 0) throw new ConventionRegistryError("CONVENTION_AUTHORITY_INVALID", `${key} needs at least one authority`);
    for (const authority of declaration.authority) assertAuthority(key, authority);
    const disclosure = declaration.disclosure as Record<string, unknown>;
    const disclosureValid = (disclosure?.kind === "definition_and_limitations" && exactKeys(disclosure, ["kind"]))
      || (disclosure?.kind === "reviewed_text" && exactKeys(disclosure, ["kind", "summary", "detail"]) && text(disclosure.summary) && text(disclosure.detail));
    if (!disclosureValid) throw new ConventionRegistryError("CONVENTION_DECLARATION_BLANK", `${key} has a blank or unsupported disclosure`);
  }
  for (const key of seen) {
    const { id, version } = parseConventionRef(key);
    if (version > 1 && !seen.has(`${id}@${version - 1}`)) throw new ConventionRegistryError("CONVENTION_LINEAGE_SKIPPED", `${key} has no ${id}@${version - 1} predecessor`);
  }
  const ordered = [...declarations].sort((left, right) => compareConventionRefs(left.ref, right.ref));
  const digest = `sha256:${evidenceDigest(ordered.map(semanticImage))}`;
  return deepFreeze({ declarations: ordered.map((declaration) => deepFreeze(structuredCloneDeclaration(declaration))), digest });
}

function structuredCloneDeclaration(declaration: ConventionDeclaration): ConventionDeclaration {
  return semanticImage(declaration) as ConventionDeclaration;
}

export const CONVENTION_REGISTRY: CompiledConventionRegistry = compileConventionRegistry(CONVENTION_DECLARATIONS);

const DECLARATION_BY_KEY: ReadonlyMap<string, ConventionDeclaration> = new Map(CONVENTION_REGISTRY.declarations.map((declaration) => [conventionRefKey(declaration.ref), declaration]));

export function registeredConvention(ref: ConventionRef): ConventionDeclaration | undefined {
  return DECLARATION_BY_KEY.get(conventionRefKey(ref));
}

export function isRegisteredConvention(ref: ConventionRef): boolean {
  return DECLARATION_BY_KEY.has(conventionRefKey(ref));
}

// ---------------------------------------------------------------------------------------------
// Value-level convention receipt (rfc/semantic-convention-provenance.md §4; [[D1921]])
// ---------------------------------------------------------------------------------------------

export type ConventionDerivationReceipt =
  | Readonly<{ kind: "source" }>
  | Readonly<{
      kind: "derived";
      /** Canonical sorted exact-projection identity of the declared member actually used. */
      member: string;
      /** Canonical multiset of every concrete sealed input value (order-free, multiplicity kept). */
      inputs: readonly Readonly<{ projection: string; valueDigest: string }>[];
    }>;

export interface ConventionReceipt {
  readonly refs: readonly ConventionRef[];
  readonly registryDigest: string;
  readonly derivation: ConventionDerivationReceipt;
  readonly digest: string;
}

/**
 * Builds one frozen receipt. `refs` are validated against the registry and canonicalized; input
 * entries are sorted so input order never changes the receipt while multiplicity does.
 */
export function conventionReceipt(refs: readonly ConventionRef[], derivation: ConventionDerivationReceipt, registry: CompiledConventionRegistry = CONVENTION_REGISTRY): ConventionReceipt {
  const byKey = new Map<string, ConventionRef>();
  for (const ref of refs) {
    const key = conventionRefKey(ref);
    if (registry === CONVENTION_REGISTRY ? !DECLARATION_BY_KEY.has(key) : !registry.declarations.some((declaration) => conventionRefKey(declaration.ref) === key)) {
      throw new ConventionRegistryError("CONVENTION_REF_UNREGISTERED", `${key} is not a registered convention`);
    }
    byKey.set(key, Object.freeze({ id: ref.id, version: ref.version }));
  }
  const canonicalRefs = [...byKey.values()].sort(compareConventionRefs);
  const canonicalDerivation: ConventionDerivationReceipt = derivation.kind === "source"
    ? { kind: "source" }
    : {
        kind: "derived",
        member: derivation.member,
        inputs: [...derivation.inputs].map((input) => ({ projection: input.projection, valueDigest: input.valueDigest }))
          .sort((left, right) => left.projection < right.projection ? -1 : left.projection > right.projection ? 1 : left.valueDigest < right.valueDigest ? -1 : left.valueDigest > right.valueDigest ? 1 : 0),
      };
  const body = { refs: canonicalRefs.map((ref) => ({ id: ref.id, version: ref.version })), registryDigest: registry.digest, derivation: canonicalDerivation };
  return deepFreeze({ ...body, refs: canonicalRefs, digest: `sha256:${evidenceDigest(body)}` });
}

export function isConventionDigest(value: unknown): value is string {
  return typeof value === "string" && SHA256.test(value);
}

function deepFreeze<T>(value: T): T {
  if (value !== null && typeof value === "object" && !Object.isFrozen(value)) {
    for (const entry of Object.values(value as Record<string, unknown>)) deepFreeze(entry);
    Object.freeze(value);
  }
  return value;
}
