import { DRILL_RUN_SCHEMA_VERSION } from "@chess-tabiya/schema";

export { canonicalFen, transposeKey } from "./chess.js";
export {
  deviationAnchors,
  insideAuthoredBoundary,
  lineMembership,
  spineNodeIdFor,
  spinePositionIndex,
  type LineMembershipEntry,
  type LineVerdict,
} from "./line.js";
export { BranchQueryError, branchPath, branchPaths } from "./branch-path.js";
export {
  MAX_COMPARISON_BRANCHES,
  compareBranches,
  type BranchColumn,
  type BranchComparison,
  type BranchConsequence,
  type CheckpointHit,
  type ComparisonEvidenceEntry,
  type ComparisonLineEntry,
  type ComparisonRow,
  type ComparisonScore,
  type NodeRef,
  type ObjectiveTimelineEntry,
} from "./compare.js";
export { BRANCH_COLLAPSE_FLOOR, branchDecidedness, collapsedBranchIds, renderCollapseExplanation, type AssessmentCategory, type AssessmentObjective, type CollapseExplanation, type Decidedness, type DecidednessGround, type TablebaseCategory as BranchTablebaseCategory } from "./branch-scale.js";
export { comparisonEngineTrajectory, comparisonNarrative, comparisonStrips, consumeComparisonEngineTrajectory, consumeComparisonStripEvidence, type BranchStrips, type ComparisonNarrative, type NarrativeGroup, type PieceRoute, type StripEntry } from "./compare-strips.js";
export {
  RuntimeError,
  assertActiveWriter,
  type IllegalMoveReason,
  type RuntimeErrorCode,
} from "./errors.js";
export { appendEvents, deriveSegments, eventsSince, groupsFromEvents, projectRun } from "./events.js";
export { feedbackDeliveryOpen, feedbackDisclosed } from "./feedback.js";
export { consumeShapeFiring, declareShapeFiringEvidence, shapeFiringEvidence, shapeFirings, type ShapeFiring, type ShapeTriggerSource } from "./shape-firing.js";
export { classifyPhase, renderPhaseReading, ENDGAME_MATERIAL_MAX, DEVELOPED_MATERIAL_MIN, OPENING_UNDEVELOPED_MIN, MIDDLEGAME_UNDEVELOPED_MAX, PHASE_PROVENANCE, type DetectedPhase, type PhaseReading } from "./phase.js";
export { SILENT_ASSISTANCE, permittedAssistance, reviewingGrant, type AssistanceConfig, type AssistanceContext, type AssistancePermission } from "./assistance.js";
export { consumePivotalMarkers, liveAdmitted, liveMarkers, pivotalMarkerEvidence, pivotalMarkers, renderPivotalMarker, type PivotalKind, type PivotalMarker, type IrreversibilityDetail, type PhaseChangeDetail, type DivergenceDetail, type CollapseDetail } from "./pivotal.js";
export {
  TRANSITION_FEATURE_KINDS,
  capturedRole,
  irreversibility,
  matchesTransitionExpression,
  matchesTransitionFeature,
  transitionFeatureKinds,
  transitionReading,
  transitionSemanticFacts,
  type TransitionObservation,
  type TransitionReading,
  type TransitionSemanticFact,
} from "./transition.js";
export { endgameReading, renderEndgameReading, type EndgameTypeId, type EndgameReading, type TechniqueRef } from "./endgame.js";
export { retrospectivePivot } from "./adaptive.js";
export { STORY_MATE_CP, STORY_PIVOT_CP, renderReviewStoryEvidence, reviewStoryTitle, storyDeclaredEvidence, storyMoments, suggestTitle, type StoryEvaluation, type StoryMoment, type StoryMomentKind, type StoryProjection, type StoryTitleInput } from "./story.js";
export {
  voiceCheck,
  renderRecordedReading,
  BANNED_JUDGEMENTS,
  PRESCRIPTIVE_VERBS,
  CHESS_LEXICON,
  type EngineReadingValues,
  type EvidencePacket,
  type PositionEvidenceIndex,
  type RecordedReading,
  type ShapeEntryRef,
  type TablebaseReadingValues,
  type VoiceCheckResult,
} from "./voice.js";
export { matchKeyPoints, normalizeReasoningText } from "./reasoning.js";
export { terminalOutcome } from "./outcome.js";
export {
  FLOAT32_POLICY_MASS_TOLERANCE,
  PolicyMassError,
  humanConcessionMass,
  type HumanConcessionMass,
  type PolicyMassCandidate,
} from "./practical-difficulty.js";
export {
  AUTHORABLE_TEMPO_VERDICTS,
  DECLARED_UNGRADEABLE_VERDICTS,
  TEMPO_GRADEABLE_VERDICTS,
  TEMPO_VERDICTS,
  UNAUTHORED_TEMPO_DEFAULTS,
  tempoMovesFromRun,
  unauthoredTempoTransition,
  windowStates,
  type TempoMove,
  type TempoVerdict,
  type TimingWindowState,
  type TriggerResolver,
} from "./tempo.js";
export {
  STRUCTURAL_FEATURE_KINDS,
  emptyBoardDistance,
  matchesStructuralExpression,
  matchesStructuralFeature,
  mirrorExpression,
  observationIdentity,
  pawnSafety,
  structuralDelta,
  structuralFeatureKinds,
  structuralReading,
  vacationReading,
  type FeatureComparison,
  type DistanceRole,
  type DistanceTarget,
  type FileRange,
  type FileTemplateFeature,
  type MirrorAxis,
  type PawnSafety,
  type ReachRole,
  type ReachScope,
  type Quantifier,
  type RankRange,
  type SquareRegion,
  type SquareTemplateFeature,
  type StructuralDelta,
  type StructuralExpression,
  type StructuralFeature,
  type StructuralFeatureKind,
  type StructuralObservation,
  type StructuralReading,
  type StructureId,
  type StructureMatch,
  type VacationReading,
} from "./structure.js";
export {
  declareStructuralPredicateEvidence,
  evaluateAuthoredStructuralPredicate,
  evaluateStructuralPredicate,
  matchesDeclaredStructuralPredicate,
  structuralEvidenceForAuthoring,
  structuralEvidenceForObjective,
  type AuthoredStructuralCondition,
  type DeclaredStructuralPredicateEvidence,
  type StructuralFeaturePredicateResult,
  type StructuralPredicateEvidencePayload,
  type StructuralPredicateResult,
  type StructuralPredicateTraceNode,
} from "./structural-evidence.js";
export {
  legIndexAt,
  trajectoryPolicyAt,
  trajectoryLegSpans,
  trajectoryVerdict,
  type TrajectoryLegOutcome,
  type TrajectoryLegSpan,
  type ResolvedTrajectoryPolicy,
  type TrajectoryTransition,
  type TrajectoryVerdict,
} from "./trajectory.js";
export {
  canonicalRunStart,
  digestSessionSource,
  isPackSession,
  sessionSource,
  type CreateRunSession,
  type PackRun,
  type SessionSource,
} from "./session.js";
export { attachEvidence } from "./evidence.js";
export {
  EVIDENCE_MANIFEST_ERROR_CODES,
  EvidenceManifestError,
  compileEvidenceManifest,
  evidenceForConsumer,
  assertConsumerEvidenceView,
  assertRenderedEvidenceView,
  renderEvidenceItems,
  type AdapterDeclaration,
  type AnswerDistance,
  type CompiledEvidenceManifest,
  type ConsumerDeclaration,
  type ConsumerEvidenceView,
  type DeclaredEvidence,
  type EvidenceBinding,
  type EvidenceContractDeclarations,
  type EvidenceDisposition,
  type EvidenceForm,
  type EvidenceGrounding,
  type EvidenceManifestErrorCode,
  type EvidenceEligibilityDeclaration,
  type EvidenceReasonDeclaration,
  type EvidenceSelectionPolicy,
  type EvidenceSelectionPolicyDeclaration,
  type EvidenceRenderer,
  type EvidenceRendererRegistry,
  type EvidencePlane,
  type EvidenceRole,
  type EvidenceTiming,
  type ProducerDeclaration,
  type ProjectionDeclaration,
  type ProviderOffBehavior,
  type RenderedEvidenceItem,
  type RenderedEvidenceView,
  type SemanticEventDeclaration,
  type SemanticEventSign,
  type VersionedEvidenceId,
} from "./evidence-contract.js";
export {
  CURRENT_CONSUMER_OPERATION_IDS,
  EVIDENCE_ADAPTERS,
  EVIDENCE_CONSUMER_IDS,
  EVIDENCE_CONSUMERS,
  EVIDENCE_CONTRACT_DECLARATIONS,
  EVIDENCE_PRODUCER_IDS,
  EVIDENCE_PRODUCERS,
  EVIDENCE_ELIGIBILITY_DECLARATIONS,
  EVIDENCE_REASON_DECLARATIONS,
  EVIDENCE_SELECTION_POLICIES,
  PRIMARY_EVIDENCE_MANIFEST,
  AVOIDANCE_EVENT_PROJECTION_IDS,
  CASTLING_EVENT_PROJECTION_IDS,
  SEMANTIC_EVENT_DECLARATIONS,
  SEMANTIC_EVENT_PROJECTION_IDS,
  STRUCTURAL_EVENT_FAMILIES,
  STRUCTURAL_EVENT_PROJECTION_IDS,
  STRUCTURAL_PREDICATE_PROJECTION_IDS,
  STRUCTURAL_READING_PROJECTION_IDS,
  TRANSITION_READING_PROJECTION_IDS,
  TRANSITION_EVENT_PROJECTION_IDS,
  TRANSITION_GEOMETRY_EVENT_FAMILIES,
  TRANSITION_RULE_EVENT_FAMILIES,
  TACTICAL_EVENT_PROJECTION_IDS,
} from "./evidence-catalog.js";
export {
  assertEvidenceSelectionResult,
  assertSemanticEvidenceEvent,
  canonicalMoveUci,
  castlingSemanticEvents,
  compileSemanticEvidenceEvent,
  legalAlternativeEdges,
  localSemanticEvents,
  selectLocalSemanticEvidence,
  selectSemanticEvidence,
  structuralSemanticEvents,
  tacticalSemanticEvents,
  transitionSemanticEvents,
  type CounterfactualAbsenceOperands,
  type EvidenceSelectionResult,
  type SelectedEvidenceFact,
  type SemanticEvidenceEvent,
  type SemanticEventAnchor,
  type SemanticEventInput,
  type SemanticSelectionInput,
  type StructuralSemanticEventOperands,
  type TransitionSemanticEventOperands,
  type TacticalSemanticEventOperands,
  type CastlingSemanticEventOperands,
} from "./semantic-evidence.js";
export {
  declareAuthoredClaimDeliveryEvidence,
  declareAuthoredClaimEvidence,
  declareAuthoredStructuralConditionEvidence,
  declareAvoidanceEvidence,
  declareCompareDerivedEvidence,
  declareEndgameReadingEvidence,
  declareEvidenceReferenceResolution,
  declareLegalExchangeEvidence,
  declareThreatEvidence,
  declareDoubleAttackEvidence,
  declareForkSurvivalEvidence,
  declareReplyBreadthEvidence,
  declareCheckEventEvidence,
  declareCastlingRightsEvidence,
  declareCastlingRightsLostEvidence,
  declareCastlingLegalityEvidence,
  declareExplorerPopulationEvidence,
  declareExplorerPositionEvidence,
  declareLivePacketEvidence,
  declareMaiaEventEvidence,
  declareMaiaPolicyEvidence,
  declareNamedStructureEvidence,
  declareOpponentProviderEvidence,
  declarePackPhaseEvidence,
  declarePhaseReadingEvidence,
  declarePivotalMarkerEvidence,
  declareRecordedEngineEvidence,
  declareRecordedTablebaseEvidence,
  declareRunRecordEvidence,
  declareShapeFiringSourceEvidence,
  declareSourcingRecordEvidence,
  declareStockfishEvalEvidence,
  declareStoryDerivedEvidence,
  declareStructuralPredicateFeatureEvidence,
  declareStructuralPredicateResultEvidence,
  declareStructuralReadingSourceEvidence,
  declareStructuralSemanticSourceEvidence,
  declareSyzygyResultEvidence,
  declareSyzygyCategoryEvidence,
  declareSyzygyDistanceEvidence,
  declareTransitionReadingSourceEvidence,
  declareTransitionSemanticSourceEvidence,
} from "./evidence-source-adapters.js";
export {
  RULES_EVIDENCE_FACTS,
  THEORY_EVIDENCE_FACTS,
  engineEvidenceRef,
  isEngineEvidenceRef,
  isMachineEvidenceRef,
  tablebaseEvidenceRef,
  packEvidenceRef,
  packAbsentEvidenceRef,
  rulesEvidenceRef,
  theoryEvidenceRef,
  tempoEvidenceRef,
  type EngineEvidenceRef,
  type PackEvidenceRef,
  type PackAbsentEvidenceRef,
  type RulesEvidenceFact,
  type RulesEvidenceRef,
  type TheoryEvidenceFact,
  type TheoryEvidenceRef,
  type TempoEvidenceRef,
} from "./evidence-ref.js";
export {
  consumeMoveTransition,
  consumePositionStructure,
  consumeSelectedSquareSight,
  declareStructuralReadingEvidence,
  declareTransitionReadingEvidence,
  moveTransitionEvidence,
  positionStructureEvidence,
  selectedSquareSightEvidence,
} from "./reading-evidence.js";
export {
  MATERIAL_VALUES,
  applyObjectiveEvidenceProposal,
  evaluateObjective,
  evaluateObjectivePredicate,
  materialBalance,
  requestObjectiveEvidence,
  transitionObjective,
  type FenPredicate,
  type MaterialBalancePredicate,
  type ObjectiveEvaluationResult,
  type ObjectiveEvidenceProposal,
  type ObjectiveEvidenceRequest,
  type ObjectiveEvidenceUpgrader,
  type ObjectivePredicate,
  type ObjectiveTransitionRule,
  type RulesFactPredicate,
} from "./objective.js";
export {
  ObjectiveEvidenceError,
  ObjectiveTransitionError,
  isObjectiveTransitionAllowed,
} from "./objective-state.js";
export { PgnExportError, exportPgn } from "./pgn.js";
export {
  PackRunPgnError,
  exportPackRunPgn,
  type PackRunPgnErrorCode,
} from "./pack-pgn.js";
export {
  ReplayError,
  opponentMovesFromEvents,
  readBackReplay,
  resistanceOnPath,
  type OpponentMoveReadback,
  type AppliedPolicyCount,
  type PathResistance,
  type RequestedLegPolicy,
  type ReadBackReplay,
  type ResistanceEngineCount,
} from "./replay.js";
export {
  appendOpponentPly,
  commitMove,
  createRun,
  fork,
  historyFrom,
  reachCheckpoint,
  rewind,
  rewindToCheckpoint,
  revealFeedback,
  type AppendOpponentPlyOptions,
  type CommitMoveOptions,
  type CreateRunInput,
  type LegacyCreateRunInput,
  type ForkOptions,
  type JobObserver,
} from "./runtime.js";
export type {
  Actor,
  Branch,
  BranchGroup,
  BranchGroupMember,
  CheckpointReachedEvent,
  Cursor,
  DrillRun,
  DrillRunEvent,
  EvidenceAttachedEvent,
  EvidenceKind,
  EvidencePayload,
  EvidenceSource,
  EventDraft,
  ExecutionLocus,
  MutationResult,
  Node,
  ObjectiveState,
  OpponentSelection,
  OpponentMoveSelectedEvent,
  PredictionRecordedEvent,
  ReasoningDetection,
  ReasoningRecordedEvent,
  ReasoningTranscript,
  GroupCreatedEvent,
  GroupResistance,
  GroupSource,
  PolicyConfig,
  PolicyModeApplied,
  PositionOpponentPolicy,
  RunFeedbackPolicy,
  RunOpponentMode,
  RunOpponentPolicy,
  RunOutcome,
  RunSessionKind,
  LiveSessionKind,
  MarkBrush,
  RunMark,
  RunStart,
  SelectionCandidate,
  SelectionEngineIdentity,
  Segment,
  VersionedPolicy,
} from "./types.js";
export { LIVE_SESSION_KINDS, MARK_BRUSHES, RUN_OPPONENT_MODES } from "./types.js";

export {
  EXCHANGE_PIECE_VALUES,
  LEGAL_EXCHANGE_CONVENTION,
  captureExchangeClass,
  exchangeCaptureAt,
  legalCaptureMovesTo,
  legalExchange,
  legalExchangeForMove,
  type CaptureExchangeClass,
  type ExchangePieceIdentity,
  type LegalExchangeBranch,
  type LegalExchangeResult,
  type LegalExchangeStep,
} from "./exchange.js";

export {
  REPLY_HORIZON,
  THREAT_CONVENTION,
  checkEvent,
  doubleAttackEvent,
  forkSurvivesReply,
  replyBreadth,
  threats,
  type CheckEvent,
  type DoubleAttackEvent,
  type DoubleAttackTarget,
  type ForkSurvivalResult,
  type ReplyBreadth,
  type Threat,
  type ThreatResult,
} from "./tactics.js";

export {
  castlingLegality,
  castlingRights,
  castlingRightsLost,
  type CastlingLegalityIssue,
  type CastlingRightLostEvent,
  type CastlingRightsState,
  type CastlingWing,
} from "./castling.js";

export const runtimeBuildInfo = Object.freeze({
  packageName: "@chess-tabiya/runtime",
  runSchemaVersion: DRILL_RUN_SCHEMA_VERSION,
});
