import { DRILL_RUN_SCHEMA_VERSION } from "@chess-tabiya/schema";

export { canonicalFen, transposeKey } from "./chess.js";
export {
  PROMOTION_ROLES,
  MOVE_DESTINATION_CONVENTION,
  MOVE_IDENTITY_CONVENTION,
  INBOUND_MOVE_DIALECT,
  exactLegalMoveMap,
  exactLegalMoves,
  exactMoveDestination,
  exactMoveIdentity,
  normalizeInboundMove,
  type ExactLegalMove,
  type ExactLegalMoveMap,
  type InboundMoveConversion,
  type InboundMoveSource,
  type PromotionRole as ExactPromotionRole,
} from "./legal-moves.js";
export {
  deviationAnchors,
  insideAuthoredBoundary,
  lineMembership,
  spineNodeIdFor,
  spinePositionIndex,
  type LineMembershipEntry,
  type LineVerdict,
} from "./line.js";
export { BranchQueryError, branchPath, branchPaths, resolveBranchPath, type BranchPathRefusalReason, type BranchPathResolution } from "./branch-path.js";
export {
  MAX_COMPARISON_BRANCHES,
  compareBranches,
  type BranchColumn,
  type BranchComparison,
  type BranchConsequence,
  type CheckpointHit,
  type ComparisonEvidenceEntry,
  type ComparisonLineEntry,
  type ComparisonRow,
  type ComparisonScore,
  type NodeRef,
  type ObjectiveTimelineEntry,
} from "./compare.js";
export { BRANCH_COLLAPSE_FLOOR, branchDecidedness, collapsedBranchIds, importedMainlineBranchId, renderCollapseExplanation, type AssessmentCategory, type AssessmentObjective, type CollapseExplanation, type Decidedness, type DecidednessGround, type TablebaseCategory as BranchTablebaseCategory } from "./branch-scale.js";
export { comparisonEngineTrajectory, comparisonNarrative, comparisonStrips, consumeComparisonEngineTrajectory, consumeComparisonStripEvidence, type BranchStrips, type ComparisonNarrative, type NarrativeGroup, type PieceRoute, type StripEntry } from "./compare-strips.js";
export {
  RuntimeError,
  assertActiveWriter,
  type IllegalMoveReason,
  type RuntimeErrorCode,
} from "./errors.js";
export { appendEvents, deriveSegments, eventsSince, groupsFromEvents, projectRun } from "./events.js";
export { feedbackDeliveryOpen, feedbackDisclosed } from "./feedback.js";
export { consumeShapeFiring, declareShapeFiringEvidence, renderShapeFiring, shapeFiringEvidence, shapeFirings, type ShapeFiring, type ShapeTriggerSource } from "./shape-firing.js";
export { classifyPhase, developmentReading, isDevelopmentHome, phaseBandReading, renderPhaseReading, PHASE_BAND_CONVENTION, type PhaseBandDecision, type PhaseBandReadingV2, DEVELOPMENT_CONVENTION, DEVELOPMENT_HOMES, ENDGAME_MATERIAL_MAX, DEVELOPED_MATERIAL_MIN, OPENING_UNDEVELOPED_MIN, MIDDLEGAME_UNDEVELOPED_MAX, PHASE_PROVENANCE, type DetectedPhase, type DevelopmentReading, type PhaseReading } from "./phase.js";
export { backRankReading, defenderDutyReading, defenderDutyRelocatedEvents, defenderRemovedEvents, discoveredExecutedEvents, discoveredLatencyReading, loosePieceEvents, loosePieceReading, mateInOne, overloadedDefenderResponseConflict, promotionPressureReading, rayClassificationReading, rookOnSeventhReading, trappedPieceReading, BACK_RANK_CONVENTION, DEFENCE_DUTY_CONVENTION, TRAPPED_CONVENTION, type BackRankReading, type DefenderDuty, type DefenderDutyReading, type DefenderDutyRelocatedEvent, type DefenderRemovedEvent, type DiscoveredExecutedEvent, type DiscoveredLatencyReading, type GainedSliderRay, type LoosePieceEvent, type LoosePieceEventResult, type LoosePieceReading, type LoosePieceState, type MateInOneReading, type OverloadedDefenderConflict, type OverloadedDefenderConflictResult, type PromotionAvailability, type PromotionPressureReading, type RayClassification, type RayClassificationKind, type RayClassificationReading, type RookOnSeventhReading, type TrappedPieceReading, type TrappedPieceState } from "./tactics.js";
export { forcedMateAfterMove, MATE_PROOF_CONVENTION, MATE_PROOF_NODE_CAP, type ForcedMateAfterMoveProof, type ForcedMateAfterMoveResult, type MateProofStatus } from "./mate-proof.js";
export {
  INSPECTOR_FAMILY_IDS,
  MODULE_ANSWER_CAPABILITIES,
  MODULE_ANSWER_CAPABILITY_IMAGE,
  MODULE_CONTRACT_ERROR_CODES,
  MODULE_FORM_IMAGE,
  MODULE_IDS,
  MODULE_TIMING_IMAGE,
  ModuleContractError,
  compileModuleRegistry,
  moduleAnswerImage,
  moduleEvidenceForms,
  moduleEvidenceTimings,
  type CompiledModuleRegistry,
  type InspectorFamilyId,
  type ModuleAcceptanceDeclaration,
  type ModuleAnswerCapability,
  type ModuleAnswerContract,
  type ModuleDependencyBlocker,
  type ModuleBudgets,
  type ModuleCeilings,
  type ModuleContractErrorCode,
  type ModuleDeclaration,
  type ModuleEmptyBehavior,
  type ModuleEvidenceClosure,
  type ModuleEvidenceDeclaration,
  type ModuleForm,
  type ModuleId,
  type ModuleInitiative,
  type ModuleSeatClass,
  type ModuleSelectionDeclaration,
  type ModuleTiming,
  type ModuleTimingDeclaration,
} from "./module-contract.js";
export { SILENT_ASSISTANCE, accessPermission, permittedAssistance, reviewingGrant, type AssistanceAccess, type AssistanceConfig, type AssistanceContext, type AssistancePermission } from "./assistance.js";
export {
  ASSISTANCE_FIELD_DOMAINS, ASSISTANCE_PREFERENCE_FIELDS, CLAMP_TOKENS, CONFIGURABLE_MODULE_IDS, EMPTY_MODULE_OVERRIDES, HINT_CEILING_TABLE,
  MODULE_PRESENTATION_FACTS, MODULE_PRESENTATION_SOURCE, PRESET_CONTRACT_ERROR_CODES, PRESET_DECLARATIONS, PRESET_IDS, WORKFLOW_CONTEXT_POLICIES, WORKFLOW_CONTEXTS,
  PreferenceParseError, PresetContractError, PresetRefusalError, assertPresetFoundation, clampFieldValue, contextClamp, deriveContextClamp, deriveModuleFieldCeiling,
  derivePresetProjection, deriveWorkflowContext, fieldRank, hintCeiling, parseWorkflowPreferenceV2, permissionCeiling, permissionToken, pointwiseMin, preferenceDisplayMode,
  preferenceReceipt, presetDeclaration, requestedAssistanceFields, requestedModules, requestedPreset, selectNamedPreset, serializeWorkflowPreferenceV2, setPreferenceField,
  setPreferenceModule, workflowContextPolicy,
  type AssistancePreferenceField, type AssistancePreferenceFields, type ConfigClamp, type ConfigurableModuleId, type ContextContract, type CustomModuleOverrides, type FieldValue,
  type ModulePresentationFacts, type OrdinaryWorkflowContextId, type OrdinaryWorkflowContextOrigin, type PresetContractErrorCode, type PresetDeclaration, type PresetId,
  type WorkflowContextId, type WorkflowContextPolicy, type WorkflowPreferenceReceipt, type WorkflowPreferenceV2,
} from "./presets.js";
export {
  ASSISTANCE_EXCHANGE_ERROR_CODES, ASSISTANCE_FIELD_EFFECT_ADAPTER, ASSISTANCE_FIELD_LABELS, CONTEXT_PHRASES, MODULE_EFFECT_CATALOG, MODULE_LABELS, MODULE_SOURCE_AUTHORITY,
  SERVER_EVIDENCE_SOURCES, SUPPRESSION_REASONS, SUPPRESSION_RENDERERS, AssistanceExchangeError, assistanceDigest, browserChannelReceipt, compileAssistanceRequest,
  compileAuthoritativeAssistance, compiledPresetDisclosure, effectSourceDependencies, finalizeAssistanceEffects, narrowBrowserChannels, parseFinalizedAssistanceV1,
  parseRequestedAssistanceV1, registryPresentationFacts, renderSuppression, serverAvailabilityFromProviders, sha256Hex,
  type AssistanceDigest, type AssistanceExchangeErrorCode, type AuthoritativeAssistanceV1, type AvailabilityState, type BrowserChannelReceiptV1, type BrowserNarrowedAssistanceV1,
  type CompiledAssistanceEffect, type FieldAdapterEntry, type FinalizedAssistanceV1, type HintCeilingReceipt, type LocalPreferenceInput, type ModuleSourceAuthority,
  type RequestedAssistanceV1, type SealedModuleSourceReceipts, type ServerAssistanceAuthority, type ServerEvidenceAvailabilityReceipt, type SuppressionReason, type SuppressionRecord,
  type CampaignWorkflowOrigin,
} from "./assistance-exchange.js";
export { MODULE_POLICIES, moduleConsumerCeilings, moduleEvidenceRole, modulePolicy, moduleSessions, type ModulePolicy } from "./module-policy.js";
export {
  GUIDED_HINT_DISCLOSURE,
  MODULE_AWAITING,
  MODULE_COVERAGE_REFUSALS,
  MODULE_DECLARATIONS,
  MODULE_OPERATIONS,
  MODULE_PAIR_EXECUTION,
  MODULE_REGISTRY,
  MODULE_SELECTION_POLICY,
  MODULE_UPSTREAM_DISCHARGES,
  ModuleRegistryInvariantError,
  ONE_EDGE_EVENT_REFS,
  assertModuleRegistry,
  blockedModules,
  moduleDeclaration,
  moduleEvidenceClosure,
  type ModuleOperation,
  type ModulePairExecution,
  type ModuleRegistryInvariantCode,
  type ModuleRegistryInvariantInput,
} from "./module-registry.js";
export { compileModulePacket, type ModulePacket, type ModulePacketRefusal, type ModulePacketRequest } from "./module-packets.js";
export {
  MODULE_QUERY_OPERATION, MODULE_QUERY_PROTOCOL, ModuleQueryError, fitModulePresentation, inspectorFamily, moduleDecisionStamp, moduleDisclosureDigest,
  moduleQueryProjections, parseModuleQueryRequest, passFen, queryModules, sightScope, witnessedEvidence,
  type InspectorFamilyState, type ModuleBudgetReceipt, type ModuleBudgetTuple, type ModuleDecisionStamp, type ModuleDisclosureReceipt, type ModuleEmptyState,
  type ModuleQueryErrorCode, type ModuleQueryInput, type ModuleQueryPacket, type ModuleQueryPage, type ModuleQueryRequest, type ModuleSourceContext,
  type ModuleSourceResult, type ModuleSuppressionReason,
} from "./module-query.js";
export { POSTCOMMIT_NUDGE_TEMPLATES, postcommitNudgePacket, type PostcommitNudgeFact, type PostcommitNudgeInput, type PostcommitNudgePacket } from "./postcommit-nudge.js";
export {
  ArrayReductionQualityRecorder,
  FACT_EQUIVALENCE_CLASSES,
  MODULE_REDUCER_VERSION,
  NULL_REDUCTION_QUALITY_RECORDER,
  SUBSUMPTION,
  admitModuleFacts,
  factIdentity,
  moduleFact,
  orderAdmittedFacts,
  reduceModulePacket,
  type ModuleFact,
  type ModuleReductionResult,
  type ReductionQualityObservation,
  type ReductionQualityRecorder,
} from "./module-reducers.js";
export {
  CAMPAIGN_ACT_IDS, CAMPAIGN_MODULE_REASONS, CAMPAIGN_REWIND_RESOURCE, CAMPAIGN_RUN_REWARD_KINDS, CAMPAIGN_THEORY_REASONS, CampaignModuleError,
  assertCampaignUnlockAllowed, campaignModuleCeiling, campaignModuleInventory, campaignModuleShelf, campaignRewardRef, campaignRewardRefKey,
  effectiveCampaignModules, isUnlockableModuleId, locateCampaignNodes,
  type CampaignAct, type CampaignActId, type CampaignBossGameEncounter, type CampaignDocument, type CampaignEconomy, type CampaignEncounter, type CampaignLayer,
  type CampaignModuleReason, type CampaignModuleShelfRow, type CampaignNode, type CampaignNodeReward, type CampaignPackEncounter, type CampaignRunReward,
  type CampaignRunRewardRef, type CampaignTheoryReason, type DurableCampaignReward, type DurableRewardGrant, type LocatedCampaignNode, type UnlockableModuleCount,
  type UnlockableModuleId,
} from "./campaign-contract.js";
export {
  CAMPAIGN_CHARGED_OPERATIONS, CAMPAIGN_EVENT_KINDS, CAMPAIGN_NODE_VERDICTS, CampaignStateError, campaignPrestigeEligible, campaignRunState, prestigeEligible,
  type CampaignActIncome, type CampaignActiveEncounter, type CampaignBossOutcome, type CampaignBossRatingDisposition, type CampaignBossTerminalReason,
  type CampaignChargedOperation, type CampaignCursor, type CampaignEvent, type CampaignEventKind, type CampaignEventPayloads, type CampaignNodeSeal,
  type CampaignNodeVerdict, type CampaignParticipationWitness, type CampaignRunState, type CampaignStateErrorCode, type ChargeLedgerEntry,
} from "./campaign-state.js";
export { deriveCampaignParticipationWitness, type CampaignBoundaryDefinition, type CampaignParticipationRefusal, type CampaignParticipationResult } from "./campaign-participation.js";
export {
  CampaignReceiptError, issueCampaignEncounterReceipt, verifyCampaignEncounterReceipt,
  type CampaignAssistanceSubject, type CampaignEncounterReceipt, type CampaignReceiptErrorCode,
} from "./campaign-receipt.js";
export { PIVOTAL_MARKER_ROUTES, consumePivotalMarkers, liveAdmitted, liveMarkers, pivotalMarkerEvidence, pivotalMarkerEvidenceItems, pivotalMarkers, renderPivotalMarker, type PivotalKind, type PivotalMarker, type IrreversibilityDetail, type PhaseChangeDetail, type DivergenceDetail, type CollapseDetail } from "./pivotal.js";
export {
  TRANSITION_FEATURE_KINDS,
  capturedRole,
  irreversibility,
  matchesTransitionExpression,
  matchesTransitionFeature,
  transitionFeatureKinds,
  transitionReading,
  transitionSemanticFacts,
  type TransitionObservation,
  type TransitionReading,
  type TransitionSemanticFact,
} from "./transition.js";
export { ENDGAME_CLASSIFICATION_CONVENTION, endgameClassification, renderEndgameClassification, type EndgameClassification, type EndgameTypeId } from "./endgame.js";
export { ENDGAME_CONVENTION_SOURCES, ENDGAME_SETUP_CONVENTIONS, endgameSetupConvention, endgameSetupMatch, endgameSetupMatches, renderEndgameSetupMatch, type EndgameConventionRef, type EndgameConventionSource, type EndgameSetupConvention, type EndgameSetupMatch, type EndgameSetupMatchResult, type EndgameTechnique } from "./endgame-setup.js";
export { ENDGAME_METHOD_CONVENTIONS, endgameMethodConvention, type EndgameMethodConvention, type MethodStage } from "./endgame-method.js";
export { retrospectivePivot } from "./adaptive.js";
export { STORY_MOMENT_KINDS, STORY_PIVOT_CP, evidenceGroundingLabel, parseReviewStoryReceipt, projectPublicReviewStory, rankStoryMoments, renderReviewStoryComponents, renderReviewStoryReceipt, reviewStoryMoments, storyDeclaredEvidence, storyMomentsForRun, storyEvidenceSourceLabels, suggestTitle, type ParsedReviewStory, type PublicReviewStoryReceipt, type ReviewStoryMomentReceipt, type ReviewStoryReceipt, type StoryMoment, type StoryMomentKind, type StoryProjection, type StoryTitleInput } from "./story.js";
export {
  CLAIM_EVIDENCE_TYPE_LABELS, SIDE_LABELS, type ClaimEvidenceType, type LabelVocabularyMembers, type ReviewSide,
  COMPONENT_DECLARATIONS, COMPONENT_IDS, GROUNDING_LABELS, LABEL_VOCABULARIES, OBJECTIVE_STATE_LABELS, PRESENTATION_ADAPTERS, PRESENTATION_CONVENTIONS,
  PRESENTATION_QUESTIONS, PRESENTATION_SELECTION_ONLY, PRESENTATION_SOURCE_REASONS, PresentationError, RECORDED_RELATION_LABELS, RUN_OUTCOME_LABELS,
  assertPresentationText, assertPresentedEvidenceItem, citationFromEvidence, isPresentedAbstention, parsePresentationReceipt, presentEvidenceItems,
  presentScore, presentSearchBound, presentationAdapter, presentationDigest, presentedSentence, serializePresentedEvidence,
  type AbstentionOperand, type CitationOperand, type ClaimOperand, type ComponentDeclaration, type ComponentId, type ComponentValue, type ConventionReceipt,
  type EnumStateOperand, type FactStatementOperand, type LabelEntry, type LabelVocabulary, type MagnitudeOperand, type PresentationReceipt,
  type PresentedEvidenceItem, type ProjectionPresentationAdapter,
  BOARD_RELATION_KINDS, DENOMINATOR_MEANINGS, DISTRIBUTION_RESIDUAL_LABELS, MAGNITUDE_SCALE_POLICIES, RELATION_PHRASES, STRUCTURED_DOCUMENT_SCHEMAS,
  adapterComponents, componentValueSentence, conventionAttribution, factStatementOperand, formatShare, parseComponentValue,
  type AdapterSpec, type BoardRelationKind, type ConventionBasis, type CountWithDenominatorOperand, type DistributionOperand, type MagnitudeScalePolicyId,
  type MagnitudeTrailOperand, type MovePathOperand, type OutcomeSplitOperand, type PopulationDescriptor, type PresentationComposition, type PresentationKit,
  type RelationOverlayOperand, type SquareSetOperand, type StructuredDocumentOperand,
} from "./presentation-contract.js";
export {
  REVIEW_PACKET_SOURCE_ADAPTERS, REVIEW_PACKET_SOURCE_PROJECTION_IDS, REVIEW_SOURCE_FAMILIES, REVIEW_UNAVAILABLE_REASONS, ReviewEvidenceError,
  REVIEW_PROVIDER_DELIVERY_KEY, REVIEW_PROVIDER_LINE_KEY, reviewDurableEngineLine, assertReviewEvidencePacket, assertReviewRecordedPrefixReceipt, reviewDeliveryEvidencePayload, reviewDurableEngineStates, reviewPacketForRun, compileReviewEvidence, compileReviewPacketForSubject, createReviewPrefixAuthority,
  foldReviewCompletion, foldReviewFamilyState, presentReviewFamilyAbstentions, reviewPacketSourcePlan, reviewSubjectPath, runReviewPacketSources,
  type ReviewAdapterState, type ReviewDegradation, type ReviewEvidenceInput, type ReviewEvidencePacket, type ReviewImportRecordImage, type ReviewNodePacket,
  type ReviewOutcomeReceipt, type ReviewProgress, type ReviewProviderNodeState, type ReviewRecordedPrefixReceipt, type ReviewRunFamilyState,
  type ReviewSourceContext, type ReviewSourceFamily, type ReviewStorageAuthority, type ReviewUnavailableReason,
} from "./review-evidence.js";
export {
  MATE_TRANSITION_KINDS, learnerCentipawns, mateTransitionChanges, reviewPointComparability, reviewScoreReceipt, searchCommandImage, whiteWdl,
  type ForcedMateAfterMoveProofV2, type RecordedPosition, type ReviewEnginePoint, type ReviewEvalDelta, type ReviewMateTransition, type ReviewScoreReceipt,
  type ReviewWdlPoint, type StockfishPositionEvaluation, type StockfishPrincipalVariation, type WhiteWdlPoint,
} from "./review-points.js";
export {
  voiceCheck,
  renderRecordedReading,
  BANNED_JUDGEMENTS,
  PRESCRIPTIVE_VERBS,
  CHESS_LEXICON,
  type EngineReadingValues,
  type EvidencePacket,
  type PositionEvidenceIndex,
  type RecordedReading,
  type ShapeEntryRef,
  type TablebaseReadingValues,
  type VoiceCheckResult,
} from "./voice.js";
export { matchKeyPoints, normalizeReasoningText } from "./reasoning.js";
export { terminalOutcome } from "./outcome.js";
export {
  FLOAT32_POLICY_MASS_TOLERANCE,
  PolicyMassError,
  humanConcessionMass,
  type HumanConcessionMass,
  type PolicyMassCandidate,
} from "./practical-difficulty.js";
export {
  AUTHORABLE_TEMPO_VERDICTS,
  DECLARED_UNGRADEABLE_VERDICTS,
  TEMPO_GRADEABLE_VERDICTS,
  TEMPO_VERDICTS,
  UNAUTHORED_TEMPO_DEFAULTS,
  tempoMovesFromRun,
  unauthoredTempoTransition,
  windowStates,
  type TempoMove,
  type TempoVerdict,
  type TimingWindowState,
  type TriggerResolver,
} from "./tempo.js";
export {
  CORPUS_POPULATION_SOURCE,
  CORPUS_RESULT_ABSTENTION_REASONS,
  isCorpusResultAbstentionReason,
  parseCorpusResultAbstention,
  type CorpusAbstentionResult,
  type CorpusMoveRow,
  type CorpusPopulation,
  type CorpusResult,
  type CorpusResultAbstentionReason,
  type CorpusStatsResult,
} from "./corpus-result.js";
export {
  SOURCE_ATTRIBUTION_ABSENT_REASON,
  SOURCE_ATTRIBUTION_MISSING_METADATA_POLICY,
  SOURCE_ATTRIBUTION_REGISTRY_ID,
  SOURCE_ATTRIBUTION_REGISTRY_IMAGE,
  SOURCE_ATTRIBUTION_REGISTRY_RESOURCE,
  SOURCE_ATTRIBUTION_REGISTRY_VERSION,
  SOURCE_ATTRIBUTION_RESOLVER,
  SOURCE_DEPLOYMENT_ARTIFACT_IDS,
  SOURCE_DEPLOYMENT_RECEIPT_FIELDS,
  SOURCE_REMOTE_ENDPOINT_IDS,
  isParsedSourceAttributionRegistryImage,
  parseSourceAttributionRegistryImage,
  resolveSourceAttribution,
  sourceAttributionRegistryDigest,
  type AbsentSourceAttribution,
  type ParsedSourceAttributionRegistryImage,
  type ResolvedSourceAttribution,
  type SourceAttributionFieldResolver,
  type SourceAttributionReceipt,
  type SourceAttributionRegistryImage,
  type SourceAttributionRegistryRow,
  type SourceAttributionResolution,
  type SourceAttributionValue,
  type SourceDeploymentArtifactId,
  type SourceDeploymentReceiptField,
  type SourceMetadataAuthority,
  type SourceRemoteEndpointId,
} from "./source-attribution.js";
export {
  STRUCTURAL_FEATURE_KINDS,
  STRUCTURE_PREDICATES,
  emptyBoardDistance,
  evaluateNamedStructureWithWitness,
  evaluateStructuralExpressionWithWitness,
  matchesStructuralExpression,
  matchesStructuralFeature,
  mirrorExpression,
  observationIdentity,
  pawnConnectivityReading,
  pawnSafety,
  renderStructuralObservationChange,
  spaceReading,
  SPACE_CONVENTION,
  structuralDelta,
  structuralFeatureKinds,
  structuralReading,
  vacationReading,
  type FeatureComparison,
  type DistanceRole,
  type DistanceTarget,
  type FileRange,
  type FileTemplateFeature,
  type MirrorAxis,
  type PawnSafety,
  type PawnConnectivityColorReading,
  type PawnConnectivityReading,
  type ReachRole,
  type ReachScope,
  type Quantifier,
  type RankRange,
  type SquareRegion,
  type SquareTemplateFeature,
  type SpaceReading,
  type SpaceZone,
  type StructuralDelta,
  type StructuralExpression,
  type StructuralExpressionWitness,
  type StructuralFeature,
  type StructuralFeatureKind,
  type StructuralObservation,
  type StructuralReading,
  type StructureId,
  type StructureMatch,
  type VacationReading,
} from "./structure.js";
export {
  declareStructuralPredicateEvidence,
  evaluateAuthoredStructuralPredicate,
  evaluateStructuralPredicate,
  matchesDeclaredStructuralPredicate,
  structuralEvidenceForAuthoring,
  structuralEvidenceForObjective,
  type AuthoredStructuralCondition,
  type DeclaredStructuralPredicateEvidence,
  type StructuralFeaturePredicateResult,
  type StructuralPredicateEvidencePayload,
  type StructuralPredicateResult,
  type StructuralPredicateTraceNode,
} from "./structural-evidence.js";
export {
  legIndexAt,
  trajectoryPolicyAt,
  trajectoryLegSpans,
  trajectoryVerdict,
  type TrajectoryLegOutcome,
  type TrajectoryLegSpan,
  type ResolvedTrajectoryPolicy,
  type TrajectoryTransition,
  type TrajectoryVerdict,
} from "./trajectory.js";
export {
  canonicalRunStart,
  digestSessionSource,
  isPackSession,
  sessionSource,
  type CreateRunSession,
  type PackRun,
  type SessionSource,
} from "./session.js";
export { attachEvidence } from "./evidence.js";
export {
  attachedPacketEvidence,
  candidateFeatureVectorEvidence,
  claimDeliveryEvidence,
  corpusPageEvidence,
  corpusPositionEvidence,
  evidenceReferenceEvidence,
  guardConditionEvidence,
  humanSplitPageEvidence,
  opponentProviderEvidence,
  packConceptReferenceEvidence,
  positionGuidanceEvidence,
  providerSourceEvidence,
  recordedEdgeEvidence,
  recordedReadingEvidence,
  sourcingRecordEvidence,
  syzygyTablebaseDomainEvidence,
  type PackConceptReferencePayload,
  type PositionGuidanceEvidenceInput,
} from "./evidence-operations.js";
// rfc/provider-exchange-and-execution.md: shared provider exchange types, request identity,
// receipts and the durable boundary. The scheduler-only constructors are NOT exported here; they
// live behind a dedicated scheduler-only subpath (census in provider-protocol.test.ts).
export * from "./provider-types.js";
export {
  PROVIDER_DIGEST_DOMAINS,
  canonicalProviderJson,
  digestEngineBinary,
  digestEngineContainer,
  digestEngineOptionImage,
  digestProviderCommands,
  digestProviderPath,
  digestProviderPending,
  digestProviderResponse,
  digestProviderRetained,
  providerUtf8,
  type EngineBinaryDigest,
  type EngineContainerDigest,
  type EngineContainerImage,
  type EngineOptionImage,
  type EngineOptionImageDigest,
  type ProviderActualDigest,
  type ProviderCacheIdentity,
  type ProviderCommandsDigest,
  type ProviderDigestDomain,
  type ProviderPendingDigest,
  type ProviderRequestDigest,
  type ProviderResponseDigest,
  type ProviderRetainedDigest,
} from "./provider-digest.js";
export {
  MAX_PRINCIPAL_VARIATION_PLIES,
  PROVIDER_REQUEST_NORMALIZERS,
  ProviderRequestInvalid,
  STOCKFISH_RESET_COMMANDS,
  explorerRequestUrl,
  maiaCommandImage,
  maiaReachedFen,
  normalizeProviderRequest,
  syzygyPieceCount,
  syzygyPreflight,
  syzygyRequestUrl,
} from "./provider-requests.js";
export { PROVIDER_RESPONSE_PARSERS, ProviderResponseInvalid, type ProviderResponseParser, type ProviderResponseParsers } from "./provider-parsers.js";
export { IMPORT_SOURCE_KINDS, IMPORT_SOURCE_PROTOCOL_MEMBERS, IMPORT_SOURCE_REQUEST_KINDS, isImportSourceKind, isImportSourceRequestKind, type ImportSourceKind, type ImportSourceProtocolMember, type ImportSourceRequestKind } from "./import-source-protocol.js";
export { PROVIDER_OPERATION_IDS, PROVIDER_PROTOCOL_MEMBERS, PROVIDER_PROTOCOL_RESOURCE, providerProtocolMember, providerProtocolRow, type ProviderCliName, type ProviderProtocolMember, type ProviderProtocolOperationRow } from "./provider-protocol.js";
export {
  PERSISTED_PROVIDER_DELIVERY_SCHEMA,
  ProviderIdentityMismatch,
  ProviderSealRefused,
  assertProviderAcquisitionReceipt,
  assertProviderDelivery,
  assertProviderLocalDomainResult,
  assertProviderParsedPayloadReceipt,
  cacheIdentityOf,
  digestProviderActual,
  digestProviderRequest,
  isCanonicalUtcIso,
  normalizedProviderRequestDigest,
  parsePersistedProviderDelivery,
  parserImplementationDigest,
  pendingKeyOf,
  providerOf,
  retainedIdentityOf,
  serializeProviderDelivery,
  type PersistedProviderDelivery,
} from "./provider-exchange.js";
export type { AuthoredFeedbackItemRecord, EvidenceAvailability } from "./evidence-factories.js";
export { RECORDED_ASSESSMENT_CATEGORIES, recordedReadingFromLedgerRecord, type SourcingLedgerRecord } from "./recorded-reading.js";
export { evidenceSentenceTable, resolveEvidenceReference, type EvidenceReferenceResolution, type EvidenceSentence } from "./evidence-ref-resolution.js";
export { candidateCollectorIds, type CandidateCollectorResult, type CandidateFeatureInput, type CandidateFeatureRow, type CandidateFeatureVector } from "./candidate-feature-vector.js";
export {
  CANDIDATE_EVENTS_SCOPE,
  CANDIDATE_PACKET_COMPILER_VERSION,
  CANDIDATE_PACKET_LEGAL_CONVENTION,
  CANDIDATE_READINGS_SCOPE,
  CANDIDATE_WIDE_SCOPE,
  CandidatePacketMoveError,
  LOCAL_CANDIDATE_EVENT_PROJECTION_KEYS,
  LOCAL_CANDIDATE_READING_PROJECTION_KEYS,
  assertCandidatePacketEvent,
  assertCandidatePacketProjection,
  assertCandidatePopulationReceipt,
  candidateAlternatives,
  candidateChildReadings,
  candidatePacketId,
  candidatePlayedRow,
  compileCandidatePopulation,
  projectCandidatePopulationReceipt,
  type CandidateCollectorProjection,
  type CandidateEventPopulation,
  type CandidateEventRow,
  type CandidateEventsScope,
  type CandidatePacketAbstention,
  type CandidatePacketIdentity,
  type CandidatePacketScope,
  type CandidatePacketScopeMember,
  type CandidatePopulationCompileResult,
  type CandidatePopulationFailure,
  type CandidatePopulationProjectionResult,
  type CandidatePopulationReceipt,
  type CandidatePopulationRequest,
  type CandidateReadingsScope,
  type CandidateWideScope,
  type ProjectableCandidateScope,
  type SealedCandidateCollectorOutcome,
} from "./candidate-population.js";
export {
  GRADE_CONVENTION,
  assertMoveQualityGradeSentence,
  moveQualityGrade,
  renderMoveQualityGrade,
  renderMoveQualityResult,
  winPercentFromCp,
  type AbstainedGradeEvaluation,
  type CitedGradeConstant,
  type GradeContext,
  type GradeEvaluation,
  type GradeLane,
  type GradeScore,
  type GradeSide,
  type MoveQualityAbstention,
  type MoveQualityAbstentionReason,
  type MoveQualityArm,
  type MoveQualityClass,
  type MoveQualityGrade,
  type MoveQualityResult,
} from "./grade.js";
export {
  EVIDENCE_MANIFEST_ERROR_CODES,
  EvidenceManifestError,
  compileEvidenceManifest,
  evidenceForConsumer,
  evidenceConsumerOperation,
  assertEvidenceConsumerOperations,
  assertConsumerEvidenceView,
  assertRenderedEvidenceView,
  renderEvidenceItems,
  type AdapterDeclaration,
  type AnswerDistance,
  type CompiledEvidenceManifest,
  type ConsumerDeclaration,
  type ConsumerEvidenceView,
  type DeclaredEvidence,
  type EvidenceBinding,
  type EvidenceContractDeclarations,
  type EvidenceConsumerOperation,
  type EvidenceDisposition,
  type EvidenceDerivation,
  type EvidenceForm,
  type EvidenceGrounding,
  type EvidenceManifestErrorCode,
  type EvidenceEligibilityDeclaration,
  type EvidenceReasonDeclaration,
  type EvidenceSelectionPolicy,
  type EvidenceSelectionPolicyDeclaration,
  type EvidenceRenderer,
  type EvidenceRendererRegistry,
  type EvidencePlane,
  type EvidenceRole,
  type EvidenceTiming,
  type ProducerDeclaration,
  type ProjectionDeclaration,
  type ProviderOffBehavior,
  type RenderedEvidenceItem,
  type RenderedEvidenceView,
  type SemanticEventDeclaration,
  type SemanticEventSign,
  type VersionedEvidenceId,
} from "./evidence-contract.js";
export { RUNTIME_EVIDENCE_CONSUMER_OPERATIONS } from "./evidence-consumer-operations.js";
export {
  CURRENT_CONSUMER_OPERATION_IDS,
  EVIDENCE_ADAPTERS,
  EVIDENCE_CONSUMER_IDS,
  EVIDENCE_MODULE_IDS,
  MODULE_CONSUMER_ACCEPTS,
  MODULE_CONSUMER_IDS,
  MODULE_CONSUMER_IMPLEMENTATION,
  MODULE_SUCCESSOR_REBASE,
  RECORDED_PATH_SUCCESSOR_REFS,
  WAVE_C_MODULE_PROJECTION_REFS,
  type EvidenceModuleId,
  EVIDENCE_CONSUMERS,
  EVIDENCE_CONTRACT_DECLARATIONS,
  EVIDENCE_PRODUCER_IDS,
  EVIDENCE_PRODUCERS,
  EVIDENCE_ELIGIBILITY_DECLARATIONS,
  EVIDENCE_REASON_DECLARATIONS,
  EVIDENCE_SELECTION_POLICIES,
  PRIMARY_EVIDENCE_MANIFEST,
  AVOIDANCE_EVENT_PROJECTION_IDS,
  TACTICAL_AVOIDANCE_EVENT_PROJECTION_IDS,
  BREADTH_COLLECTOR_PROJECTION_IDS,
  BREADTH_CONVENTION_TEXT,
  BREADTH_EVENT_PROJECTION_IDS,
  CASTLING_EVENT_PROJECTION_IDS,
  SEMANTIC_EVENT_DECLARATIONS,
  SEMANTIC_EVENT_FAMILY_IDS,
  SEMANTIC_EVENT_PROJECTION_REFS,
  SEMANTIC_CONVENTION_TEXT,
  SEMANTIC_WAVE_EVENT_PROJECTION_IDS,
  STRUCTURAL_EVENT_FAMILIES,
  STRUCTURAL_EVENT_PROJECTION_IDS,
  STRUCTURAL_PREDICATE_PROJECTION_IDS,
  STRUCTURAL_READING_PROJECTION_IDS,
  TACTICAL_COLLECTOR_PROJECTION_IDS,
  TRANSITION_READING_PROJECTION_IDS,
  TRANSITION_EVENT_PROJECTION_IDS,
  TRANSITION_GEOMETRY_EVENT_FAMILIES,
  TRANSITION_RULE_EVENT_FAMILIES,
  TACTICAL_EVENT_PROJECTION_IDS,
} from "./evidence-catalog.js";
export {
  assertEvidenceSelectionResult,
  assertSemanticEvidenceEvent,
  breadthSemanticEvents,
  canonicalMoveUci,
  capturedZoneDefenderOperands,
  checkSemanticEvent,
  checkZwischenzugObservedOperands,
  checkZwischenzugSemanticEvent,
  castlingSemanticEvents,
  compileSemanticEvidenceEvent,
  defenderConsequenceOperands,
  defenderConsequenceSemanticEvent,
  defenderExposureOperands,
  deflectionObservedOperands,
  deflectionObservedInduction,
  deflectionObservedSemanticEvent,
  harassmentPressureSemanticEvent,
  interferenceObservedOperands,
  interferenceSemanticEvent,
  legalAlternativeEdges,
  localSemanticEventClosure,
  localSemanticEvents,
  lineBlockerClearanceObservedOperands,
  lineBlockerClearanceSemanticEvent,
  loosePieceSemanticEvents,
  pawnIslandSemanticEvents,
  pawnContactTimingSemanticEvent,
  overloadExploitationObservedOperands,
  overloadExploitationSemanticEvent,
  semanticDutyEvents,
  squareClearanceObservedOperands,
  squareClearanceSemanticEvent,
  attractionObservedOperands,
  attractionObservedSemanticEvent,
  discoveredExecutedSemanticEvents,
  derivedExchangeSemanticEvents,
  tradeCompletedSemanticEvent,
  openFileOccupancyOperands,
  selectLocalSemanticEvidence,
  selectSemanticEvidence,
  structuralSemanticEvents,
  tacticalSemanticEvents,
  transitionSemanticEvents,
  type CounterfactualAbsenceOperands,
  type CapturedZoneDefenderOperands,
  type DefenderConsequenceOperands,
  type DeflectionObservedInduction,
  type DeflectionObservedOperands,
  type AttractionObservedOperands,
  type LineBlockerClearanceObservedOperands,
  type SquareClearanceObservedOperands,
  type InterferenceObservedOperands,
  type CheckZwischenzugObservedOperands,
  type OverloadExploitationObservedOperands,
  type DefenderExposureOperands,
  type EvidenceSelectionResult,
  type SelectedEvidenceFact,
  type SemanticEvidenceEvent,
  type SemanticEventAnchor,
  type SemanticEventInput,
  type SemanticSelectionInput,
  type LocalSemanticEventAbstention,
  type LocalSemanticEventClosure,
  type StructuralSemanticEventOperands,
  type TransitionSemanticEventOperands,
  type TacticalSemanticEventOperands,
  type CastlingSemanticEventOperands,
  type DerivedExchangeSemanticEventOperands,
  type PawnIslandEventOperands,
  type OpenFileOccupancyOperands,
  type TradeCompletedEventOperands,
} from "./semantic-evidence.js";
export {
  RecordedEdgeError,
  assertRecordedEdgeEvidence,
  type RecordedEdge,
  type RecordedEdgeRefusalReason,
} from "./recorded-edge.js";
export {
  recordedAttractionObservedSemanticEvent,
  recordedCheckZwischenzugSemanticEvent,
  recordedDefenderConsequenceSemanticEvent,
  recordedDeflectionObservedSemanticEvent,
  recordedHarassmentPressureSemanticEvent,
  recordedInterferenceSemanticEvent,
  recordedLineBlockerClearanceSemanticEvent,
  recordedOverloadExploitationSemanticEvent,
  recordedPawnContactTimingSemanticEvent,
  recordedSquareClearanceSemanticEvent,
  recordedTradeCompletedSemanticEvent,
} from "./semantic-evidence.js";
export {
  recordedSemanticPath,
  recordedSemanticPathExecution,
  type RecordedPathConventionReceipt,
  type RecordedPathRefusalReason,
  type RecordedPathWindowReceipt,
  type RecordedSemanticPathExecution,
  type RecordedSemanticPathResult,
} from "./recorded-semantic-path.js";
export {
  RULES_EVIDENCE_FACTS,
  THEORY_EVIDENCE_FACTS,
  engineEvidenceRef,
  isEngineEvidenceRef,
  isMachineEvidenceRef,
  tablebaseEvidenceRef,
  packEvidenceRef,
  packAbsentEvidenceRef,
  rulesEvidenceRef,
  theoryEvidenceRef,
  tempoEvidenceRef,
  type EngineEvidenceRef,
  type PackEvidenceRef,
  type PackAbsentEvidenceRef,
  type RulesEvidenceFact,
  type RulesEvidenceRef,
  type TheoryEvidenceFact,
  type TheoryEvidenceRef,
  type TempoEvidenceRef,
} from "./evidence-ref.js";
export {
  consumeMoveTransition,
  consumePositionStructure,
  consumeSelectedSquareSight,
  declareStructuralReadingEvidence,
  declareTransitionReadingEvidence,
  moveTransitionEvidence,
  positionStructureEvidence,
  selectedSquareSightEvidence,
} from "./reading-evidence.js";
export {
  MATERIAL_VALUES,
  applyObjectiveEvidenceProposal,
  evaluateObjective,
  evaluateObjectivePredicate,
  materialBalance,
  materialBalanceAt,
  requestObjectiveEvidence,
  transitionObjective,
  type FenPredicate,
  type MaterialBalancePredicate,
  type ObjectiveEvaluationResult,
  type ObjectiveEvidenceProposal,
  type ObjectiveEvidenceRequest,
  type ObjectiveEvidenceUpgrader,
  type ObjectivePredicate,
  type ObjectiveTransitionRule,
  type RulesFactPredicate,
} from "./objective.js";
export {
  ObjectiveEvidenceError,
  ObjectiveTransitionError,
  isObjectiveTransitionAllowed,
} from "./objective-state.js";
export { PgnExportError, exportPgn } from "./pgn.js";
export {
  PackRunPgnError,
  exportPackRunPgn,
  type PackRunPgnErrorCode,
} from "./pack-pgn.js";
export {
  ReplayError,
  opponentMovesFromEvents,
  readBackReplay,
  resistanceOnPath,
  type OpponentMoveReadback,
  type AppliedPolicyCount,
  type PathResistance,
  type RequestedLegPolicy,
  type ReadBackReplay,
  type ResistanceEngineCount,
} from "./replay.js";
export {
  appendOpponentPly,
  commitMove,
  createRun,
  fork,
  historyFrom,
  reachCheckpoint,
  rewind,
  rewindToCheckpoint,
  revealFeedback,
  type AppendOpponentPlyOptions,
  type CommitMoveOptions,
  type CreateRunInput,
  type LegacyCreateRunInput,
  type ForkOptions,
  type JobObserver,
} from "./runtime.js";
export type {
  Actor,
  Branch,
  BranchGroup,
  BranchGroupMember,
  CheckpointReachedEvent,
  Cursor,
  DrillRun,
  DrillRunEvent,
  EvidenceAttachedEvent,
  EvidenceKind,
  EvidencePayload,
  EvidenceSource,
  EventDraft,
  ExecutionLocus,
  MutationResult,
  Node,
  ObjectiveState,
  OpponentSelection,
  OpponentSelectionPolicy,
  OpponentMoveSelectedEvent,
  PredictionRecordedEvent,
  ReasoningDetection,
  ReasoningRecordedEvent,
  ReasoningTranscript,
  GroupCreatedEvent,
  GroupResistance,
  GroupSource,
  PolicyConfig,
  PolicyModeApplied,
  PositionOpponentPolicy,
  RunFeedbackPolicy,
  RunOpponentMode,
  RunOpponentPolicy,
  RunOutcome,
  RunSessionKind,
  LiveSessionKind,
  MarkBrush,
  RunMark,
  RunStart,
  SelectionCandidate,
  SelectionEngineIdentity,
  Segment,
  VersionedPolicy,
} from "./types.js";
export { LIVE_SESSION_KINDS, MARK_BRUSHES, RUN_OPPONENT_MODES } from "./types.js";

export {
  EXCHANGE_PIECE_VALUES,
  LEGAL_EXCHANGE_CONVENTION,
  captureClassEvent,
  captureExchangeClass,
  exchangeCaptureAt,
  legalCaptureMovesTo,
  legalExchange,
  legalExchangeForMove,
  type CaptureExchangeClass,
  type CaptureClassEvent,
  type ExchangePieceIdentity,
  type LegalExchangeBranch,
  type LegalExchangeResult,
  type LegalExchangeStep,
} from "./exchange.js";

export {
  REPLY_HORIZON,
  THREAT_CONVENTION,
  checkEvent,
  doubleAttackEvent,
  forkSurvivesReply,
  replyBreadth,
  threats,
  type CheckEvent,
  type DoubleAttackEvent,
  type DoubleAttackTarget,
  type ForkSurvivalResult,
  type ReplyBreadth,
  type Threat,
  type ThreatResult,
} from "./tactics.js";

export {
  castlingLegality,
  castlingRights,
  castlingRightsLost,
  type CastlingLegalityIssue,
  type CastlingRightLostEvent,
  type CastlingRightsState,
  type CastlingWing,
} from "./castling.js";

export {
  squareControlEvents,
  squareControlReading,
  type ControlledSquare,
  type LegalControlSet,
  type SquareControlEvent,
  type SquareControlEvents,
  type SquareController,
  type SquareControlReading,
} from "./square-control.js";

export {
  LOCAL_NON_LOSING_CONVENTION,
  legalMovesReading,
  pieceDestinationEvents,
  pieceDestinationsReading,
  type ColorPieceDestinations,
  type PieceDestinations,
  type PieceDestinationsEvent,
  type PieceDestinationsEventResult,
  type PieceDestinationsReading,
  type LegalMovesReading,
} from "./mobility.js";

export {
  CANDIDATE_MAJORITY_CONVENTION,
  RACE_ARRIVAL_CONVENTION,
  candidateMajorityReading,
  harassmentPressureSequence,
  pawnContactTimingSequence,
  pawnContactsReading,
  pawnDynamicsEvents,
  pawnTransitionEvents,
  promotionRaceGeometry,
  promotionRaceTablebase,
  type BoardPieceIdentity,
  type CandidateMajorityReading,
  type HarassmentPressureSequence,
  type PawnContactTimingSequence,
  type PawnContactsReading,
  type PawnDynamicsEvent,
  type PawnTransitionEvent,
  type PawnIdentity,
  type PromotionRacePawn,
  type PromotionRaceGeometry,
  type PromotionRaceGeometryResult,
  type PromotionRaceTablebaseInput,
  type PromotionRaceTablebaseEvent,
  type PromotionRaceTablebaseResult,
  type PressureLine,
  type RecordedMoveAnchor,
} from "./pawn-dynamics.js";

export {
  KING_SHELTER_CONVENTION,
  KING_ZONE_CONVENTION,
  kingZoneEvents,
  kingZoneReading,
  type KingEscapeSet,
  type KingZoneEvent,
  type KingZoneParticipant,
  type KingZoneReading,
  type KingZoneState,
} from "./king-state.js";

export {
  MATERIAL_ROLE_SIGNATURE_CONVENTION,
  isMaterialRole,
  materialRoleAsymmetryEvent,
  materialRoleSignatureReading,
  type MaterialRole,
  type MaterialRoleAsymmetryEvent,
  type MaterialRoleSignatureReading,
  type MaterialRoleVector,
} from "./material-state.js";

export { CORPUS_GUARD } from "./population-guard.js";

export const runtimeBuildInfo = Object.freeze({
  packageName: "@chess-tabiya/runtime",
  runSchemaVersion: DRILL_RUN_SCHEMA_VERSION,
});
export {
  REVIEW_MAP_CONVENTION,
  REVIEW_MOMENT_BUDGET,
  reviewMapProjection,
  selectReviewMoments,
  type ReviewAccuracy,
  type ReviewMapContext,
  type ReviewMapGrade,
  type ReviewMapInput,
  type ReviewMapMoment,
  type ReviewMapProjection,
  type ReviewMapRow,
  type ReviewMomentSelection,
  REVIEW_COMPARE_LIMIT,
  openRetryEntry,
  type ReviewCompareDoor,
  type ReviewEvalGap,
  type ReviewEvalGraph,
  type ReviewEvalPoint,
} from "./review-map.js";
export { reviewAnalysis, type ReviewAnalysis } from "./review-analysis.js";
export { REVIEW_MAP_TEMPLATES, reviewText, type ReviewTemplateId } from "./review-map-templates.js";
export { judgementWordsOutsideGrounding, ungroundedResidue } from "./voice.js";
export {
  BOT_CARD_SOURCE_IDS,
  BOT_CARD_STATEMENT_IDS,
  BOT_CLASSIFIER_IDS,
  BOT_DEGRADATION_REASONS,
  BOT_FAMILY_LABELS,
  BOT_FAMILY_LAYERS,
  BOT_AVAILABILITY_BLOCKERS,
  BOT_AVAILABILITY_CONDITIONS,
  botProfileIsStartable,
  botProfileStartability,
  type BotAvailabilityBlocker,
  type BotAvailabilityCondition,
  type BotProfileStartability,
  type BotProviderAvailabilitySnapshot,
  type BotProviderOperationState,
  type BotCardSourceId,
  type BotCardStatementId,
  BOT_GUARD_ABSTENTION_REASONS,
  BOT_LAYER_DECLARATIONS,
  BOT_LAYER_IDS,
  BOT_MAIA_MODEL,
  BOT_MEASUREMENT_IDS,
  BOT_MODEL_BANDS,
  BOT_PROFILE_CATALOG,
  BOT_PROFILE_CATALOG_RESOURCE,
  BOT_PROFILE_DIGESTS,
  BOT_PROFILE_FAMILIES,
  BOT_SAMPLER,
  BotCompositionError,
  BotProfileError,
  assertBotLayerComposition,
  botBehaviorDeclaration,
  botControlledTraits,
  botProfileDeclaration,
  botProfileId,
  catalogEntryFor,
  classifyPawnMoves,
  resolveBotProfileReference,
  type BotBehaviorDeclaration,
  type BotClassifierId,
  type BotDegradationReason,
  type BotGuardAbstentionReason,
  type BotGuardLayer,
  type BotLayerDeclaration,
  type BotLayerId,
  type BotMeasurementId,
  type BotModelBand,
  type BotProfileCatalogEntry,
  type BotProfileDeclaration,
  type BotProfileFamily,
  type BotProfileId,
  type BotProfileReference,
  type BotSamplerLayer,
  type BotTraitLayer,
  type CandidateBotLayer,
  type PawnMoveClassification,
  botEffectiveRequestedWidth,
} from "./bot-profile-catalog.js";
export {
  BOT_OPPONENT_PLY_RESULTS,
  BOT_OPPONENT_PLY_RESULT_KINDS,
  BOT_REQUEST_ID_PATTERN,
  BotOpponentPlyRequestError,
  botOpponentPlyRequestId,
  parseBotOpponentPlyRequest,
  parseBotOpponentPlyResultRow,
  runEventHeadDigest,
  type BotOpponentPlyRequest,
  type BotOpponentPlyResultKind,
  type BotOpponentPlyResultRow,
} from "./bot-opponent-ply.js";
export * from "./style-contract.js";
export * from "./style-atoms.js";
export * from "./skills-contract.js";
export * from "./concept-registry.js";
export * from "./provider-health.js";
// rfc/hint-distance.md — Guided Hint registry, wire and server-local compiler.
export {
  HINT_ABSTENTION_REASONS, HINT_DECLARATION_MATRIX, HINT_DISCLOSURE_BY_RUNG, HINT_DISCLOSURE_PROJECTION_IDS, HINT_DISTANCES, HINT_FAMILIES,
  HINT_HORIZON_PROJECTION_IDS, HINT_RELATIONS, HINT_RUNGS, HINT_RUNG_FORMS, HINT_SCAN_PLIES, HINT_SEARCH_SOURCE, HINT_SELECTION_ORDER, hintDeclarationRow,
  hintDisclosureIdentity, hintDisclosureProjectionId, hintDistanceIndex, hintHorizonProjectionId, hintRungIndex, minHintDistance,
  type HintDeclarationRow, type HintDisclosureProjectionId, type HintDistance, type HintFamily, type HintRelation, type HintRung,
} from "./hint-registry.js";
export {
  HINT_EMPTY_REASONS, HINT_FAILURE_REASONS, HINT_POLICY_REASONS, HINT_SOURCE_REASONS, HintExchangeError, hintDecisionStamp, hintDisclosureBoundarySeq,
  hintPolicyDecision, hintReceiptDigest, hintRequestId, nextHintRung, parseHintDeliveryReceipt, parseHintResponse,
  type HintDecisionStamp, type HintDeliveryMarks, type HintDeliveryReceipt, type HintEmptyReason, type HintFailureReason, type HintPieceMark,
  type HintPolicyDecision, type HintPolicyReason, type HintRequestState, type HintResponse, type HintSourceReason, type HintVoiceState,
} from "./hint-exchange.js";
export { HintHorizonMismatch, type HintDisclosurePayload, type HintHorizonOccurrence, type HintPieceIdentity } from "./hint-horizon.js";
export {
  HINT_COMPILER_VERSION, HINT_DISCLOSURE_RENDERERS, HINT_FORCED_MATE_ATTACKER_MOVES, assertHintDisclosurePacket, compileGuidedHintPacket,
  compileHintDeliveryReceipt, compileHintDisclosure, hintHorizonOwner, hintPacketRoots, hintSearchLineEvidence, hintSentence, hintVoiceCheck, selectHintHorizon,
  type GuidedHintPacket, type HintHorizonAuthority, type HintHorizonSelection, type HintRootIdentity, type SealedHintHorizon,
} from "./hint-distance.js";
