import { DRILL_RUN_SCHEMA_VERSION } from "@chess-tabiya/schema";

export { canonicalFen, transposeKey } from "./chess.js";
export {
  PROMOTION_ROLES,
  MOVE_DESTINATION_CONVENTION,
  MOVE_IDENTITY_CONVENTION,
  INBOUND_MOVE_DIALECT,
  exactLegalMoveMap,
  exactLegalMoves,
  exactMoveDestination,
  exactMoveIdentity,
  normalizeInboundMove,
  type ExactLegalMove,
  type ExactLegalMoveMap,
  type InboundMoveConversion,
  type InboundMoveSource,
  type PromotionRole as ExactPromotionRole,
} from "./legal-moves.js";
export {
  deviationAnchors,
  insideAuthoredBoundary,
  lineMembership,
  spineNodeIdFor,
  spinePositionIndex,
  type LineMembershipEntry,
  type LineVerdict,
} from "./line.js";
export { BranchQueryError, branchPath, branchPaths } from "./branch-path.js";
export {
  MAX_COMPARISON_BRANCHES,
  compareBranches,
  type BranchColumn,
  type BranchComparison,
  type BranchConsequence,
  type CheckpointHit,
  type ComparisonEvidenceEntry,
  type ComparisonLineEntry,
  type ComparisonRow,
  type ComparisonScore,
  type NodeRef,
  type ObjectiveTimelineEntry,
} from "./compare.js";
export { BRANCH_COLLAPSE_FLOOR, branchDecidedness, collapsedBranchIds, importedMainlineBranchId, renderCollapseExplanation, type AssessmentCategory, type AssessmentObjective, type CollapseExplanation, type Decidedness, type DecidednessGround, type TablebaseCategory as BranchTablebaseCategory } from "./branch-scale.js";
export { comparisonEngineTrajectory, comparisonNarrative, comparisonStrips, consumeComparisonEngineTrajectory, consumeComparisonStripEvidence, type BranchStrips, type ComparisonNarrative, type NarrativeGroup, type PieceRoute, type StripEntry } from "./compare-strips.js";
export {
  RuntimeError,
  assertActiveWriter,
  type IllegalMoveReason,
  type RuntimeErrorCode,
} from "./errors.js";
export { appendEvents, deriveSegments, eventsSince, groupsFromEvents, projectRun } from "./events.js";
export { feedbackDeliveryOpen, feedbackDisclosed } from "./feedback.js";
export { consumeShapeFiring, declareShapeFiringEvidence, shapeFiringEvidence, shapeFirings, type ShapeFiring, type ShapeTriggerSource } from "./shape-firing.js";
export { classifyPhase, developmentReading, isDevelopmentHome, renderPhaseReading, DEVELOPMENT_CONVENTION, DEVELOPMENT_HOMES, ENDGAME_MATERIAL_MAX, DEVELOPED_MATERIAL_MIN, OPENING_UNDEVELOPED_MIN, MIDDLEGAME_UNDEVELOPED_MAX, PHASE_PROVENANCE, type DetectedPhase, type DevelopmentReading, type PhaseReading } from "./phase.js";
export { backRankReading, defenderDutyReading, defenderDutyRelocatedEvents, defenderRemovedEvents, discoveredExecutedEvents, discoveredLatencyReading, loosePieceEvents, loosePieceReading, mateInOne, overloadedDefenderResponseConflict, promotionPressureReading, rayClassificationReading, rookOnSeventhReading, trappedPieceReading, BACK_RANK_CONVENTION, DEFENCE_DUTY_CONVENTION, TRAPPED_CONVENTION, type BackRankReading, type DefenderDuty, type DefenderDutyReading, type DefenderDutyRelocatedEvent, type DefenderRemovedEvent, type DiscoveredExecutedEvent, type DiscoveredLatencyReading, type GainedSliderRay, type LoosePieceEvent, type LoosePieceEventResult, type LoosePieceReading, type LoosePieceState, type MateInOneReading, type OverloadedDefenderConflict, type OverloadedDefenderConflictResult, type PromotionAvailability, type PromotionPressureReading, type RayClassification, type RayClassificationKind, type RayClassificationReading, type RookOnSeventhReading, type TrappedPieceReading, type TrappedPieceState } from "./tactics.js";
export { forcedMateAfterMove, MATE_PROOF_CONVENTION, MATE_PROOF_NODE_CAP, type ForcedMateAfterMoveProof, type ForcedMateAfterMoveResult, type MateProofStatus } from "./mate-proof.js";
export {
  MODULE_ANSWER_IMAGE,
  MODULE_CONTRACT_ERROR_CODES,
  MODULE_FORM_IMAGE,
  MODULE_IDS,
  MODULE_TIMING_IMAGE,
  ModuleContractError,
  compileModuleRegistry,
  type CompiledModuleRegistry,
  type ModuleAcceptanceDeclaration,
  type ModuleAnswerCeiling,
  type ModuleAnswerContract,
  type ModuleBudgets,
  type ModuleCeilings,
  type ModuleContractErrorCode,
  type ModuleDeclaration,
  type ModuleEmptyBehavior,
  type ModuleEvidenceClosure,
  type ModuleEvidenceDeclaration,
  type ModuleForm,
  type ModuleId,
  type ModuleInitiative,
  type ModuleSeatClass,
  type ModuleSelectionDeclaration,
  type ModuleTiming,
  type ModuleTimingDeclaration,
} from "./module-contract.js";
export { SILENT_ASSISTANCE, permittedAssistance, reviewingGrant, type AssistanceConfig, type AssistanceContext, type AssistancePermission } from "./assistance.js";
export { PRESET_CONTRACT_ERROR_CODES, PRESET_DECLARATIONS, PRESET_IDS, WORKFLOW_CONTEXT_POLICIES, WORKFLOW_CONTEXTS, PresetContractError, assertPresetFoundation, deriveWorkflowContext, presetDeclaration, workflowContextPolicy, type PresetContractErrorCode, type PresetDeclaration, type PresetId, type WorkflowContextId, type WorkflowContextPolicy } from "./presets.js";
export { CAMPAIGN_ACT_IDS, CampaignModuleError, assertCampaignUnlockAllowed, campaignModuleInventory, effectiveCampaignModules, isUnlockableModuleId, type CampaignAct, type CampaignActId, type CampaignDocument, type CampaignEconomy, type CampaignLayer, type CampaignNode, type CampaignNodeReward, type UnlockableModuleId } from "./campaign-contract.js";
export { CampaignStateError, campaignRunState, prestigeEligible, type CampaignChargeEarnedEvent, type CampaignChargeSpentEvent, type CampaignCursor, type CampaignEvent, type CampaignModuleUnlockedEvent, type CampaignNodeEnteredEvent, type CampaignNodeSeal, type CampaignNodeSealedEvent, type CampaignNodeVerdict, type CampaignRunState, type CampaignStateErrorCode } from "./campaign-state.js";
export { consumePivotalMarkers, liveAdmitted, liveMarkers, pivotalMarkerEvidence, pivotalMarkers, renderPivotalMarker, type PivotalKind, type PivotalMarker, type IrreversibilityDetail, type PhaseChangeDetail, type DivergenceDetail, type CollapseDetail } from "./pivotal.js";
export {
  TRANSITION_FEATURE_KINDS,
  capturedRole,
  irreversibility,
  matchesTransitionExpression,
  matchesTransitionFeature,
  transitionFeatureKinds,
  transitionReading,
  transitionSemanticFacts,
  type TransitionObservation,
  type TransitionReading,
  type TransitionSemanticFact,
} from "./transition.js";
export { endgameReading, renderEndgameReading, type EndgameTypeId, type EndgameReading, type TechniqueRef } from "./endgame.js";
export { retrospectivePivot } from "./adaptive.js";
export { STORY_MATE_CP, STORY_PIVOT_CP, renderReviewStoryEvidence, reviewStoryTitle, storyDeclaredEvidence, storyMoments, suggestTitle, type StoryEvaluation, type StoryMoment, type StoryMomentKind, type StoryProjection, type StoryTitleInput } from "./story.js";
export {
  voiceCheck,
  renderRecordedReading,
  BANNED_JUDGEMENTS,
  PRESCRIPTIVE_VERBS,
  CHESS_LEXICON,
  type EngineReadingValues,
  type EvidencePacket,
  type PositionEvidenceIndex,
  type RecordedReading,
  type ShapeEntryRef,
  type TablebaseReadingValues,
  type VoiceCheckResult,
} from "./voice.js";
export { matchKeyPoints, normalizeReasoningText } from "./reasoning.js";
export { terminalOutcome } from "./outcome.js";
export {
  FLOAT32_POLICY_MASS_TOLERANCE,
  PolicyMassError,
  humanConcessionMass,
  type HumanConcessionMass,
  type PolicyMassCandidate,
} from "./practical-difficulty.js";
export {
  AUTHORABLE_TEMPO_VERDICTS,
  DECLARED_UNGRADEABLE_VERDICTS,
  TEMPO_GRADEABLE_VERDICTS,
  TEMPO_VERDICTS,
  UNAUTHORED_TEMPO_DEFAULTS,
  tempoMovesFromRun,
  unauthoredTempoTransition,
  windowStates,
  type TempoMove,
  type TempoVerdict,
  type TimingWindowState,
  type TriggerResolver,
} from "./tempo.js";
export {
  STRUCTURAL_FEATURE_KINDS,
  emptyBoardDistance,
  matchesStructuralExpression,
  matchesStructuralFeature,
  mirrorExpression,
  observationIdentity,
  pawnConnectivityReading,
  pawnSafety,
  renderStructuralObservationChange,
  spaceReading,
  SPACE_CONVENTION,
  structuralDelta,
  structuralFeatureKinds,
  structuralReading,
  vacationReading,
  type FeatureComparison,
  type DistanceRole,
  type DistanceTarget,
  type FileRange,
  type FileTemplateFeature,
  type MirrorAxis,
  type PawnSafety,
  type PawnConnectivityColorReading,
  type PawnConnectivityReading,
  type ReachRole,
  type ReachScope,
  type Quantifier,
  type RankRange,
  type SquareRegion,
  type SquareTemplateFeature,
  type SpaceReading,
  type SpaceZone,
  type StructuralDelta,
  type StructuralExpression,
  type StructuralFeature,
  type StructuralFeatureKind,
  type StructuralObservation,
  type StructuralReading,
  type StructureId,
  type StructureMatch,
  type VacationReading,
} from "./structure.js";
export {
  declareStructuralPredicateEvidence,
  evaluateAuthoredStructuralPredicate,
  evaluateStructuralPredicate,
  matchesDeclaredStructuralPredicate,
  structuralEvidenceForAuthoring,
  structuralEvidenceForObjective,
  type AuthoredStructuralCondition,
  type DeclaredStructuralPredicateEvidence,
  type StructuralFeaturePredicateResult,
  type StructuralPredicateEvidencePayload,
  type StructuralPredicateResult,
  type StructuralPredicateTraceNode,
} from "./structural-evidence.js";
export {
  legIndexAt,
  trajectoryPolicyAt,
  trajectoryLegSpans,
  trajectoryVerdict,
  type TrajectoryLegOutcome,
  type TrajectoryLegSpan,
  type ResolvedTrajectoryPolicy,
  type TrajectoryTransition,
  type TrajectoryVerdict,
} from "./trajectory.js";
export {
  canonicalRunStart,
  digestSessionSource,
  isPackSession,
  sessionSource,
  type CreateRunSession,
  type PackRun,
  type SessionSource,
} from "./session.js";
export { attachEvidence } from "./evidence.js";
export { declareExactLegalMovesEvidence } from "./evidence-source-adapters.js";
export {
  GRADE_CONVENTION,
  assertMoveQualityGradeSentence,
  moveQualityGrade,
  renderMoveQualityGrade,
  renderMoveQualityResult,
  winPercentFromCp,
  type AbstainedGradeEvaluation,
  type CitedGradeConstant,
  type GradeContext,
  type GradeEvaluation,
  type GradeLane,
  type GradeScore,
  type GradeSide,
  type MoveQualityAbstention,
  type MoveQualityAbstentionReason,
  type MoveQualityArm,
  type MoveQualityClass,
  type MoveQualityGrade,
  type MoveQualityResult,
} from "./grade.js";
export {
  EVIDENCE_MANIFEST_ERROR_CODES,
  EvidenceManifestError,
  compileEvidenceManifest,
  evidenceForConsumer,
  assertConsumerEvidenceView,
  assertRenderedEvidenceView,
  renderEvidenceItems,
  type AdapterDeclaration,
  type AnswerDistance,
  type CompiledEvidenceManifest,
  type ConsumerDeclaration,
  type ConsumerEvidenceView,
  type DeclaredEvidence,
  type EvidenceBinding,
  type EvidenceContractDeclarations,
  type EvidenceDisposition,
  type EvidenceDerivation,
  type EvidenceForm,
  type EvidenceGrounding,
  type EvidenceManifestErrorCode,
  type EvidenceEligibilityDeclaration,
  type EvidenceReasonDeclaration,
  type EvidenceSelectionPolicy,
  type EvidenceSelectionPolicyDeclaration,
  type EvidenceRenderer,
  type EvidenceRendererRegistry,
  type EvidencePlane,
  type EvidenceRole,
  type EvidenceTiming,
  type ProducerDeclaration,
  type ProjectionDeclaration,
  type ProviderOffBehavior,
  type RenderedEvidenceItem,
  type RenderedEvidenceView,
  type SemanticEventDeclaration,
  type SemanticEventSign,
  type VersionedEvidenceId,
} from "./evidence-contract.js";
export {
  CURRENT_CONSUMER_OPERATION_IDS,
  EVIDENCE_ADAPTERS,
  EVIDENCE_CONSUMER_IDS,
  EVIDENCE_CONSUMERS,
  EVIDENCE_CONTRACT_DECLARATIONS,
  EVIDENCE_PRODUCER_IDS,
  EVIDENCE_PRODUCERS,
  EVIDENCE_ELIGIBILITY_DECLARATIONS,
  EVIDENCE_REASON_DECLARATIONS,
  EVIDENCE_SELECTION_POLICIES,
  PRIMARY_EVIDENCE_MANIFEST,
  AVOIDANCE_EVENT_PROJECTION_IDS,
  BREADTH_COLLECTOR_PROJECTION_IDS,
  BREADTH_CONVENTION_TEXT,
  BREADTH_EVENT_PROJECTION_IDS,
  CASTLING_EVENT_PROJECTION_IDS,
  SEMANTIC_EVENT_DECLARATIONS,
  SEMANTIC_EVENT_PROJECTION_IDS,
  SEMANTIC_CONVENTION_TEXT,
  SEMANTIC_WAVE_EVENT_PROJECTION_IDS,
  STRUCTURAL_EVENT_FAMILIES,
  STRUCTURAL_EVENT_PROJECTION_IDS,
  STRUCTURAL_PREDICATE_PROJECTION_IDS,
  STRUCTURAL_READING_PROJECTION_IDS,
  TACTICAL_COLLECTOR_PROJECTION_IDS,
  TRANSITION_READING_PROJECTION_IDS,
  TRANSITION_EVENT_PROJECTION_IDS,
  TRANSITION_GEOMETRY_EVENT_FAMILIES,
  TRANSITION_RULE_EVENT_FAMILIES,
  TACTICAL_EVENT_PROJECTION_IDS,
} from "./evidence-catalog.js";
export {
  assertEvidenceSelectionResult,
  assertSemanticEvidenceEvent,
  breadthSemanticEvents,
  canonicalMoveUci,
  capturedZoneDefenderOperands,
  checkZwischenzugObservedOperands,
  checkZwischenzugSemanticEvent,
  castlingSemanticEvents,
  compileSemanticEvidenceEvent,
  defenderConsequenceOperands,
  defenderConsequenceSemanticEvent,
  defenderExposureOperands,
  deflectionObservedOperands,
  deflectionObservedSemanticEvent,
  harassmentPressureSemanticEvent,
  interferenceObservedOperands,
  interferenceSemanticEvent,
  legalAlternativeEdges,
  localSemanticEvents,
  lineBlockerClearanceObservedOperands,
  lineBlockerClearanceSemanticEvent,
  loosePieceSemanticEvents,
  pawnIslandSemanticEvents,
  pawnContactTimingSemanticEvent,
  overloadExploitationObservedOperands,
  overloadExploitationSemanticEvent,
  semanticDutyEvents,
  squareClearanceObservedOperands,
  squareClearanceSemanticEvent,
  attractionObservedOperands,
  attractionObservedSemanticEvent,
  discoveredExecutedSemanticEvents,
  derivedExchangeSemanticEvents,
  tradeCompletedSemanticEvent,
  openFileOccupancyOperands,
  selectLocalSemanticEvidence,
  selectSemanticEvidence,
  structuralSemanticEvents,
  tacticalSemanticEvents,
  transitionSemanticEvents,
  type CounterfactualAbsenceOperands,
  type CapturedZoneDefenderOperands,
  type DefenderConsequenceOperands,
  type DeflectionObservedOperands,
  type AttractionObservedOperands,
  type LineBlockerClearanceObservedOperands,
  type SquareClearanceObservedOperands,
  type InterferenceObservedOperands,
  type CheckZwischenzugObservedOperands,
  type OverloadExploitationObservedOperands,
  type DefenderExposureOperands,
  type EvidenceSelectionResult,
  type SelectedEvidenceFact,
  type SemanticEvidenceEvent,
  type SemanticEventAnchor,
  type SemanticEventInput,
  type SemanticSelectionInput,
  type StructuralSemanticEventOperands,
  type TransitionSemanticEventOperands,
  type TacticalSemanticEventOperands,
  type CastlingSemanticEventOperands,
  type DerivedExchangeSemanticEventOperands,
  type PawnIslandEventOperands,
  type OpenFileOccupancyOperands,
  type TradeCompletedEventOperands,
} from "./semantic-evidence.js";
export {
  declareAuthoredClaimDeliveryEvidence,
  declareAuthoredClaimEvidence,
  declareAuthoredStructuralConditionEvidence,
  declareAvoidanceEvidence,
  declareCompareDerivedEvidence,
  declareEndgameReadingEvidence,
  declareEvidenceReferenceResolution,
  declareLegalExchangeEvidence,
  declareCaptureClassEvidence,
  declareThreatEvidence,
  declareDoubleAttackEvidence,
  declareForkSurvivalEvidence,
  declareReplyBreadthEvidence,
  declareCheckEventEvidence,
  declareLoosePieceEvidence,
  declareRayClassificationEvidence,
  declareMateInOneEvidence,
  declareDiscoveredLatencyEvidence,
  declareTrappedPieceEvidence,
  declareBackRankEvidence,
  declareRookOnSeventhEvidence,
  declarePawnConnectivityEvidence,
  declareSpaceEvidence,
  declareLoosePieceEventEvidence,
  declarePawnIslandEventEvidence,
  declareDiscoveredExecutedEvidence,
  declarePromotionPressureEvidence,
  declareTradeCompletedEvidence,
  declareCastlingRightsEvidence,
  declareCastlingRightsLostEvidence,
  declareCastlingLegalityEvidence,
  declareCandidateMajorityEvidence,
  declareCandidateFeatureVectorEvidence,
  declareCapturedZoneDefenderEvidence,
  declareDefenderConsequenceEvidence,
  declareDefenderExposureEvidence,
  declareDefenderDutyEvidence,
  declareDefenderDutyRelocatedEvidence,
  declareDefenderRemovedEvidence,
  declareForcedMateAfterMoveEvidence,
  declareOverloadedDefenderConflictEvidence,
  declareDeflectionObservedEvidence,
  declareAttractionObservedEvidence,
  declareLineBlockerClearanceEvidence,
  declareSquareClearanceEvidence,
  declareInterferenceEvidence,
  declareCheckZwischenzugEvidence,
  declareOverloadExploitationEvidence,
  declareExplorerPopulationEvidence,
  declareExplorerPositionEvidence,
  declareHarassmentPressureEvidence,
  declareKingZoneEventEvidence,
  declareKingZoneReadingEvidence,
  declareLivePacketEvidence,
  declareMaterialRoleEventEvidence,
  declareMaterialRoleReadingEvidence,
  declareMaiaEventEvidence,
  declareMaiaCandidateWdlEvidence,
  declareMaiaPolicyEvidence,
  declareMobilityEventEvidence,
  declareMobilityReadingEvidence,
  declareNamedStructureEvidence,
  declareOpponentProviderEvidence,
  declarePackPhaseEvidence,
  declareOpenFileOccupancyEvidence,
  declarePawnContactTimingEvidence,
  declarePawnContactsEvidence,
  declarePawnDynamicsEvidence,
  declarePawnTransitionEvidence,
  declarePhaseReadingEvidence,
  declareDevelopmentReadingEvidence,
  declarePivotalMarkerEvidence,
  declareRecordedEngineEvidence,
  declareRecordedTablebaseEvidence,
  declareRunRecordEvidence,
  declareShapeFiringSourceEvidence,
  declareSquareControlEventEvidence,
  declareSquareControlReadingEvidence,
  declareSourcingRecordEvidence,
  declareStockfishEvalEvidence,
  declareStoryDerivedEvidence,
  declareStructuralPredicateFeatureEvidence,
  declareStructuralPredicateResultEvidence,
  declareStructuralReadingSourceEvidence,
  declareStructuralSemanticSourceEvidence,
  declareSyzygyResultEvidence,
  declareSyzygyCategoryEvidence,
  declareSyzygyDistanceEvidence,
  declareTransitionReadingSourceEvidence,
  declareTransitionSemanticSourceEvidence,
} from "./evidence-source-adapters.js";
export type { MaiaCandidateWdlProjection } from "./evidence-source-adapters.js";
export {
  RULES_EVIDENCE_FACTS,
  THEORY_EVIDENCE_FACTS,
  engineEvidenceRef,
  isEngineEvidenceRef,
  isMachineEvidenceRef,
  tablebaseEvidenceRef,
  packEvidenceRef,
  packAbsentEvidenceRef,
  rulesEvidenceRef,
  theoryEvidenceRef,
  tempoEvidenceRef,
  type EngineEvidenceRef,
  type PackEvidenceRef,
  type PackAbsentEvidenceRef,
  type RulesEvidenceFact,
  type RulesEvidenceRef,
  type TheoryEvidenceFact,
  type TheoryEvidenceRef,
  type TempoEvidenceRef,
} from "./evidence-ref.js";
export {
  consumeMoveTransition,
  consumePositionStructure,
  consumeSelectedSquareSight,
  declareStructuralReadingEvidence,
  declareTransitionReadingEvidence,
  moveTransitionEvidence,
  positionStructureEvidence,
  selectedSquareSightEvidence,
} from "./reading-evidence.js";
export {
  MATERIAL_VALUES,
  applyObjectiveEvidenceProposal,
  evaluateObjective,
  evaluateObjectivePredicate,
  materialBalance,
  requestObjectiveEvidence,
  transitionObjective,
  type FenPredicate,
  type MaterialBalancePredicate,
  type ObjectiveEvaluationResult,
  type ObjectiveEvidenceProposal,
  type ObjectiveEvidenceRequest,
  type ObjectiveEvidenceUpgrader,
  type ObjectivePredicate,
  type ObjectiveTransitionRule,
  type RulesFactPredicate,
} from "./objective.js";
export {
  ObjectiveEvidenceError,
  ObjectiveTransitionError,
  isObjectiveTransitionAllowed,
} from "./objective-state.js";
export { PgnExportError, exportPgn } from "./pgn.js";
export {
  PackRunPgnError,
  exportPackRunPgn,
  type PackRunPgnErrorCode,
} from "./pack-pgn.js";
export {
  ReplayError,
  opponentMovesFromEvents,
  readBackReplay,
  resistanceOnPath,
  type OpponentMoveReadback,
  type AppliedPolicyCount,
  type PathResistance,
  type RequestedLegPolicy,
  type ReadBackReplay,
  type ResistanceEngineCount,
} from "./replay.js";
export {
  appendOpponentPly,
  commitMove,
  createRun,
  fork,
  historyFrom,
  reachCheckpoint,
  rewind,
  rewindToCheckpoint,
  revealFeedback,
  type AppendOpponentPlyOptions,
  type CommitMoveOptions,
  type CreateRunInput,
  type LegacyCreateRunInput,
  type ForkOptions,
  type JobObserver,
} from "./runtime.js";
export type {
  Actor,
  Branch,
  BranchGroup,
  BranchGroupMember,
  CheckpointReachedEvent,
  Cursor,
  DrillRun,
  DrillRunEvent,
  EvidenceAttachedEvent,
  EvidenceKind,
  EvidencePayload,
  EvidenceSource,
  EventDraft,
  ExecutionLocus,
  MutationResult,
  Node,
  ObjectiveState,
  OpponentSelection,
  OpponentMoveSelectedEvent,
  PredictionRecordedEvent,
  ReasoningDetection,
  ReasoningRecordedEvent,
  ReasoningTranscript,
  GroupCreatedEvent,
  GroupResistance,
  GroupSource,
  PolicyConfig,
  PolicyModeApplied,
  PositionOpponentPolicy,
  RunFeedbackPolicy,
  RunOpponentMode,
  RunOpponentPolicy,
  RunOutcome,
  RunSessionKind,
  LiveSessionKind,
  MarkBrush,
  RunMark,
  RunStart,
  SelectionCandidate,
  SelectionEngineIdentity,
  Segment,
  VersionedPolicy,
} from "./types.js";
export { LIVE_SESSION_KINDS, MARK_BRUSHES, RUN_OPPONENT_MODES } from "./types.js";

export {
  EXCHANGE_PIECE_VALUES,
  LEGAL_EXCHANGE_CONVENTION,
  captureClassEvent,
  captureExchangeClass,
  exchangeCaptureAt,
  legalCaptureMovesTo,
  legalExchange,
  legalExchangeForMove,
  type CaptureExchangeClass,
  type CaptureClassEvent,
  type ExchangePieceIdentity,
  type LegalExchangeBranch,
  type LegalExchangeResult,
  type LegalExchangeStep,
} from "./exchange.js";

export {
  REPLY_HORIZON,
  THREAT_CONVENTION,
  checkEvent,
  doubleAttackEvent,
  forkSurvivesReply,
  replyBreadth,
  threats,
  type CheckEvent,
  type DoubleAttackEvent,
  type DoubleAttackTarget,
  type ForkSurvivalResult,
  type ReplyBreadth,
  type Threat,
  type ThreatResult,
} from "./tactics.js";

export {
  castlingLegality,
  castlingRights,
  castlingRightsLost,
  type CastlingLegalityIssue,
  type CastlingRightLostEvent,
  type CastlingRightsState,
  type CastlingWing,
} from "./castling.js";

export {
  squareControlEvents,
  squareControlReading,
  type ControlledSquare,
  type LegalControlSet,
  type SquareControlEvent,
  type SquareControlEvents,
  type SquareController,
  type SquareControlReading,
} from "./square-control.js";

export {
  LOCAL_NON_LOSING_CONVENTION,
  legalMovesReading,
  pieceDestinationEvents,
  pieceDestinationsReading,
  type ColorPieceDestinations,
  type PieceDestinations,
  type PieceDestinationsEvent,
  type PieceDestinationsEventResult,
  type PieceDestinationsReading,
  type LegalMovesReading,
} from "./mobility.js";

export {
  CANDIDATE_MAJORITY_CONVENTION,
  RACE_ARRIVAL_CONVENTION,
  candidateMajorityReading,
  harassmentPressureSequence,
  pawnContactTimingSequence,
  pawnContactsReading,
  pawnDynamicsEvents,
  pawnTransitionEvents,
  promotionRaceGeometry,
  promotionRaceTablebase,
  type BoardPieceIdentity,
  type CandidateMajorityReading,
  type HarassmentPressureSequence,
  type PawnContactTimingSequence,
  type PawnContactsReading,
  type PawnDynamicsEvent,
  type PawnTransitionEvent,
  type PawnIdentity,
  type PromotionRacePawn,
  type PromotionRaceGeometry,
  type PromotionRaceGeometryResult,
  type PromotionRaceTablebaseInput,
  type PromotionRaceTablebaseEvent,
  type PromotionRaceTablebaseResult,
  type PressureLine,
  type RecordedMoveAnchor,
} from "./pawn-dynamics.js";

export {
  KING_SHELTER_CONVENTION,
  KING_ZONE_CONVENTION,
  kingZoneEvents,
  kingZoneReading,
  type KingEscapeSet,
  type KingZoneEvent,
  type KingZoneParticipant,
  type KingZoneReading,
  type KingZoneState,
} from "./king-state.js";

export {
  MATERIAL_ROLE_SIGNATURE_CONVENTION,
  isMaterialRole,
  materialRoleAsymmetryEvent,
  materialRoleSignatureReading,
  type MaterialRole,
  type MaterialRoleAsymmetryEvent,
  type MaterialRoleSignatureReading,
  type MaterialRoleVector,
} from "./material-state.js";

export const runtimeBuildInfo = Object.freeze({
  packageName: "@chess-tabiya/runtime",
  runSchemaVersion: DRILL_RUN_SCHEMA_VERSION,
});
