// Generated by `UPDATE_PROVIDER_PARSER_IMPLEMENTATION=1 make provider-exchange-check`; checked by
// packages/runtime/src/provider-parsers.test.ts. The digest covers the complete static local
// import closure of provider-parsers.ts (rfc/provider-exchange-and-execution.md §4).
export const PROVIDER_PARSER_IMPLEMENTATION = Object.freeze({
  files: Object.freeze([
    "packages/runtime/src/chess.ts",
    "packages/runtime/src/legal-moves.ts",
    "packages/runtime/src/provider-digest.ts",
    "packages/runtime/src/provider-parsers.ts",
    "packages/runtime/src/provider-requests.ts",
    "packages/runtime/src/provider-types.ts"
  ] as readonly string[]),
  closureDigest: "sha256:8f3ffcd90fdd32232538996de90370f18e5dc82ce071b764936479a62cf41e34",
} as const);
