// GENERATED by `make semantic-validation-update` (tools/semantic-validation-build.ts). Do not edit by hand.
// `make semantic-validation-check` recomputes this file and semantic-validation-receipt.generated.json and fails on any byte difference.
// The full per-case/per-population receipt is the JSON sibling; the runtime imports only these compact verdicts.
import type { SemanticValidationVerdictTable } from "./semantic-validation.js";

export const SEMANTIC_VALIDATION_RECEIPT: SemanticValidationVerdictTable = {
  "schemaVersion": 1,
  "receiptSha256": "eb6f734aa542befbec146cc2b7bfd2aa425cc3284fd4fc9760e2725eb6def31a",
  "verdicts": [
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.activity.event.open_file_occupancy",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.bounded_target.immediate",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.exchange.capture_class",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.exchange.trade_completed",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.exchange.trade_completed",
          "version": 2
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.king.captured_zone_defender",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.material.event.role_asymmetry",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.pawn.event.transitions",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.pawn.sequence.contact_timing",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.pawn.sequence.contact_timing",
          "version": 2
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.pawn.sequence.harassment_pressure",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.pawn.sequence.harassment_pressure",
          "version": 2
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.semantic_avoidance.backward_pawn",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "counterfactual",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.semantic_avoidance.direct_attack_count",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "counterfactual",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.semantic_avoidance.doubled_pawn",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "counterfactual",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.semantic_avoidance.half_open_file",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "counterfactual",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.semantic_avoidance.isolated_pawn",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "counterfactual",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.semantic_avoidance.king_opposition",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "counterfactual",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.semantic_avoidance.king_zone",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "counterfactual",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.semantic_avoidance.line_blockers",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "counterfactual",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.semantic_avoidance.loose_piece",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "counterfactual",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.semantic_avoidance.open_file",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "counterfactual",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.semantic_avoidance.passed_pawn",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "counterfactual",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.semantic_avoidance.pawn_islands",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "counterfactual",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.semantic_avoidance.piece_count",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "counterfactual",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.tactic.attraction_observed",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.tactic.attraction_observed",
          "version": 2
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "external_label"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.tactic.check_zwischenzug_observed",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.tactic.check_zwischenzug_observed",
          "version": 2
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "external_label"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.tactic.defender_exposure",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.tactic.deflection_observed",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.tactic.deflection_observed",
          "version": 2
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "external_label"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.tactic.discovered_executed",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.tactic.interference_observed",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.tactic.interference_observed",
          "version": 2
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "external_label"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.tactic.line_blocker_clearance_observed",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.tactic.line_blocker_clearance_observed",
          "version": 2
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "external_label"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.tactic.overload_exploitation_observed",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.tactic.overload_exploitation_observed",
          "version": 2
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "external_label"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.tactic.sequence.defender_consequence",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.tactic.sequence.defender_consequence",
          "version": 2
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.tactic.square_clearance_observed",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "derived.tactic.square_clearance_observed",
          "version": 2
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "external_label"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.castling.event.rights_lost",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.king.event.zone_state",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.mobility.event.piece_destinations",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.pawn.event.dynamics",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.square.event.control",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.structural.event.backward_pawn",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.structural.event.direct_attack_count",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.structural.event.doubled_pawn",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.structural.event.half_open_file",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.structural.event.isolated_pawn",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.structural.event.king_opposition",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.structural.event.king_zone",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.structural.event.line_blockers",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.structural.event.open_file",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.structural.event.passed_pawn",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.structural.event.pawn_islands",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.structural.event.piece_count",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.tactic.consequence.reply_breadth",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "semantic_negative",
        "orientation",
        "counterfactual"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.tactic.event.check",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.tactic.event.defender_duty_relocated",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.tactic.event.defender_removed",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.tactic.event.double_attack",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.tactic.event.loose_piece",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.transition.event.capture",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.transition.event.castled",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.transition.event.checkmate",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.transition.event.clock_reset",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.transition.event.defended_duty",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.transition.event.developed",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.transition.event.last_of_role",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.transition.event.occupied_attack",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.transition.event.occupied_defence",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.transition.event.pawn_contact",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.transition.event.piece_escape",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.transition.event.promotion",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "event",
        "projection": {
          "id": "rules.transition.event.slider_ray",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation"
      ]
    },
    {
      "subject": {
        "kind": "reading",
        "projection": {
          "id": "derived.bounded_target.bounded_return",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "imported_population"
      ]
    },
    {
      "subject": {
        "kind": "reading",
        "projection": {
          "id": "derived.bounded_target.named_material_target",
          "version": 1
        }
      },
      "verdict": "unvalidated",
      "open": [
        "positive",
        "semantic_negative",
        "orientation",
        "imported_population"
      ]
    }
  ]
};
