// DISPOSABLE research harness — D366 (design/BACKLOG.md).
// Not production code. Builds the endgame probe set and its tablebase ground truth.
//
// Sources of positions, in order of preference:
//   1. every position on the spine / deviation set of the 14 `phase: "endgame"` packs
//      in content/drafts that is inside the 7-man Syzygy range;
//   2. positions REACHED DURING PLAY from those, generated by a seeded walk in which
//      BOTH sides play a uniformly random *category-preserving* move (so the winner
//      keeps winning and the defender keeps defending, and the walk stays on the
//      endgame technique the pack is about instead of wandering into noise).
//
// Ground truth comes from the repo's own LichessTablebaseSource (single-flight,
// four-deep queue) — probed strictly sequentially, one position at a time.
import { appendFileSync, existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { Chess } from "chessops/chess";
import { makeFen, parseFen } from "chessops/fen";
import { isNormal } from "chessops/types";
import { makeUci, parseUci } from "chessops/util";

import {
  LichessTablebaseSource,
  invertTablebaseCategory,
  type TablebaseCategory,
  type TablebasePosition,
} from "../../apps/server/src/tablebase.js";

interface SpineNode {
  readonly id: string;
  readonly moveUci: string;
  readonly children?: readonly SpineNode[];
}
interface Pack {
  readonly id: string;
  readonly phase: string;
  readonly start: { readonly fen: string; readonly side: string };
  readonly objective?: { readonly type?: string };
  readonly spine?: readonly SpineNode[];
  readonly deviations?: readonly { readonly at: { readonly fen?: string } }[];
}

interface Seed {
  readonly packId: string;
  readonly learnerSide: string;
  readonly objectiveType: string;
  readonly origin: "spine" | "deviation" | "start";
  readonly fen: string;
  readonly startFen: string;
  readonly historyUci: readonly string[];
}

function pieceCount(fen: string): number {
  return (fen.split(" ")[0] ?? "").replace(/[^a-zA-Z]/gu, "").length;
}

function legalMoves(position: Chess): readonly string[] {
  const out: string[] = [];
  for (const [from, targets] of position.allDests()) {
    for (const to of targets) {
      const isPawn = position.board.getRole(from) === "pawn";
      const rank = to >> 3;
      if (isPawn && (rank === 0 || rank === 7)) {
        for (const promotion of ["queen", "rook", "bishop", "knight"] as const) {
          out.push(makeUci({ from, to, promotion }));
        }
      } else {
        out.push(makeUci({ from, to }));
      }
    }
  }
  return out.sort();
}

// The mover's own view of a category, ranked. `unknown` is never accepted.
// The three-class projection follows the SHIPPED grading semantics in
// apps/server/src/tablebase.ts OBJECTIVE_ASSESSMENT_SETS: `win` counts only
// `win`; `hold` counts `draw`, `cursed-win` and `blessed-loss` alike.
export function resultClass(category: TablebaseCategory): "win" | "draw" | "loss" | null {
  if (category === "win" || category === "syzygy-win" || category === "maybe-win") return "win";
  if (category === "cursed-win" || category === "draw" || category === "blessed-loss") return "draw";
  if (category === "loss" || category === "syzygy-loss" || category === "maybe-loss") return "loss";
  return null;
}
export function classRank(value: "win" | "draw" | "loss"): number {
  return value === "win" ? 2 : value === "draw" ? 1 : 0;
}

// A deterministic 32-bit PRNG so the walk is reproducible from the seed integer.
function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function collectSeeds(dir: string): Seed[] {
  const seeds: Seed[] = [];
  for (const file of readdirSync(dir).sort()) {
    if (!file.endsWith(".json")) continue;
    if (/\.(evidence|job|sources|browser)\.json$/u.test(file)) continue;
    const pack = JSON.parse(readFileSync(join(dir, file), "utf8")) as Pack;
    if (pack.phase !== "endgame" || pack.start?.fen === undefined) continue;
    const root = Chess.fromSetup(parseFen(pack.start.fen).unwrap()).unwrap();
    const push = (
      origin: Seed["origin"],
      fen: string,
      startFen: string,
      history: readonly string[],
    ): void => {
      seeds.push({
        packId: pack.id,
        learnerSide: pack.start.side,
        objectiveType: pack.objective?.type ?? "n/a",
        origin,
        fen,
        startFen,
        historyUci: [...history],
      });
    };
    const walk = (node: SpineNode, position: Chess, history: readonly string[]): void => {
      push("spine", makeFen(position.toSetup()), pack.start.fen, history);
      const move = parseUci(node.moveUci);
      if (move === undefined || !isNormal(move) || !position.isLegal(move)) {
        throw new Error(`${pack.id}: illegal spine move ${node.moveUci}`);
      }
      const next = position.clone();
      next.play(move);
      const nextHistory = [...history, node.moveUci];
      for (const child of node.children ?? []) walk(child, next, nextHistory);
      if ((node.children ?? []).length === 0 && !next.isEnd()) {
        push("spine", makeFen(next.toSetup()), pack.start.fen, nextHistory);
      }
    };
    push("start", pack.start.fen, pack.start.fen, []);
    for (const node of pack.spine ?? []) walk(node, root.clone(), []);
    for (const deviation of pack.deviations ?? []) {
      const fen = deviation.at.fen;
      if (fen !== undefined) push("deviation", fen, fen, []);
    }
  }
  return seeds;
}

interface Record_ {
  readonly fen: string;
  readonly packId: string;
  readonly learnerSide: string;
  readonly objectiveType: string;
  readonly origin: string;
  readonly walkId: string;
  readonly ply: number;
  readonly startFen: string;
  readonly historyUci: readonly string[];
  readonly pieceCount: number;
  readonly sideToMove: string;
  readonly legalCount: number;
  readonly category: TablebaseCategory;
  readonly resultClass: string;
  readonly dtz: number | null;
  readonly moves: readonly {
    readonly uci: string;
    readonly san: string;
    readonly moverCategory: TablebaseCategory;
    readonly moverClass: string | null;
    readonly dtz: number | null;
    readonly preciseDtz: number | null;
  }[];
}

async function main(): Promise<void> {
  const dir = process.argv[2]!;
  const outPath = process.argv[3]!;
  const walksPerSeed = Number(process.argv[4] ?? "3");
  const walkPlies = Number(process.argv[5] ?? "12");
  const delayMs = Number(process.argv[6] ?? "260");

  const collected = collectSeeds(dir).filter((seed) => pieceCount(seed.fen) <= 7);
  // Round-robin the seeds across packs so that stopping the run early still leaves a
  // corpus balanced over the 14 packs rather than one exhausted alphabetically.
  const byPack = new Map<string, Seed[]>();
  for (const seed of collected) {
    const bucket = byPack.get(seed.packId);
    if (bucket === undefined) byPack.set(seed.packId, [seed]);
    else bucket.push(seed);
  }
  const seeds: Seed[] = [];
  for (let index = 0; seeds.length < collected.length; index += 1) {
    for (const bucket of byPack.values()) if (bucket[index] !== undefined) seeds.push(bucket[index]!);
  }
  process.stderr.write(`seeds<=7men=${seeds.length} packs=${byPack.size}\n`);

  const source = new LichessTablebaseSource({ timeoutMs: 20_000 });
  const probeCache = new Map<string, TablebasePosition>();
  const emitted = new Set<string>();
  if (existsSync(outPath)) {
    for (const line of readFileSync(outPath, "utf8").split("\n")) {
      if (line.trim() === "") continue;
      const parsed = JSON.parse(line) as Record_;
      if (parsed.fen === undefined) continue;
      emitted.add(parsed.fen);
      // Rehydrate the tablebase answer from the record so a resumed run does not
      // re-probe the network for a position it already has ground truth for.
      probeCache.set(parsed.fen, {
        category: parsed.category,
        dtz: parsed.dtz,
        moves: parsed.moves.map((move) => ({
          uci: move.uci,
          san: move.san,
          category: invertTablebaseCategory(move.moverCategory),
          dtz: move.dtz,
          preciseDtz: move.preciseDtz ?? null,
        })),
      });
    }
    process.stderr.write(`resume: ${emitted.size} already emitted and rehydrated\n`);
  } else {
    writeFileSync(outPath, "");
  }
  let probes = 0;
  const probe = async (fen: string): Promise<TablebasePosition> => {
    const cached = probeCache.get(fen);
    if (cached !== undefined) return cached;
    for (let attempt = 0; ; attempt += 1) {
      try {
        const value = await source.probe(fen);
        probes += 1;
        probeCache.set(fen, value);
        await new Promise((resolve) => setTimeout(resolve, delayMs));
        return value;
      } catch (error) {
        if (attempt >= 3) throw error;
        // LichessTablebaseSource caches a failure for 60s keyed on the FEN
        // (tablebase.ts #fetch), so any retry inside that window is answered by the
        // cached error rather than by the network. Back off past the cache lifetime.
        process.stderr.write(`retry ${String(attempt)} ${String(error)}\n`);
        await new Promise((resolve) => setTimeout(resolve, 65_000));
      }
    }
  };

  const emit = (
    seed: Seed,
    walkId: string,
    ply: number,
    position: Chess,
    fen: string,
    history: readonly string[],
    probed: TablebasePosition,
  ): void => {
    if (emitted.has(fen)) return;
    emitted.add(fen);
    const record: Record_ = {
      fen,
      packId: seed.packId,
      learnerSide: seed.learnerSide,
      objectiveType: seed.objectiveType,
      origin: seed.origin,
      walkId,
      ply,
      startFen: seed.startFen,
      historyUci: [...history],
      pieceCount: pieceCount(fen),
      sideToMove: position.turn,
      legalCount: legalMoves(position).length,
      category: probed.category,
      resultClass: resultClass(probed.category) ?? "unknown",
      dtz: probed.dtz,
      moves: probed.moves.map((move) => {
        const mover = invertTablebaseCategory(move.category);
        return {
          uci: move.uci,
          san: move.san,
          moverCategory: mover,
          moverClass: resultClass(mover),
          dtz: move.dtz,
          preciseDtz: move.preciseDtz,
        };
      }),
    };
    appendFileSync(outPath, `${JSON.stringify(record)}\n`);
  };

  let seedIndex = 0;
  for (const seed of seeds) {
    seedIndex += 1;
    for (let walk = 0; walk < walksPerSeed; walk += 1) {
      const rng = mulberry32(
        walk * 1_000_003 + [...seed.fen].reduce((acc, ch) => (acc * 31 + ch.charCodeAt(0)) >>> 0, 7),
      );
      let position = Chess.fromSetup(parseFen(seed.fen).unwrap()).unwrap();
      let fen = seed.fen;
      let history = [...seed.historyUci];
      for (let ply = 0; ply <= walkPlies; ply += 1) {
        if (position.isEnd() || pieceCount(fen) > 7) break;
        let probed: TablebasePosition;
        try {
          probed = await probe(fen);
        } catch (error) {
          process.stderr.write(`GIVEUP ${fen} ${String(error)}\n`);
          break;
        }
        const own = resultClass(probed.category);
        if (own === null) break;
        emit(seed, `${seed.packId}#${String(seedIndex)}/${String(walk)}`, ply, position, fen, history, probed);
        const legal = new Set(legalMoves(position));
        const usable = probed.moves.filter((move) => legal.has(move.uci));
        if (usable.length === 0) break;
        const preserving = usable.filter(
          (move) => resultClass(invertTablebaseCategory(move.category)) === own,
        );
        const pool = preserving.length > 0 ? preserving : usable;
        const chosen = pool[Math.floor(rng() * pool.length)]!;
        const parsed = parseUci(chosen.uci);
        if (parsed === undefined || !position.isLegal(parsed)) break;
        const next = position.clone();
        next.play(parsed);
        position = next;
        fen = makeFen(position.toSetup());
        history = [...history, chosen.uci];
      }
    }
    process.stderr.write(
      `[${String(seedIndex)}/${String(seeds.length)}] emitted=${String(emitted.size)} probes=${String(probes)}\n`,
    );
  }
  process.stderr.write(`DONE emitted=${String(emitted.size)} networkProbes=${String(probes)}\n`);
}

void main();
