// rfc/pack-capability-contract.md §5 — every capability whose lifecycle is not "active at version 1".
//
// A version transition is authored HERE: when `make capability-check` reports that a stored digest
// no longer matches the tree, either revert the meaning change or add the next version to its
// subject's row (the obsolete row `deprecated`/`withdrawn` with a same-subject successor) and run
// `make capability-declarations`. The obsolete declaration keeps its frozen digest; every pack or
// shape that required it then appears in `make migration-plan`'s judgement debt.
//
// Only a subject's CURRENT row may name another subject as its successor (a replacement: the whole
// subject is superseded). Obsolete rows advance within their own subject.

import { capabilityId, type CapabilityVersion } from "@chess-tabiya/schema";

import type { CapabilityLifecycleRow } from "./registry.js";

const v = (value: number): CapabilityVersion => ({ kind: "integer", value });

export const CAPABILITY_LIFECYCLE: readonly CapabilityLifecycleRow[] = Object.freeze([
  // Provider-exchange §§7/9: a bound opponent source is a successor, not a rewrite of operator-only v1.
  { subjectId: "live.syzygy.position_result", versions: [{ version: v(1), disposition: { kind: "deprecated", successor: capabilityId("live.syzygy.position_result", 2), reasonCode: "superseded", reason: "The whole registered delivery now has an opponent-selection consumer; version 1 retains the operator-only source declaration" } }, { version: v(2), disposition: { kind: "active" } }] },
  // Provider-exchange §1: sequence-valued derivation operands; frozen predecessors retained.
  { subjectId: "selection.semantic_policy", versions: [{ version: v(1), disposition: { kind: "deprecated", successor: capabilityId("selection.semantic_policy", 2), reasonCode: "superseded", reason: "The shared manifest compiler retains ordered repeated derivation operands; version 1 retains its original source image" } }, { version: v(2), disposition: { kind: "active" } }] },
  // Provider-exchange §8: the value-route/compiled evidence closure gains the sealed, move-free
  // Explorer summary. Never regenerate that extended closure over the committed @1 meanings.
  { subjectId: "engineCondition.engine_eval_swing", versions: [{ version: v(1), disposition: { kind: "deprecated", successor: capabilityId("engineCondition.engine_eval_swing", 2), reasonCode: "superseded", reason: "The shared evidence value-route closure now includes the sealed Explorer summary; version 1 retains its original source image" } }, { version: v(2), disposition: { kind: "deprecated", successor: capabilityId("engineCondition.engine_eval_swing", 3), reasonCode: "superseded", reason: "The shared manifest compiler retains ordered repeated derivation operands; version 2 retains its original source image" } }, { version: v(3), disposition: { kind: "deprecated", successor: capabilityId("engineCondition.engine_eval_swing", 4), reasonCode: "superseded", reason: "Canonical semantic-validation implementation receipts are refreshed after the isolated run-subject API registration; version 3 retains its original source image" } }, { version: v(4), disposition: { kind: "deprecated", successor: capabilityId("engineCondition.engine_eval_swing", 5), reasonCode: "superseded", reason: "The shared value-route closure gains exact Maia occurrence authorities; version 4 retains its original source image" } }, { version: v(5), disposition: { kind: "deprecated", successor: capabilityId("engineCondition.engine_eval_swing", 6), reasonCode: "superseded", reason: "The opponent selector admits the whole registered Syzygy delivery before selection; the consumer and semantic-validation closure is refreshed, while version 5 retains its original source image" } }, { version: v(6), disposition: { kind: "active" } }] },
  { subjectId: "engineCondition.engine_mate_appears", versions: [{ version: v(1), disposition: { kind: "deprecated", successor: capabilityId("engineCondition.engine_mate_appears", 2), reasonCode: "superseded", reason: "The shared evidence value-route closure now includes the sealed Explorer summary; version 1 retains its original source image" } }, { version: v(2), disposition: { kind: "deprecated", successor: capabilityId("engineCondition.engine_mate_appears", 3), reasonCode: "superseded", reason: "The shared manifest compiler retains ordered repeated derivation operands; version 2 retains its original source image" } }, { version: v(3), disposition: { kind: "deprecated", successor: capabilityId("engineCondition.engine_mate_appears", 4), reasonCode: "superseded", reason: "Canonical semantic-validation implementation receipts are refreshed after the isolated run-subject API registration; version 3 retains its original source image" } }, { version: v(4), disposition: { kind: "deprecated", successor: capabilityId("engineCondition.engine_mate_appears", 5), reasonCode: "superseded", reason: "The shared value-route closure gains exact Maia occurrence authorities; version 4 retains its original source image" } }, { version: v(5), disposition: { kind: "deprecated", successor: capabilityId("engineCondition.engine_mate_appears", 6), reasonCode: "superseded", reason: "The opponent selector admits the whole registered Syzygy delivery before selection; the consumer and semantic-validation closure is refreshed, while version 5 retains its original source image" } }, { version: v(6), disposition: { kind: "active" } }] },
  { subjectId: "engineCondition.tablebase_category_regression", versions: [{ version: v(1), disposition: { kind: "deprecated", successor: capabilityId("engineCondition.tablebase_category_regression", 2), reasonCode: "superseded", reason: "The shared evidence value-route closure now includes the sealed Explorer summary; version 1 retains its original source image" } }, { version: v(2), disposition: { kind: "deprecated", successor: capabilityId("engineCondition.tablebase_category_regression", 3), reasonCode: "superseded", reason: "The shared manifest compiler retains ordered repeated derivation operands; version 2 retains its original source image" } }, { version: v(3), disposition: { kind: "deprecated", successor: capabilityId("engineCondition.tablebase_category_regression", 4), reasonCode: "superseded", reason: "Canonical semantic-validation implementation receipts are refreshed after the isolated run-subject API registration; version 3 retains its original source image" } }, { version: v(4), disposition: { kind: "deprecated", successor: capabilityId("engineCondition.tablebase_category_regression", 5), reasonCode: "superseded", reason: "The shared value-route closure gains exact Maia occurrence authorities; version 4 retains its original source image" } }, { version: v(5), disposition: { kind: "deprecated", successor: capabilityId("engineCondition.tablebase_category_regression", 6), reasonCode: "superseded", reason: "The opponent selector admits the whole registered Syzygy delivery before selection; the consumer and semantic-validation closure is refreshed, while version 5 retains its original source image" } }, { version: v(6), disposition: { kind: "active" } }] },
  { subjectId: "engineCondition.tablebase_dtz_regression", versions: [{ version: v(1), disposition: { kind: "deprecated", successor: capabilityId("engineCondition.tablebase_dtz_regression", 2), reasonCode: "superseded", reason: "The shared evidence value-route closure now includes the sealed Explorer summary; version 1 retains its original source image" } }, { version: v(2), disposition: { kind: "deprecated", successor: capabilityId("engineCondition.tablebase_dtz_regression", 3), reasonCode: "superseded", reason: "The shared manifest compiler retains ordered repeated derivation operands; version 2 retains its original source image" } }, { version: v(3), disposition: { kind: "deprecated", successor: capabilityId("engineCondition.tablebase_dtz_regression", 4), reasonCode: "superseded", reason: "Canonical semantic-validation implementation receipts are refreshed after the isolated run-subject API registration; version 3 retains its original source image" } }, { version: v(4), disposition: { kind: "deprecated", successor: capabilityId("engineCondition.tablebase_dtz_regression", 5), reasonCode: "superseded", reason: "The shared value-route closure gains exact Maia occurrence authorities; version 4 retains its original source image" } }, { version: v(5), disposition: { kind: "deprecated", successor: capabilityId("engineCondition.tablebase_dtz_regression", 6), reasonCode: "superseded", reason: "The opponent selector admits the whole registered Syzygy delivery before selection; the consumer and semantic-validation closure is refreshed, while version 5 retains its original source image" } }, { version: v(6), disposition: { kind: "active" } }] },
  { subjectId: "fenPredicate.structuralFeature", versions: [{ version: v(1), disposition: { kind: "deprecated", successor: capabilityId("fenPredicate.structuralFeature", 2), reasonCode: "superseded", reason: "The shared evidence value-route closure now includes the sealed Explorer summary; version 1 retains its original source image" } }, { version: v(2), disposition: { kind: "deprecated", successor: capabilityId("fenPredicate.structuralFeature", 3), reasonCode: "superseded", reason: "The shared manifest compiler retains ordered repeated derivation operands; version 2 retains its original source image" } }, { version: v(3), disposition: { kind: "deprecated", successor: capabilityId("fenPredicate.structuralFeature", 4), reasonCode: "superseded", reason: "Canonical semantic-validation implementation receipts are refreshed after the isolated run-subject API registration; version 3 retains its original source image" } }, { version: v(4), disposition: { kind: "deprecated", successor: capabilityId("fenPredicate.structuralFeature", 5), reasonCode: "superseded", reason: "The shared value-route closure gains exact Maia occurrence authorities; version 4 retains its original source image" } }, { version: v(5), disposition: { kind: "deprecated", successor: capabilityId("fenPredicate.structuralFeature", 6), reasonCode: "superseded", reason: "The opponent selector admits the whole registered Syzygy delivery before selection; the consumer and semantic-validation closure is refreshed, while version 5 retains its original source image" } }, { version: v(6), disposition: { kind: "active" } }] },
  { subjectId: "opponent.practical_slice", versions: [{ version: v(1), disposition: { kind: "deprecated", successor: capabilityId("opponent.practical_slice", 2), reasonCode: "superseded", reason: "The shared evidence value-route closure now includes the sealed Explorer summary; version 1 retains its original source image" } }, { version: v(2), disposition: { kind: "deprecated", successor: capabilityId("opponent.practical_slice", 3), reasonCode: "superseded", reason: "The shared manifest compiler retains ordered repeated derivation operands; version 2 retains its original source image" } }, { version: v(3), disposition: { kind: "deprecated", successor: capabilityId("opponent.practical_slice", 4), reasonCode: "superseded", reason: "Canonical semantic-validation implementation receipts are refreshed after the isolated run-subject API registration; version 3 retains its original source image" } }, { version: v(4), disposition: { kind: "deprecated", successor: capabilityId("opponent.practical_slice", 5), reasonCode: "superseded", reason: "The shared value-route closure gains exact Maia occurrence authorities; version 4 retains its original source image" } }, { version: v(5), disposition: { kind: "deprecated", successor: capabilityId("opponent.practical_slice", 6), reasonCode: "superseded", reason: "The opponent selector admits the whole registered Syzygy delivery before selection; the consumer and semantic-validation closure is refreshed, while version 5 retains its original source image" } }, { version: v(6), disposition: { kind: "active" } }] },
  { subjectId: "opponent.selection", versions: [{ version: v(1), disposition: { kind: "deprecated", successor: capabilityId("opponent.selection", 2), reasonCode: "superseded", reason: "The shared evidence value-route closure now includes the sealed Explorer summary; version 1 retains its original source image" } }, { version: v(2), disposition: { kind: "deprecated", successor: capabilityId("opponent.selection", 3), reasonCode: "superseded", reason: "The shared manifest compiler retains ordered repeated derivation operands; version 2 retains its original source image" } }, { version: v(3), disposition: { kind: "deprecated", successor: capabilityId("opponent.selection", 4), reasonCode: "superseded", reason: "Canonical semantic-validation implementation receipts are refreshed after the isolated run-subject API registration; version 3 retains its original source image" } }, { version: v(4), disposition: { kind: "deprecated", successor: capabilityId("opponent.selection", 5), reasonCode: "superseded", reason: "The shared value-route closure gains exact Maia occurrence authorities; version 4 retains its original source image" } }, { version: v(5), disposition: { kind: "deprecated", successor: capabilityId("opponent.selection", 6), reasonCode: "superseded", reason: "The opponent selector admits the whole registered Syzygy delivery before selection; the consumer and semantic-validation closure is refreshed, while version 5 retains its original source image" } }, { version: v(6), disposition: { kind: "active" } }] },
  // §5 "the three prose-only deprecations get typed successors" — two have a truthful successor.
  {
    subjectId: "successCondition.plan_consequence",
    versions: [{ version: v(1), disposition: { kind: "deprecated", successor: capabilityId("successCondition.structural_feature"), reasonCode: "superseded", reason: "plan_consequence is deprecated; use structural_feature with a plan_signature leaf (lint PLAN_CONSEQUENCE_DEPRECATED)" } }],
  },
  {
    subjectId: "structuralFeature.pawn_count",
    versions: [{ version: v(1), disposition: { kind: "deprecated", successor: capabilityId("structuralFeature.piece_count"), reasonCode: "superseded", reason: "pawn_count is deprecated; use piece_count with role pawn (PAWN_COUNT_DEPRECATED)" } }],
  },
  // `retryVariants` is not flattened (§5, D1327): the catalogue relation advances to `variantOf`,
  // while the scheduler read (`retryVariants.scheduler`) stays active.
  {
    subjectId: "catalogue.variant_relation",
    versions: [
      { version: v(1), disposition: { kind: "deprecated", successor: capabilityId("catalogue.variant_relation", 2), reasonCode: "superseded", reason: "retryVariants is a catalogue relation, not a run modifier; variantOf is its successor" } },
      { version: v(2), disposition: { kind: "active" } },
    ],
  },
  // §5a: the two declared-but-unimplemented opponent modes.
  { subjectId: "opponentPolicy.mode.plan_defense", versions: [{ version: v(1), disposition: { kind: "unimplemented", implementationRef: "apps/server/src/capabilities.ts#DECLARED_UNIMPLEMENTED_POLICY_MODES" } }] },
  { subjectId: "opponentPolicy.mode.human_external", versions: [{ version: v(1), disposition: { kind: "unimplemented", implementationRef: "apps/server/src/capabilities.ts#DECLARED_UNIMPLEMENTED_POLICY_MODES" } }] },
  // The format register's assistance and error rows keep their real subject kinds (§4.2).
  { subjectId: "assistance.arrows", versions: [{ version: v(1), disposition: { kind: "unmeasured", experiment: "Measure and define a directed structural primitive before enabling system-drawn sight arrows" } }] },
  {
    subjectId: "error.SIMULATE_BUDGET_EXCEEDED",
    versions: [{ version: v(1), disposition: { kind: "withdrawn", reason: "No simulation economy or budget exists; reintroduce a refusal with the economy that needs it", removedAt: "0.25", successor: null, noSuccessor: { kind: "no_migration_exists", reason: "the refusal named a budget that never existed" } } }],
  },
]);
