// DISPOSABLE research harness — D1066. Not production code.
import { readFileSync, writeFileSync } from "node:fs";

import { Chess, normalizeMove } from "chessops/chess";
import { makeFen, parseFen } from "chessops/fen";
import type { Color, Role, SquareName } from "chessops/types";
import { makeSquare, makeUci, parseUci } from "chessops/util";
import { describe, expect, it } from "vitest";

import { PRIMARY_EVIDENCE_MANIFEST } from "../../packages/runtime/src/evidence-catalog.js";
import {
  localSemanticEvents,
  legalAlternativeEdges,
  selectSemanticEvidence,
  type SelectedEvidenceFact,
  type SemanticEvidenceEvent,
} from "../../packages/runtime/src/semantic-evidence.js";

const INPUT = new URL("../../planning/evidence-foundation-ux/d1061-bestline-distance-results.json", import.meta.url);
const OUTPUT = new URL("../../planning/evidence-foundation-ux/d1066-semantic-horizon-results.json", import.meta.url);
const REPORT = new URL("../../planning/evidence-foundation-ux/d1066-semantic-horizon-results.md", import.meta.url);
const POLICY = Object.freeze({ id: "research.r2_candidate", version: 1 });

// Closed from learner-modules Appendix B. Avoidance is generated by selection, not locally.
const NUDGE_EVENT_IDS = new Set([
  ...["backward_pawn", "doubled_pawn", "isolated_pawn", "passed_pawn", "open_file", "half_open_file", "king_zone", "king_opposition"].map((family) => `rules.structural.event.${family}@1`),
  ...["castled", "last_of_role", "pawn_contact", "checkmate", "promotion", "capture", "developed"].map((family) => `rules.transition.event.${family}@1`),
  "rules.castling.event.rights_lost@1", "rules.tactic.event.double_attack@1", "rules.tactic.event.check@1", "rules.tactic.event.loose_piece@1",
  "derived.exchange.capture_class@1", "derived.exchange.trade_completed@1", "rules.structural.event.pawn_islands@1",
  "rules.pawn.event.dynamics@1", "derived.pawn.event.transitions@1", "rules.king.event.zone_state@1",
  "derived.king.captured_zone_defender@1", "derived.activity.event.open_file_occupancy@1",
]);

interface InputProbe { readonly arm: string; readonly pv: readonly string[] }
interface InputRow {
  readonly packId: string;
  readonly phase: "opening" | "middlegame" | "cross_phase";
  readonly fen: string;
  readonly probes: readonly InputProbe[];
}
interface Edge { readonly beforeFen: string; readonly moveUci: string; readonly afterFen: string }
interface StageActor { readonly color: Color; readonly role: Role; readonly from: SquareName; readonly to: SquareName }
interface Stageable { readonly actor: StageActor; readonly targets: readonly SquareName[] }
interface Refused { readonly reason: "counterfactual_has_no_single_target" | "event_has_no_square_target" | "event_adapter_absent" }

function position(fen: string): Chess { return Chess.fromSetup(parseFen(fen).unwrap()).unwrap(); }

function edge(beforeFen: string, rawUci: string): Edge {
  const before = position(beforeFen);
  const parsed = parseUci(rawUci);
  if (parsed === undefined || !("from" in parsed)) throw new TypeError(`Invalid PV UCI ${rawUci}`);
  const move = normalizeMove(before, parsed);
  if (!("from" in move) || !before.isLegal(move)) throw new TypeError(`Illegal PV UCI ${rawUci} from ${beforeFen}`);
  const moveUci = makeUci(move);
  before.play(move);
  return Object.freeze({ beforeFen, moveUci, afterFen: makeFen(before.toSetup()) });
}

function projection(event: { readonly projection: { readonly id: string; readonly version: number } }): string {
  return `${event.projection.id}@${event.projection.version}`;
}

function record(value: unknown): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return {};
  return value as Record<string, unknown>;
}

function square(value: unknown): SquareName | undefined {
  return typeof value === "string" && /^[a-h][1-8]$/u.test(value) ? value as SquareName : undefined;
}

function squares(values: readonly unknown[]): readonly SquareName[] {
  return Object.freeze([...new Set(values.flatMap((value) => {
    const direct = square(value);
    if (direct !== undefined) return [direct];
    const item = record(value);
    return [square(item.square), square(item.target), square(item.to), square(item.after)].filter((candidate): candidate is SquareName => candidate !== undefined);
  }))].sort());
}

function movedActor(event: SemanticEvidenceEvent): StageActor {
  const before = position(event.anchor.beforeFen);
  const parsed = parseUci(event.anchor.moveUci);
  if (parsed === undefined || !("from" in parsed)) throw new TypeError(`Invalid event move ${event.anchor.moveUci}`);
  const move = normalizeMove(before, parsed);
  if (!("from" in move) || !before.isLegal(move)) throw new TypeError(`Illegal event move ${event.anchor.moveUci}`);
  const piece = before.board.get(move.from);
  if (piece === undefined) throw new TypeError(`Event move has no actor ${event.anchor.moveUci}`);
  return Object.freeze({ color: piece.color, role: piece.role, from: makeSquare(move.from), to: makeSquare(move.to) });
}

function structuralTargets(event: SemanticEvidenceEvent, payload: Record<string, unknown>): readonly SquareName[] {
  const observation = record(event.sign === "lost" ? payload.before : payload.after);
  const direct = squares(Array.isArray(observation.squares) ? observation.squares : []);
  if (direct.length > 0) return direct;
  const fen = event.sign === "lost" ? event.anchor.beforeFen : event.anchor.afterFen;
  const state = position(fen);
  const file = typeof observation.file === "string" && /^[a-h]$/u.test(observation.file) ? observation.file.charCodeAt(0) - 97 : undefined;
  if (file !== undefined && (observation.kind === "open_file" || observation.kind === "half_open_file")) return Object.freeze(Array.from({ length: 8 }, (_, rank) => makeSquare(rank * 8 + file)));
  if (file !== undefined && typeof observation.color === "string") return Object.freeze([...state.board.pieces(observation.color as Color, "pawn")].filter((value) => value % 8 === file).map(makeSquare).sort());
  if (observation.kind === "king_zone" && typeof observation.color === "string") {
    const king = state.board.kingOf(observation.color as Color);
    return king === undefined ? [] : [makeSquare(king)];
  }
  if (observation.kind === "king_opposition") return Object.freeze(([state.board.kingOf("white"), state.board.kingOf("black")] as const).filter((value): value is NonNullable<typeof value> => value !== undefined).map(makeSquare).sort());
  return [];
}

/** Literal projection-specific target extraction. There is deliberately no recursive fallback. */
function stageable(fact: SelectedEvidenceFact): Stageable | Refused {
  if (fact.kind === "counterfactual_absence") return Object.freeze({ reason: "counterfactual_has_no_single_target" });
  const event = fact.event;
  const id = projection(event);
  const payload = record(event.operands);
  let targets: readonly SquareName[] = [];
  if (id.startsWith("rules.structural.event.") && id !== "rules.structural.event.pawn_islands@1") {
    targets = structuralTargets(event, payload);
  } else if (id.startsWith("rules.transition.event.")) {
    if (id === "rules.transition.event.checkmate@1") {
      const after = position(event.anchor.afterFen);
      const king = after.board.kingOf(after.turn);
      targets = king === undefined ? [] : [makeSquare(king)];
    } else targets = squares([payload.to]);
  } else if (id === "rules.tactic.event.double_attack@1") {
    targets = squares(Array.isArray(payload.targets) ? payload.targets : []);
  } else if (id === "rules.tactic.event.check@1") {
    targets = squares([payload.checkedKing]);
  } else if (id === "rules.tactic.event.loose_piece@1") {
    const state = record(event.sign === "lost" ? payload.before : payload.after);
    targets = squares([record(state.piece)]);
  } else if (id === "derived.exchange.capture_class@1" || id === "derived.exchange.trade_completed@1") {
    targets = squares([payload.landingSquare]);
  } else if (id === "rules.pawn.event.dynamics@1") {
    const subjects = record(payload.subjects);
    targets = squares([subjects.minor, subjects.pawn, subjects.white, subjects.black, record(subjects.after).pawn]);
  } else if (id === "derived.pawn.event.transitions@1") {
    targets = squares([record(record(payload.pawn).after), record(payload.contact).target, record(payload.capture).to]);
  } else if (id === "rules.king.event.zone_state@1") {
    targets = squares([record(payload.king).after]);
  } else if (id === "derived.king.captured_zone_defender@1") {
    targets = squares([payload.capturedSquare]);
  } else if (id === "derived.activity.event.open_file_occupancy@1") {
    targets = squares([record(record(payload.piece).after)]);
  } else if (id === "rules.castling.event.rights_lost@1" || id === "rules.structural.event.pawn_islands@1") {
    return Object.freeze({ reason: "event_has_no_square_target" });
  } else return Object.freeze({ reason: "event_adapter_absent" });
  return targets.length === 0
    ? Object.freeze({ reason: "event_has_no_square_target" })
    : Object.freeze({ actor: movedActor(event), targets });
}

const EVENT_CACHE = new Map<string, readonly SemanticEvidenceEvent[]>();

function filteredEvents(current: Edge): readonly SemanticEvidenceEvent[] {
  const key = `${current.beforeFen}\0${current.moveUci}\0${current.afterFen}`;
  const cached = EVENT_CACHE.get(key);
  if (cached !== undefined) return cached;
  const events = Object.freeze(localSemanticEvents(current.beforeFen, current.moveUci, current.afterFen).filter((event) => NUDGE_EVENT_IDS.has(projection(event))));
  EVENT_CACHE.set(key, events);
  return events;
}

function moduleSelection(current: Edge) {
  return selectSemanticEvidence(PRIMARY_EVIDENCE_MANIFEST, POLICY, {
    ...current,
    playedEvents: filteredEvents(current),
    evaluateAlternative: (alternative) => filteredEvents(alternative),
  });
}

const CRITICAL = new Set(["rules.transition.event.checkmate@1", "rules.transition.event.promotion@1", "rules.transition.event.castled@1", "rules.transition.event.last_of_role@1"]);

/** Same measured R2 20%/cap-two convention, but only literal stageable events and no avoidance. */
function horizonSelection(current: Edge): readonly SemanticEvidenceEvent[] {
  const played = filteredEvents(current).filter((event) => "actor" in stageable({ kind: "played_event", event, sameFamilyShare: 0 }));
  const alternatives = legalAlternativeEdges(current.beforeFen, current.moveUci);
  const familyCounts = new Map<string, number>();
  for (const alternative of alternatives) {
    const families = new Set(filteredEvents(alternative)
      .filter((event) => "actor" in stageable({ kind: "played_event", event, sameFamilyShare: 0 }))
      .map((event) => `${projection(event)}:${event.sign}`));
    for (const family of families) familyCounts.set(family, (familyCounts.get(family) ?? 0) + 1);
  }
  return Object.freeze(played.flatMap((event) => {
    const critical = CRITICAL.has(projection(event));
    const share = alternatives.length === 0 ? 0 : (familyCounts.get(`${projection(event)}:${event.sign}`) ?? 0) / alternatives.length;
    return critical || alternatives.length >= 8 && share <= 0.20 ? [{ event, critical, support: 1 - share }] : [];
  }).sort((left, right) => Number(right.critical) - Number(left.critical) || right.support - left.support || projection(left.event).localeCompare(projection(right.event)) || left.event.id.localeCompare(right.event)).slice(0, 2).map((value) => value.event));
}

function pct(numerator: number, denominator: number): string { return denominator === 0 ? "n/a" : `${(100 * numerator / denominator).toFixed(1)}%`; }

function timing(values: readonly number[]) {
  const ordered = [...values].sort((left, right) => left - right);
  const at = (quantile: number) => ordered[Math.min(ordered.length - 1, Math.floor(quantile * ordered.length))] ?? 0;
  return { n: values.length, meanMs: values.reduce((sum, value) => sum + value, 0) / values.length, p50Ms: at(0.50), p95Ms: at(0.95), maxMs: ordered.at(-1) ?? 0 };
}

describe("D1066 semantic-horizon coverage", () => {
  it("joins fixed PVs to module-filtered selection and literal stage adapters", () => {
    const source = JSON.parse(readFileSync(INPUT, "utf8")) as { readonly rows: readonly InputRow[] };
    const lines: Array<Record<string, unknown>> = [];
    const selectedProjectionCounts = new Map<string, number>();
    const horizonProjectionCounts = new Map<string, number>();
    const refusalCounts = new Map<string, number>();
    const horizonTimings: number[] = [], compatibilityTimings: number[] = [];
    for (const row of source.rows) for (const arm of ["depth12", "movetime100_a"] as const) {
      const probe = row.probes.find((candidate) => candidate.arm === arm);
      if (probe === undefined) throw new TypeError(`Missing ${arm} for ${row.packId}`);
      let fen = row.fen;
      let first: Record<string, unknown> | undefined;
      const refusals: Array<Record<string, unknown>> = [];
      for (const [index, rawUci] of probe.pv.slice(0, 4).entries()) {
        const current = edge(fen, rawUci);
        const horizonStarted = performance.now();
        const horizon = horizonSelection(current);
        horizonTimings.push(performance.now() - horizonStarted);
        const compatibilityStarted = performance.now();
        const baseline = moduleSelection(current);
        compatibilityTimings.push(performance.now() - compatibilityStarted);
        for (const fact of baseline.selected) {
          const id = projection(fact.event);
          selectedProjectionCounts.set(id, (selectedProjectionCounts.get(id) ?? 0) + 1);
          const adapted = stageable(fact);
          if ("reason" in adapted) {
            refusalCounts.set(adapted.reason, (refusalCounts.get(adapted.reason) ?? 0) + 1);
            refusals.push({ projection: id, ply: index + 1, reason: adapted.reason });
            continue;
          }
        }
        for (const event of horizon) {
          const id = projection(event);
          horizonProjectionCounts.set(id, (horizonProjectionCounts.get(id) ?? 0) + 1);
          const adapted = stageable({ kind: "played_event", event, sameFamilyShare: 0 });
          if ("reason" in adapted) throw new TypeError(`Horizon selector admitted unstageable ${id}: ${adapted.reason}`);
          if (first === undefined) first = { projection: id, sign: event.sign, ply: index + 1, actor: adapted.actor, targets: adapted.targets, firstMoveUci: probe.pv[0] };
        }
        fen = current.afterFen;
        if (first !== undefined) break;
      }
      lines.push({ packId: row.packId, positionFen: row.fen, phase: row.phase, arm, pvPliesAvailable: probe.pv.length, first: first ?? null, refusals });
    }
    const depth12 = lines.filter((line) => line.arm === "depth12");
    const time100 = lines.filter((line) => line.arm === "movetime100_a");
    const byPhase = Object.fromEntries(["opening", "middlegame", "cross_phase"].map((phase) => {
      const members = depth12.filter((line) => line.phase === phase);
      return [phase, { lines: members.length, stageable: members.filter((line) => line.first !== null).length }];
    })) as Record<string, { lines: number; stageable: number }>;
    let sameFamily = 0, samePly = 0, bothStageable = 0;
    for (const depth of depth12) {
      const timed = time100.find((line) => line.positionFen === depth.positionFen)!;
      const left = depth.first as { projection: string; ply: number } | null;
      const right = timed.first as { projection: string; ply: number } | null;
      if (left === null || right === null) continue;
      bothStageable += 1;
      if (left.projection === right.projection) sameFamily += 1;
      if (left.ply === right.ply) samePly += 1;
    }
    const depth12Stageable = depth12.filter((line) => line.first !== null).length;
    const summary = {
      positions: source.rows.length,
      lines: lines.length,
      depth12Stageable,
      depth12WithinFourRate: depth12Stageable / depth12.length,
      byPhase,
      selectedProjectionCounts: Object.fromEntries([...selectedProjectionCounts].sort()),
      horizonProjectionCounts: Object.fromEntries([...horizonProjectionCounts].sort()),
      refusalCounts: Object.fromEntries([...refusalCounts].sort()),
      timingMs: { horizonColdFirst: timing(horizonTimings), compatibilityAfterCache: timing(compatibilityTimings) },
      stability: { bothStageable, sameFamily, samePly },
    };
    writeFileSync(OUTPUT, `${JSON.stringify({ measuredAt: new Date().toISOString(), contract: { accepts: [...NUDGE_EVENT_IDS].sort(), policy: "research.r2_candidate@1", horizonPlies: 4 }, summary, lines }, null, 2)}\n`, "utf8");
    const report = [
      "# D1066 semantic-horizon results", "",
      `Depth-12 stageable within four plies: **${depth12Stageable}/${depth12.length} (${pct(depth12Stageable, depth12.length)})**.`, "",
      "| phase | lines | stageable | reach |", "|---|---:|---:|---:|",
      ...Object.entries(byPhase).map(([phase, value]) => `| ${phase} | ${value.lines} | ${value.stageable} | ${pct(value.stageable, value.lines)} |`), "",
      `Both engine arms stageable: ${bothStageable}; same first projection: ${sameFamily}/${bothStageable}; same occurrence ply: ${samePly}/${bothStageable}.`, "",
      `Candidate horizon compile+selection: mean ${summary.timingMs.horizonColdFirst.meanMs.toFixed(1)} ms, p95 ${summary.timingMs.horizonColdFirst.p95Ms.toFixed(1)} ms per searched PV edge on this machine.`, "",
      "The compatibility arm applies shipped R2 after the Appendix-B projection filter. The reported reach arm additionally requires a literal actor/target before ranking and disables alternative-only avoidance, while preserving R2's 20%/cap-two rule. This is a research candidate, not a production policy. No LLM selects or labels an event. Sequence-only Wave-C motifs are outside `localSemanticEvents` and therefore outside these reach figures.", "",
    ];
    writeFileSync(REPORT, report.join("\n"), "utf8");
    expect(source.rows).toHaveLength(64);
    expect(lines).toHaveLength(128);
    expect(summary.depth12WithinFourRate).toBeGreaterThanOrEqual(0);
  });
});
